/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class AfConfig extends TemplateConfig {
	public AfConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Spesiaal");
		addNamespaceAlias(1, "Bespreking");
		addNamespaceAlias(2, "Gebruiker");
		addNamespaceAlias(3, "Gebruikerbespreking");
		addNamespaceAlias(5, "Wikipediabespreking");
		addNamespaceAlias(6, "Lêer", "Beeld");
		addNamespaceAlias(7, "Lêerbespreking", "Beeldbespreking");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWikibespreking");
		addNamespaceAlias(10, "Sjabloon");
		addNamespaceAlias(11, "Sjabloonbespreking");
		addNamespaceAlias(12, "Hulp");
		addNamespaceAlias(13, "Hulpbespreking");
		addNamespaceAlias(14, "Kategorie");
		addNamespaceAlias(15, "Kategoriebespreking");

		addI18nCIAlias("redirect", "#AANSTUUR", "#REDIRECT");
		addI18nCIAlias("notoc", "__GEENIO__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__GEENGALERY__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__DWINGIO__", "__FORCETOC__");
		addI18nCIAlias("toc", "__IO__", "__TOC__");
		addI18nCIAlias("noeditsection", "__GEENNUWEAFDELING__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "HUIDIGEMAAND", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "HUIDIGEMAAND1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "HUIDIGEMAANDNAAM", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthabbrev", "HUIDIGEMAANDAFK", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "HUIDIGEDAG", "CURRENTDAY");
		addI18nAlias("currentday2", "HUIDIGEDAG2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "HUIDIGEDAGNAAM", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "HUIDIGEJAAR", "CURRENTYEAR");
		addI18nAlias("currenttime", "HUIDIGETYD", "CURRENTTIME");
		addI18nAlias("currenthour", "HUIDIGEUUR", "CURRENTHOUR");
		addI18nAlias("numberofpages", "AANTALBLADSYE", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "AANTALARTIKELS", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "AANTALLêERS", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "AANTALGEBRUIKERS", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "AANTALAKTIEWEGEBRUIKERS", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "AANTALWYSIGINGS", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "AANTALKEERGESIEN", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "BLADSYNAAM", "PAGENAME");
		addI18nAlias("namespace", "NAAMSPASIE", "NAMESPACE");
		addI18nAlias("talkspace", "BESPREKINGSBLADSY", "TALKSPACE");
		addI18nAlias("fullpagename", "VOLBLADSYNAAM", "FULLPAGENAME");
		addI18nAlias("img_thumbnail", "duimnael", "thumbnail", "thumb");
		addI18nAlias("img_right", "regs", "right");
		addI18nAlias("img_left", "links", "left");
		addI18nAlias("img_none", "geen", "none");
		addI18nAlias("img_center", "senter", "center", "centre");
		addI18nAlias("img_framed", "omraam", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "raamloos", "frameless");
		addI18nAlias("img_border", "raam", "border");
		addI18nAlias("img_top", "bo", "top");
		addI18nAlias("img_text_top", "teks-bo", "text-top");
		addI18nAlias("img_middle", "middel", "middle");
		addI18nAlias("img_bottom", "onder", "bottom");
		addI18nAlias("img_text_bottom", "teks-onder", "text-bottom");
		addI18nAlias("img_link", "skakel=$1", "link=$1");
		addI18nAlias("sitename", "WERFNAAM", "SITENAME");
		addI18nCIAlias("server", "BEDIENER", "SERVER");
		addI18nCIAlias("servername", "BEDIENERNAAM", "SERVERNAME");
		addI18nCIAlias("gender", "GESLAG:", "GENDER:");
		addI18nAlias("localweek", "HUIDIGEWEEK", "LOCALWEEK");
		addI18nCIAlias("plural", "MEERVOUD", "PLURAL:");
		addI18nCIAlias("fullurl", "VOLURL", "FULLURL:");
		addI18nAlias("displaytitle", "VERTOONTITEL", "DISPLAYTITLE");
		addI18nAlias("currentversion", "HUIDIGEWEERGAWE", "CURRENTVERSION");
		addI18nCIAlias("language", "#TAAL:", "#LANGUAGE:");
		addI18nCIAlias("special", "spesiaal", "special");
		addI18nCIAlias("filepath", "LêERPAD:", "FILEPATH:");
		addI18nCIAlias("tag", "etiket", "tag");
		addI18nAlias("pagesize", "BLADSYGROOTTE", "PAGESIZE");
		addI18nAlias("index", "__INDEKS__", "__INDEX__");
		addI18nAlias("noindex", "__GEENINDEKS__", "__NOINDEX__");
		addI18nCIAlias("url_path", "PAD", "PATH");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://af.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "af";
	}
}
