/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class AngConfig extends TemplateConfig {
	public AngConfig() {
		addNamespaceAlias(-1, "Syndrig");
		addNamespaceAlias(1, "Mōtung", "Gesprec", "Motung");
		addNamespaceAlias(2, "Brūcend", "Brucend");
		addNamespaceAlias(3, "Brūcendmōtung", "Brucendmotung");
		addNamespaceAlias(6, "Ymele", "Biliþ");
		addNamespaceAlias(7, "Ymelmōtung", "Biliþmotung", "Biliþmōtung");
		addNamespaceAlias(9, "MediaWikimōtung");
		addNamespaceAlias(10, "Bysen");
		addNamespaceAlias(11, "Bysenmōtung", "Bysengesprec", "Bysenmotung");
		addNamespaceAlias(12, "Help");
		addNamespaceAlias(13, "Helpmōtung", "Helpgesprec", "Helpmotung");
		addNamespaceAlias(14, "Flocc");
		addNamespaceAlias(15, "Floccmōtung", "Floccgesprec", "Floccmotung");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ang.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ang";
	}
}
