/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class AzConfig extends TemplateConfig {
	public AzConfig() {
		addNamespaceAlias(-1, "Xüsusi");
		addNamespaceAlias(0, "");
		addNamespaceAlias(1, "Müzakirə");
		addNamespaceAlias(2, "İstifadəçi");
		addNamespaceAlias(3, "İstifadəçi_müzakirəsi");
		addNamespaceAlias(5, "Wikipedia_müzakirəsi");
		addNamespaceAlias(6, "Şəkil");
		addNamespaceAlias(7, "Şəkil_müzakirəsi");
		addNamespaceAlias(8, "MediaWiki", "MediyaViki");
		addNamespaceAlias(9, "MediaWiki_müzakirəsi", "MediyaViki_müzakirəsi");
		addNamespaceAlias(10, "Şablon");
		addNamespaceAlias(11, "Şablon_müzakirəsi");
		addNamespaceAlias(12, "Kömək");
		addNamespaceAlias(13, "Kömək_müzakirəsi");
		addNamespaceAlias(14, "Kateqoriya");
		addNamespaceAlias(15, "Kateqoriya_müzakirəsi");
		addNamespaceAlias(-2, "Mediya");

		addI18nCIAlias("redirect", "#İSTİQAMƏTLƏNDİRMƏ", "#İSTİQAMƏTLƏNDİR", "#REDIRECT");
		addI18nCIAlias("notoc", "__MÜNDƏRİCATYOX__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__QALEREYAYOX__", "__NOGALLERY__");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://az.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "az";
	}
}
