/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class BclConfig extends TemplateConfig {
	public BclConfig() {
		addNamespaceAlias(-2, "Medio");
		addNamespaceAlias(-1, "Espesyal");
		addNamespaceAlias(1, "Olay");
		addNamespaceAlias(2, "Paragamit");
		addNamespaceAlias(3, "Olay_kan_paragamit");
		addNamespaceAlias(5, "Olay_sa_Wikipedia");
		addNamespaceAlias(6, "Ladawan");
		addNamespaceAlias(7, "Olay_sa_ladawan");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Olay_sa_MediaWiki");
		addNamespaceAlias(10, "Plantilya");
		addNamespaceAlias(11, "Olay_sa_plantilya");
		addNamespaceAlias(12, "Tabang");
		addNamespaceAlias(13, "Olay_sa_tabang");
		addNamespaceAlias(14, "Kategorya");
		addNamespaceAlias(15, "Olay_sa_kategorya");

		addI18nAlias("currentmonth", "BULANNGONYAN", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "NGARANBULANNGONYAN", "CURRENTMONTHNAME");
		addI18nAlias("currentday", "ALDAWNGONYAN", "CURRENTDAY");
		addI18nAlias("currentyear", "TAONNGONYAN", "CURRENTYEAR");
		addI18nAlias("currenttime", "PANAHONNGONYAN", "CURRENTTIME");
		addI18nAlias("currenthour", "ORASNGONYAN", "CURRENTHOUR");
		addI18nAlias("localmonth", "LOKALBULAN", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonthname", "NGARANLOKALBULAN", "LOCALMONTHNAME");
		addI18nAlias("localday", "LOKALALDAW", "LOCALDAY");
		addI18nAlias("localday2", "LOKALALDAW2", "LOCALDAY2");
		addI18nAlias("localdayname", "NGARANLOKALALDAW", "LOCALDAYNAME");
		addI18nAlias("localyear", "LOKALTAON", "LOCALYEAR");
		addI18nAlias("localtime", "LOKALPANAHON", "LOCALTIME");
		addI18nAlias("localhour", "LOKALORAS", "LOCALHOUR");
		addI18nAlias("numberofpages", "NUMEROKANPAHINA", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "NUMEROKANARTIKULO", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "NUMEROKANDOKUMENTO", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "NUMEROKANPARAGAMIT", "NUMBEROFUSERS");
		addI18nAlias("numberofedits", "NUMEROKANLIGWAT", "NUMBEROFEDITS");
		addI18nAlias("pagename", "NGARANKANPAHINA", "PAGENAME");
		addI18nAlias("pagenamee", "KAGNGARANKANPAHINA", "PAGENAMEE");
		addI18nAlias("namespace", "NGARANESPASYO", "NAMESPACE");
		addI18nAlias("namespacee", "KAGNGARANESPASYO", "NAMESPACEE");
		addI18nAlias("talkspace", "OLAYESPASYO", "TALKSPACE");
		addI18nAlias("talkspacee", "KAGOLAYESPASYO", "TALKSPACEE");
		addI18nAlias("fullpagename", "TODONGNGARANKANPAHINA", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "KAGNGARANKANTODONGNGARANKANPAHINA", "FULLPAGENAMEE");
		addI18nAlias("talkpagename", "NGARANKANPAHINANINOLAY", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "KAGNGARANKANPAHINANINOLAY", "TALKPAGENAMEE");
		addI18nCIAlias("msg", "MSH", "MSG:");
		addI18nAlias("img_right", "too", "right");
		addI18nAlias("img_left", "wala", "left");
		addI18nAlias("img_none", "mayò", "none");
		addI18nAlias("img_center", "sentro", "tangâ", "center", "centre");
		addI18nAlias("img_framed", "nakakawadro", "kwadro", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "daing kwadro", "frameless");
		addI18nAlias("img_page", "pahina=$1", "pahina $1", "page=$1", "page $1");
		addI18nCIAlias("localurl", "LOKALURL", "LOCALURL:");
		addI18nCIAlias("localurle", "LOKALURLE", "LOCALURLE:");
		addI18nAlias("currentweek", "SEMANANGONYAN", "CURRENTWEEK");
		addI18nAlias("localweek", "LOKALSEMANA", "LOCALWEEK");
		addI18nCIAlias("plural", "DAKOL:", "PLURAL:");
		addI18nCIAlias("fullurl", "TODONGURL:", "FULLURL:");
		addI18nCIAlias("fullurle", "TODONGURLE:", "FULLURLE:");
		addI18nCIAlias("language", "#TATARAMON", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "TATARAMONKANLAOG", "TATARAMONLAOG", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("numberofadmins", "NUMEROKANTAGAMATO", "NUMBEROFADMINS");
		addI18nCIAlias("padleft", "PADWALA", "PADLEFT");
		addI18nCIAlias("padright", "PADTOO", "PADRIGHT");
		addI18nCIAlias("filepath", "FILEDALAN", "FILEPATH:");
		addI18nAlias("hiddencat", "__NAKATAGONGKAT__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "PAHINASAKATEGORYA", "PAHINASAKAT", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "PAHINASOKOL", "PAGESIZE");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://bcl.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "bcl";
	}
}
