/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class BpyConfig extends TemplateConfig {
	public BpyConfig() {
		addNamespaceAlias(-2, "মিডিয়া", "মিডিয়া");
		addNamespaceAlias(-1, "বিশেষ", "বিশেষ");
		addNamespaceAlias(1, "য়্যারী", "আলাপ");
		addNamespaceAlias(2, "আতাকুরা", "ব্যবহারকারী");
		addNamespaceAlias(3, "আতাকুরার_য়্যারী", "ব্যবহারকারী_আলাপ");
		addNamespaceAlias(5, "Wikipedia_য়্যারী", "Wikipedia_আলোচনা", "Wikipedia_আলাপ");
		addNamespaceAlias(6, "ছবি", "চিত্র");
		addNamespaceAlias(7, "ছবি_য়্যারী", "চিত্র_আলোচনা", "চিত্র_আলাপ", "MediaWiki_আলাপ");
		addNamespaceAlias(8, "মিডিয়াউইকি", "মিডিয়াউইকি");
		addNamespaceAlias(9, "মিডিয়াউইকির_য়্যারী", "মিডিয়াউইকি_আলোচনা");
		addNamespaceAlias(10, "মডেল", "টেমপ্লেট");
		addNamespaceAlias(11, "মডেলর_য়্যারী", "টেমপ্লেট_আলোচনা");
		addNamespaceAlias(12, "পাংলাক", "সাহায্য");
		addNamespaceAlias(13, "পাংলাকর_য়্যারী", "সাহায্য_আলোচনা");
		addNamespaceAlias(14, "থাক", "বিষয়শ্রেণী");
		addNamespaceAlias(15, "থাকর_য়্যারী", "বিষয়শ্রেণী_আলোচনা");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://bpy.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "bpy";
	}
}
