/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class CaConfig extends TemplateConfig {
	public CaConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Especial");
		addNamespaceAlias(1, "Discussió");
		addNamespaceAlias(2, "Usuari");
		addNamespaceAlias(3, "Usuari_Discussió");
		addNamespaceAlias(5, "Wikipedia_Discussió");
		addNamespaceAlias(6, "Fitxer", "Imatge");
		addNamespaceAlias(7, "Fitxer_Discussió", "Imatge_Discussió");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_Discussió");
		addNamespaceAlias(10, "Plantilla");
		addNamespaceAlias(11, "Plantilla_Discussió");
		addNamespaceAlias(12, "Ajuda");
		addNamespaceAlias(13, "Ajuda_Discussió");
		addNamespaceAlias(14, "Categoria");
		addNamespaceAlias(15, "Categoria_Discussió");

		addI18nAlias("numberofarticles", "NOMBRED'ARTICLES", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "NOMBRED'ARXIUS", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "NOMBRED'USUARIS", "NUMBEROFUSERS");
		addI18nAlias("numberofedits", "NOMBRED'EDICIONS", "NUMBEROFEDITS");
		addI18nAlias("pagename", "NOMDELAPLANA", "PAGENAME");
		addI18nAlias("img_right", "dreta", "right");
		addI18nAlias("img_left", "esquerra", "left");
		addI18nAlias("img_border", "vora", "border");
		addI18nAlias("img_link", "enllaç=$1", "link=$1");
		addI18nAlias("displaytitle", "TÍTOL", "DISPLAYTITLE");
		addI18nCIAlias("language", "#IDIOMA:", "#LANGUAGE:");
		addI18nCIAlias("special", "especial", "special");
		addI18nAlias("defaultsort", "ORDENA:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nAlias("pagesize", "MIDADELAPLANA", "PAGESIZE");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ca.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ca";
	}
}
