/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class CeConfig extends TemplateConfig {
	public CeConfig() {
		addNamespaceAlias(-2, "Медиа", "Медйа", "Медиа");
		addNamespaceAlias(-1, "Белхан", "Башхо", "Служебная");
		addNamespaceAlias(1, "Дийцаре", "Дийца", "Обсуждение");
		addNamespaceAlias(2, "Декъашхо", "Юзер", "Участник", "Участник", "Участница");
		addNamespaceAlias(3, "Декъашхочун_дийцаре", "Юзери_дийца", "Дийцаре_декъашхо", "Декъашхон_дийцаре", "Обсуждение_участника", "Обсуждение_участника", "Обсуждение_участницы");
		addNamespaceAlias(5, "{{GRAMMAR:genitive|Wikipedia}}_дийцаре", "Wikipedia_Дийца", "Дийцаре_{{GRAMMAR:genitive|Wikipedia}}", "Обсуждение_{{GRAMMAR:genitive|Wikipedia}}");
		addNamespaceAlias(6, "Файл", "Сурт", "Хlум", "Файл", "Изображение");
		addNamespaceAlias(7, "Файлан_дийцаре", "Сурти_дийца", "Хlуман_дийцаре", "Дийцаре_хlуман", "Обсуждение_файла", "Обсуждение_изображения");
		addNamespaceAlias(8, "MediaWiki", "МедйаВики", "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_дийцаре", "МедйаВики_дийца", "MediaWiki_Дийцаре", "Обсуждение_MediaWiki");
		addNamespaceAlias(10, "Кеп", "Дакъан", "Куцкеп", "Шаблон");
		addNamespaceAlias(11, "Кепан_дийцаре", "Дакъан_дийца", "Куцкеп_дийцаре", "Обсуждение_шаблона");
		addNamespaceAlias(12, "ГӀо", "ГІо", "Гlо", "Справка");
		addNamespaceAlias(13, "ГӀо_дийцаре", "ГІодан_дийца", "Гlон_дийцаре", "Обсуждение_справки");
		addNamespaceAlias(14, "Категори", "Тоба", "Кадегар", "Категория");
		addNamespaceAlias(15, "Категорин_дийцаре", "Тобан_дийца", "Кадегар_дийцаре", "Обсуждение_категории");

		addI18nCIAlias("redirect", "#дlасахьажайар'", "'#хьажайо'", "'#REDIRECT", "#перенаправление", "#перенапр", "#REDIRECT", "Array");
		addI18nCIAlias("notoc", "__БАЦ_ЧУЛАЦАМ__", "__БАЦ_ЧУЛ__", "__БЕЗ_ОГЛАВЛЕНИЯ__", "__БЕЗ_ОГЛ__", "__NOTOC__", "Array");
		addI18nCIAlias("nogallery", "__ЙАЦ_УЧЕ__", "__БЕЗ_ГАЛЕРЕИ__", "__NOGALLERY__", "Array");
		addI18nCIAlias("forcetoc", "__ТlЕДУЬЛЛУ_ЧУЛАЦАМБАР__", "__ТlЕДУЬЛ_ЧУЛ__", "__ОБЯЗАТЕЛЬНОЕ_ОГЛАВЛЕНИЕ__", "__ОБЯЗ_ОГЛ__", "__FORCETOC__", "Array");
		addI18nCIAlias("toc", "__ЧУЛАЦАМ__", "__ЧУЛ__", "__ОГЛАВЛЕНИЕ__", "__ОГЛ__", "__TOC__", "Array");
		addI18nCIAlias("noeditsection", "__ЦАМЕГ_РЕДАККХА_АГlОН__", "__БЕЗ_РЕДАКТИРОВАНИЯ_РАЗДЕЛА__", "__NOEDITSECTION__", "Array");
		addI18nAlias("currentmonth", "КАРАРА_БУТТ", "КАРАРА_БУТТ_2", "ТЕКУЩИЙ_МЕСЯЦ", "ТЕКУЩИЙ_МЕСЯЦ_2", "CURRENTMONTH", "CURRENTMONTH2", "Array");
		addI18nAlias("currentmonth1", "КАРАРА_БУТТ_1", "ТЕКУЩИЙ_МЕСЯЦ_1", "CURRENTMONTH1", "Array");
		addI18nAlias("currentmonthname", "КАРАРАЧУ_БЕТТА_ЦlЕ", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА", "CURRENTMONTHNAME", "Array");
		addI18nAlias("currentmonthnamegen", "КАРАРАЧУ_БЕТТА_ЦlЕ_МУХ", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_РОД", "CURRENTMONTHNAMEGEN", "Array");
		addI18nAlias("currentmonthabbrev", "КАРАРАЧУ_БЕТТА_ЦlЕ_АБР", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_АБР", "CURRENTMONTHABBREV", "Array");
		addI18nAlias("currentday", "КАРАРА_ДЕ", "ТЕКУЩИЙ_ДЕНЬ", "CURRENTDAY", "Array");
		addI18nAlias("currentday2", "КАРАРА_ДЕ_2", "ТЕКУЩИЙ_ДЕНЬ_2", "CURRENTDAY2", "Array");
		addI18nAlias("currentdayname", "КАРАРАЧУ_ДЕ_ЦlЕ", "НАЗВАНИЕ_ТЕКУЩЕГО_ДНЯ", "CURRENTDAYNAME", "Array");
		addI18nAlias("currentyear", "КАРАРА_ШО", "ТЕКУЩИЙ_ГОД", "CURRENTYEAR", "Array");
		addI18nAlias("currenttime", "КАРАРА_ХАН", "ТЕКУЩЕЕ_ВРЕМЯ", "CURRENTTIME", "Array");
		addI18nAlias("currenthour", "КАРАРА_САХЬТ", "ТЕКУЩИЙ_ЧАС", "CURRENTHOUR", "Array");
		addI18nAlias("localmonth", "МЕТТИГАН_БУТТ", "МЕСТНЫЙ_МЕСЯЦ_2", "МЕСТНЫЙ_МЕСЯЦ", "LOCALMONTH", "LOCALMONTH2", "Array");
		addI18nAlias("localmonth1", "МЕТТИГАН_БУТТ_1", "МЕСТНЫЙ_МЕСЯЦ_1", "LOCALMONTH1", "Array");
		addI18nAlias("localmonthname", "МЕТТИГАН_БЕТТА_ЦlЕ", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА", "LOCALMONTHNAME", "Array");
		addI18nAlias("localmonthnamegen", "МЕТТИГАН_БЕТТА_ЦlЕ_МУХ", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_РОД", "LOCALMONTHNAMEGEN", "Array");
		addI18nAlias("localmonthabbrev", "МЕТТИГАН_БЕТТА_ЦlЕ_АБР", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_АБР", "LOCALMONTHABBREV", "Array");
		addI18nAlias("localday", "МЕТТИГАН_ДЕ", "МЕСТНЫЙ_ДЕНЬ", "LOCALDAY", "Array");
		addI18nAlias("localday2", "МЕТТИГАН_ДЕ_2", "МЕСТНЫЙ_ДЕНЬ_2", "LOCALDAY2", "Array");
		addI18nAlias("localdayname", "МЕТТИГАН_ДЕ_ЦlЕ", "НАЗВАНИЕ_МЕСТНОГО_ДНЯ", "LOCALDAYNAME", "Array");
		addI18nAlias("localyear", "МЕТТИГАН_ШО", "МЕСТНЫЙ_ГОД", "LOCALYEAR", "Array");
		addI18nAlias("localtime", "МЕТТИГАН_ХАН", "МЕСТНОЕ_ВРЕМЯ", "LOCALTIME", "Array");
		addI18nAlias("localhour", "МЕТТИГАН_САХЬТ", "МЕСТНЫЙ_ЧАС", "LOCALHOUR", "Array");
		addI18nAlias("numberofpages", "АГlОНИЙ_ДУКХАЛЛА", "КОЛИЧЕСТВО_СТРАНИЦ", "NUMBEROFPAGES", "Array");
		addI18nAlias("numberofarticles", "ЯЗЗАМАШИ_ДУКХАЛЛА", "КОЛИЧЕСТВО_СТАТЕЙ", "NUMBEROFARTICLES", "Array");
		addI18nAlias("numberoffiles", "ФАЙЛАНШИ_ДУКХАЛЛА", "КОЛИЧЕСТВО_ФАЙЛОВ", "NUMBEROFFILES", "Array");
		addI18nAlias("numberofusers", "ДЕКЪАШХОЙ_ДУКХАЛЛА", "КОЛИЧЕСТВО_УЧАСТНИКОВ", "NUMBEROFUSERS", "Array");
		addI18nAlias("numberofactiveusers", "ДУКХАЛЛА_ЖИГАРА_ДЕКЪАШХОЙ", "КОЛИЧЕСТВО_АКТИВНЫХ_УЧАСТНИКОВ", "NUMBEROFACTIVEUSERS", "Array");
		addI18nAlias("numberofedits", "НИСДАРШИЙ_ДУКХАЛЛА", "КОЛИЧЕСТВО_ПРАВОК", "NUMBEROFEDITS", "Array");
		addI18nAlias("numberofviews", "ХЬАЖАРИЙ_ДУКХАЛЛА", "КОЛИЧЕСТВО_ПРОСМОТРОВ", "NUMBEROFVIEWS", "Array");
		addI18nAlias("pagename", "АГlОН_ЦlЕ", "НАЗВАНИЕ_СТРАНИЦЫ", "PAGENAME", "Array");
		addI18nAlias("pagenamee", "АГlОН_ЦlЕ_2", "НАЗВАНИЕ_СТРАНИЦЫ_2", "PAGENAMEE", "Array");
		addI18nAlias("namespace", "ЦlЕРИ_АНА", "ПРОСТРАНСТВО_ИМЁН", "NAMESPACE", "Array");
		addI18nAlias("namespacee", "ЦlЕРИ_АНА_2", "ПРОСТРАНСТВО_ИМЁН_2", "NAMESPACEE", "Array");
		addI18nAlias("talkspace", "ДИЙЦАРШИ_АНА", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ", "TALKSPACE", "Array");
		addI18nAlias("talkspacee", "ДИЙЦАРШИ_АНА_2", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ_2", "TALKSPACEE", "Array");
		addI18nAlias("subjectspace", "ЯЗЗАМАШИ_АНА", "ПРОСТРАНСТВО_СТАТЕЙ", "SUBJECTSPACE", "ARTICLESPACE", "Array");
		addI18nAlias("subjectspacee", "ЯЗЗАМАШИ_АНА_2", "ПРОСТРАНСТВО_СТАТЕЙ_2", "SUBJECTSPACEE", "ARTICLESPACEE", "Array");
		addI18nAlias("fullpagename", "ЮЬЗЗИНА_АГlОН_ЦlЕ", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ", "FULLPAGENAME", "Array");
		addI18nAlias("fullpagenamee", "ЮЬЗЗИНА_АГlОН_ЦlЕ_2", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ_2", "FULLPAGENAMEE", "Array");
		addI18nAlias("subpagename", "АГlОН_КlЕЛАРА_ЦlЕ", "НАЗВАНИЕ_ПОДСТРАНИЦЫ", "SUBPAGENAME", "Array");
		addI18nAlias("subpagenamee", "АГlОН_КlЕЛАРА_ЦlЕ_2", "НАЗВАНИЕ_ПОДСТРАНИЦЫ_2", "SUBPAGENAMEE", "Array");
		addI18nAlias("basepagename", "АГlОН_ЦlЕРА_БУХ", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ", "BASEPAGENAME", "Array");
		addI18nAlias("basepagenamee", "АГlОН_ЦlЕРА_БУХ_2", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ_2", "BASEPAGENAMEE", "Array");
		addI18nAlias("talkpagename", "ДИЙЦАРЕ_АГlОН_ЦlЕ", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ", "TALKPAGENAME", "Array");
		addI18nAlias("talkpagenamee", "ДИЙЦАРЕ_АГlОН_ЦlЕ_2", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ_2", "TALKPAGENAMEE", "Array");
		addI18nAlias("subjectpagename", "АГlОН_ЯЗЗАМАН_ЦlЕ", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ", "SUBJECTPAGENAME", "ARTICLEPAGENAME", "Array");
		addI18nAlias("subjectpagenamee", "АГlОН_ЯЗЗАМАН_ЦlЕ_2", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ_2", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE", "Array");
		addI18nCIAlias("msg", "ХААМ:", "СООБЩЕНИЕ:", "СООБЩ:", "MSG:", "Array");
		addI18nCIAlias("subst", "ХlОТТОР:", "ХlОТТ:", "ПОДСТАНОВКА:", "ПОДСТ:", "SUBST:", "Array");
		addI18nCIAlias("msgnw", "ВИКИ_ХААМ_БОЦАШ:", "СООБЩ_БЕЗ_ВИКИ:", "MSGNW:", "Array");
		addI18nAlias("img_thumbnail", "жима", "жимо", "мини", "миниатюра", "thumbnail", "thumb", "Array");
		addI18nAlias("img_manualthumb", "жима=$1", "жимо=$1", "мини=$1", "миниатюра=$1", "thumbnail=$1", "thumb=$1", "Array");
		addI18nAlias("img_right", "бакъхьа", "справа", "right", "Array");
		addI18nAlias("img_left", "харцхьа", "слева", "left", "Array");
		addI18nAlias("img_none", "йоцуш", "без", "none", "Array");
		addI18nAlias("img_width", "$1пкс", "$1px", "Array");
		addI18nAlias("img_center", "юккъ", "центр", "center", "centre", "Array");
		addI18nAlias("img_framed", "гурабе", "обрамить", "framed", "enframed", "frame", "Array");
		addI18nAlias("img_frameless", "гурабоцаш", "безрамки", "frameless", "Array");
		addI18nAlias("img_page", "агlо=$1", "агlо_$1", "page_$1", "страница=$1", "страница_$1", "страница $1", "page=$1", "page $1", "Array");
		addI18nAlias("img_upright", "бакъхьалакхо", "бакъхьалакхо=$1", "бакъхьалакхо_$1", "upright_$1", "сверхусправа", "сверхусправа=$1", "сверхусправа_$1", "сверхусправа $1", "upright", "upright=$1", "upright $1", "Array");
		addI18nAlias("img_border", "доза", "граница", "border", "Array");
		addI18nAlias("img_baseline", "бух", "основание", "baseline", "Array");
		addI18nAlias("img_sub", "буха", "под", "sub", "Array");
		addI18nAlias("img_super", "тlе", "над", "super", "sup", "Array");
		addI18nAlias("img_top", "лакхахь", "сверху", "top", "Array");
		addI18nAlias("img_text_top", "лакххьара-йоза", "текст-сверху", "text-top", "Array");
		addI18nAlias("img_middle", "юккъе", "посередине", "middle", "Array");
		addI18nAlias("img_bottom", "бухар", "снизу", "bottom", "Array");
		addI18nAlias("img_text_bottom", "бухара-йоза", "текст-снизу", "text-bottom", "Array");
		addI18nAlias("img_link", "хьажориг=$1", "ссылка=$1", "link=$1", "Array");
		addI18nAlias("img_alt", "альт=$1", "alt=$1", "Array");
		addI18nCIAlias("int", "ЧУЬРА:", "ВНУТР:", "INT:", "Array");
		addI18nAlias("sitename", "МЕТТИГ_ЦlЕ", "НАЗВАНИЕ_САЙТА", "SITENAME", "Array");
		addI18nCIAlias("ns", "БО:", "ПИ:", "NS:", "Array");
		addI18nCIAlias("nse", "БОХЬ:", "ПИК:", "NSE:", "Array");
		addI18nCIAlias("localurl", "ХlОТТАЕЛЛА_МЕТТИГ:", "ЛОКАЛЬНЫЙ_АДРЕС:", "LOCALURL:", "Array");
		addI18nCIAlias("localurle", "ХlОТТАЕЛЛА_МЕТТИГ_2:", "ЛОКАЛЬНЫЙ_АДРЕС_2:", "LOCALURLE:", "Array");
		addI18nCIAlias("server", "ГlУЛКХДИРИГ", "СЕРВЕР", "SERVER", "Array");
		addI18nCIAlias("servername", "ГlУЛКХДЕЧУЬНА_ЦlЕ", "НАЗВАНИЕ_СЕРВЕРА", "SERVERNAME", "Array");
		addI18nCIAlias("scriptpath", "НЕКЪ_ОЦ_МЕТТАКЕПА", "ПУТЬ_К_СКРИПТУ", "SCRIPTPATH", "Array");
		addI18nCIAlias("stylepath", "ЙОМАНХАТl", "ПУТЬ_К_СТИЛЮ", "STYLEPATH", "Array");
		addI18nCIAlias("grammar", "ДОЖАР:", "ПАДЕЖ:", "GRAMMAR:", "Array");
		addI18nCIAlias("gender", "ВУ_ЙУ:", "GENDER", "ПОЛ:", "GENDER:", "Array");
		addI18nCIAlias("notitleconvert", "__ХИЙЦАР_ДОЦУШ_КОЬРТЕ__", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ЗАГОЛОВКА__", "__NOTITLECONVERT__", "__NOTC__", "Array");
		addI18nCIAlias("nocontentconvert", "__ЙОЗА_ХИЙЦАР_ДОЦУШ__", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ТЕКСТА__", "__NOCONTENTCONVERT__", "__NOCC__", "Array");
		addI18nAlias("currentweek", "КАРАРА_КlИР", "ТЕКУЩАЯ_НЕДЕЛЯ", "CURRENTWEEK", "Array");
		addI18nAlias("currentdow", "КАРАРА_КlИРАН_ДЕ", "ТЕКУЩИЙ_ДЕНЬ_НЕДЕЛИ", "CURRENTDOW", "Array");
		addI18nAlias("localweek", "МЕТТИГЕРА_КlИРА", "МЕСТНАЯ_НЕДЕЛЯ", "LOCALWEEK", "Array");
		addI18nAlias("localdow", "МЕТТИГАН_КlИРАН_ДЕ", "МЕСТНЫЙ_ДЕНЬ_НЕДЕЛИ", "LOCALDOW", "Array");
		addI18nAlias("revisionid", "ЦУЬНА_БАШХО", "ИД_ВЕРСИИ", "REVISIONID", "Array");
		addI18nAlias("revisionday", "ДЕ_БАШХО", "ДЕНЬ_ВЕРСИИ", "REVISIONDAY", "Array");
		addI18nAlias("revisionday2", "ДЕ_БАШХО_2", "ДЕНЬ_ВЕРСИИ_2", "REVISIONDAY2", "Array");
		addI18nAlias("revisionmonth", "БЕТТА_БАШХО", "МЕСЯЦ_ВЕРСИИ", "REVISIONMONTH", "Array");
		addI18nAlias("revisionyear", "ШО_БАШХО", "ГОД_ВЕРСИИ", "REVISIONYEAR", "Array");
		addI18nAlias("revisiontimestamp", "КЪАСТАМ_ХЕНА_БАШХО", "ОТМЕТКА_ВРЕМЕНИ_ВЕРСИИ", "REVISIONTIMESTAMP", "Array");
		addI18nAlias("revisionuser", "ДЕКЪАШХОН_БАШХО", "ВЕРСИЯ_УЧАСНИКА", "ВЕРСИЯ_УЧАСТНИКА", "REVISIONUSER", "Array");
		addI18nCIAlias("plural", "ДУКХАЛЛИН_ТЕРАХЬ:", "МНОЖЕСТВЕННОЕ_ЧИСЛО:", "PLURAL:", "Array");
		addI18nCIAlias("fullurl", "МАЙАРРА_МЕТТИГ:", "ПОЛНЫЙ_АДРЕС:", "FULLURL:", "Array");
		addI18nCIAlias("fullurle", "МАЙАРРА_МЕТТИГ_2:", "ПОЛНЫЙ_АДРЕС_2:", "FULLURLE:", "Array");
		addI18nCIAlias("lcfirst", "ХЬАЛХАР_ЭЛП_ЖИМА:", "ПЕРВАЯ_БУКВА_МАЛЕНЬКАЯ:", "LCFIRST:", "Array");
		addI18nCIAlias("ucfirst", "ХЬАЛХАР_ЭЛП_ДОККХА:", "ПЕРВАЯ_БУКВА_БОЛЬШАЯ:", "UCFIRST:", "Array");
		addI18nCIAlias("lc", "КЕГИЙЧУ_ЭЛПАШЦА:", "МАЛЕНЬКИМИ_БУКВАМИ:", "LC:", "Array");
		addI18nCIAlias("uc", "ДАККХИЙЧУ_ЭЛПАШЦА:", "БОЛЬШИМИ_БУКВАМИ:", "UC:", "Array");
		addI18nCIAlias("raw", "ТАЙАНЗА:", "НЕОБРАБ:", "RAW:", "Array");
		addI18nAlias("displaytitle", "ГАЙТА_КОЬРТАМОГl", "ПОКАЗАТЬ_ЗАГОЛОВОК", "DISPLAYTITLE", "Array");
		addI18nAlias("rawsuffix", "Т", "Н", "R", "Array");
		addI18nAlias("newsectionlink", "__ХЬАЖОРАГ_ОЦ_КЕРЛАЧУ_ДЕКЪАН__", "__ССЫЛКА_НА_НОВЫЙ_РАЗДЕЛ__", "__NEWSECTIONLINK__", "Array");
		addI18nAlias("nonewsectionlink", "__ЙОЦАШ_ХЬАЖОРАГ_ОЦ_КЕРЛАЧУ_ДЕКЪАН__", "__БЕЗ_ССЫЛКИ_НА_НОВЫЙ_РАЗДЕЛ__", "__NONEWSECTIONLINK__", "Array");
		addI18nAlias("currentversion", "ЙОЛШЙОЛУ_БАШХО", "ТЕКУЩАЯ_ВЕРСИЯ", "CURRENTVERSION", "Array");
		addI18nCIAlias("urlencode", "ИШАРЙИНА_МЕТТИГ:", "ЗАКОДИРОВАННЫЙ_АДРЕС:", "URLENCODE:", "Array");
		addI18nCIAlias("anchorencode", "ИШАРЙАР_МЕТТИГАН", "КОДИРОВАТЬ_МЕТКУ", "ANCHORENCODE", "Array");
		addI18nAlias("currenttimestamp", "КЪАСТАМ_ЙОЛУЧУ_ХАННА", "ОТМЕТКА_ТЕКУЩЕГО_ВРЕМЕНИ", "CURRENTTIMESTAMP", "Array");
		addI18nAlias("localtimestamp", "КЪАСТАМ_МЕТТИГА_ХАННА", "ОТМЕТКА_МЕСТНОГО_ВРЕМЕНИ", "LOCALTIMESTAMP", "Array");
		addI18nAlias("directionmark", "ХЬАЖОЧЕ_ХААМ", "НАПРАВЛЕНИЕ_ПИСЬМА", "DIRECTIONMARK", "DIRMARK", "Array");
		addI18nCIAlias("language", "#МОТТ", "#ЯЗЫК:", "#LANGUAGE:", "Array");
		addI18nAlias("contentlanguage", "МОТТ_ЧУЛАЦАМ", "ЯЗЫК_СОДЕРЖАНИЯ", "CONTENTLANGUAGE", "CONTENTLANG", "Array");
		addI18nAlias("pagesinnamespace", "АГlОНАШ_ОЦ_ЦlЕРАШКАХЬ:", "СТРАНИЦ_В_ПРОСТРАНСТВЕ_ИМЁН:", "PAGESINNAMESPACE:", "PAGESINNS:", "Array");
		addI18nAlias("numberofadmins", "КУЬГАЛХОЙ_ДУКХАЛЛА", "КОЛИЧЕСТВО_АДМИНИСТРАТОРОВ", "NUMBEROFADMINS", "Array");
		addI18nCIAlias("formatnum", "ТЕРАХЬАН_БАРАМХlОТТОР", "ФОРМАТИРОВАТЬ_ЧИСЛО", "FORMATNUM", "Array");
		addI18nCIAlias("padleft", "ЙУЗА_ХАРЦЕ", "ЗАПОЛНИТЬ_СЛЕВА", "PADLEFT", "Array");
		addI18nCIAlias("padright", "ЙУЗА_БАКЪЕ", "ЗАПОЛНИТЬ_СПРАВА", "PADRIGHT", "Array");
		addI18nCIAlias("special", "белхан", "гlуллакхан", "служебная", "special", "Array");
		addI18nAlias("defaultsort", "ЛИСТАР_ЦАХЬЕХОР", "ДОГlА_ЛИСТАРАН", "СОРТИРОВКА_ПО_УМОЛЧАНИЮ", "КЛЮЧ_СОРТИРОВКИ", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:", "Array");
		addI18nCIAlias("filepath", "ОЦ_ХlУМАНТlЕ_НЕКЪ:", "ПУТЬ_К_ФАЙЛУ:", "FILEPATH:", "Array");
		addI18nCIAlias("tag", "къастам", "къасто", "къаст", "метка", "тег", "тэг", "tag", "Array");
		addI18nAlias("hiddencat", "__КЪАЙЛАХЙОЛУ_КАДЕГАР__", "__СКРЫТАЯ_КАТЕГОРИЯ__", "__HIDDENCAT__", "Array");
		addI18nAlias("pagesincategory", "АГlОНАШ_ОЦУ_КАДЕГАРШЧОХЬ", "СТРАНИЦ_В_КАТЕГОРИИ", "PAGESINCATEGORY", "PAGESINCAT", "Array");
		addI18nAlias("pagesize", "АГlОН_БАРАМ", "РАЗМЕР_СТРАНИЦЫ", "PAGESIZE", "Array");
		addI18nAlias("index", "__МЕТТИГТЕРАХЬ__", "__ИНДЕКС__", "__INDEX__", "Array");
		addI18nAlias("noindex", "__МЕТТИГТЕРАХЬ_ЙОЦАШ__", "__БЕЗ_ИНДЕКСА__", "__NOINDEX__", "Array");
		addI18nAlias("numberingroup", "ТЕРАХЬ_ОЦ_ТОБАНЦА", "ЧИСЛО_В_ГРУППЕ", "NUMBERINGROUP", "NUMINGROUP", "Array");
		addI18nAlias("staticredirect", "__БУХЕХЬДЕРГ_ДlАСХЬАЖАЙАР__", "__СТАТИЧЕСКОЕ_ПЕРЕНАПРАВЛЕНИЕ__", "__STATICREDIRECT__", "Array");
		addI18nAlias("protectionlevel", "ГlАРОЛЛИ_БАРАМ", "УРОВЕНЬ_ЗАЩИТЫ", "PROTECTIONLEVEL", "Array");
		addI18nCIAlias("formatdate", "терахьибарам", "форматдаты", "formatdate", "dateformat", "Array");
		addI18nCIAlias("url_path", "ЙОМА", "ПУТЬ", "PATH", "Array");
		addI18nCIAlias("url_wiki", "ЧЕХКА", "ВИКИ", "WIKI", "Array");
		addI18nAlias("namespacenumber", "НОМЕР_ПРОСТРАНСТВА_ИМЁН", "NAMESPACENUMBER");
		addI18nCIAlias("safesubst", "ЗАЩПОДСТ:", "SAFESUBST:");
		addI18nCIAlias("articlepath", "ПУТЬ_К_СТАТЬЕ", "ARTICLEPATH");
		addI18nCIAlias("pageid", "ИДЕНТИФИКАТОР_СТРАНИЦЫ", "PAGEID");
		addI18nAlias("revisionmonth1", "МЕСЯЦ_ВЕРСИИ_1", "REVISIONMONTH1");
		addI18nCIAlias("url_query", "ЗАПРОС", "QUERY");
		addI18nCIAlias("pagesincategory_all", "все", "all");
		addI18nCIAlias("pagesincategory_pages", "страницы", "pages");
		addI18nCIAlias("pagesincategory_subcats", "подкатегории", "subcats");
		addI18nCIAlias("pagesincategory_files", "файлы", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ce.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ce";
	}
}
