/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class CkbConfig extends TemplateConfig {
	public CkbConfig() {
		addNamespaceAlias(-2, "میدیا");
		addNamespaceAlias(-1, "تایبەت");
		addNamespaceAlias(0, "");
		addNamespaceAlias(1, "وتووێژ", "لێدوان");
		addNamespaceAlias(2, "بەکارھێنەر");
		addNamespaceAlias(3, "لێدوانی_بەکارھێنەر", "قسەی_بەکارھێنەر");
		addNamespaceAlias(5, "لێدوانی_Wikipedia");
		addNamespaceAlias(6, "پەڕگە");
		addNamespaceAlias(7, "وتووێژی_پەڕگە", "لێدوانی_پەڕگە");
		addNamespaceAlias(8, "میدیاویکی");
		addNamespaceAlias(9, "وتووێژی_میدیاویکی", "لێدوانی_میدیاویکی");
		addNamespaceAlias(10, "داڕێژە", "قاڵب");
		addNamespaceAlias(11, "وتووێژی_داڕێژە", "لێدوانی_قاڵب", "لێدوانی_داڕێژە");
		addNamespaceAlias(12, "یارمەتی");
		addNamespaceAlias(13, "وتووێژی_یارمەتی", "لێدوانی_یارمەتی");
		addNamespaceAlias(14, "پۆل");
		addNamespaceAlias(15, "وتووێژی_پۆل", "لێدوانی_پۆل");

		addI18nAlias("img_thumbnail", "وێنۆک", "thumbnail", "thumb");
		addI18nAlias("img_right", "ڕاست", "right");
		addI18nAlias("img_left", "چەپ", "left");
		addI18nAlias("img_width", "$1پیکسڵ", "$1px");
		addI18nAlias("img_center", "ناوەڕاست", "center", "centre");
		addI18nAlias("img_framed", "چوارچێوە", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "بێچوارچێوە", "frameless");
		addI18nAlias("img_border", "سنوور", "border");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ckb.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ckb";
	}
}
