/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class DiqConfig extends TemplateConfig {
	public DiqConfig() {
		addNamespaceAlias(-2, "Medya");
		addNamespaceAlias(-1, "Bağse", "Xısusi");
		addNamespaceAlias(1, "Vaten", "Werênayış", "Mesac");
		addNamespaceAlias(2, "Karber");
		addNamespaceAlias(3, "Karber_vaten", "Karber_werênayış", "Karber_mesac");
		addNamespaceAlias(5, "Wikipedia_vaten", "Wikipedia_werênayış", "Wikipedia_mesac");
		addNamespaceAlias(6, "Dosya");
		addNamespaceAlias(7, "Dosya_vaten", "Dosya_werênayış", "Dosya_mesac");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_vaten", "MediaWiki_werênayış", "MediaWiki_mesac");
		addNamespaceAlias(10, "Şablon");
		addNamespaceAlias(11, "Şablon_vaten", "Şablon_werênayış", "Şablon_mesac");
		addNamespaceAlias(12, "Desteg", "Desteg", "Peşti");
		addNamespaceAlias(13, "Desteg_vaten", "Desteg_werênayış", "Peşti_mesac", "Peşti_werênayış");
		addNamespaceAlias(14, "Kategori", "Kategori", "Kategoriye");
		addNamespaceAlias(15, "Kategori_vaten", "Kategori_werênayış", "Kategoriye_mesac", "Kategoriye_werênayış");

		addI18nCIAlias("redirect", "#HETENAYIŞ", "#REDIRECT");
		addI18nCIAlias("notoc", "__ESTENÇINO__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__GALERİÇINO__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__ESTENZARURET__", "__FORCETOC__");
		addI18nCIAlias("toc", "__ESTEN__", "__TOC__");
		addI18nCIAlias("noeditsection", "__TİMARKERDIŞÇINO__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "AŞMİYANEWKİ", "MEWCUDAŞMİ2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "AŞMİYANEWKİ1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "NAMEYAŞMDANEWKİ", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "AŞMACIYANEWKİ", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "AŞMİYANEWKİKILMKERDIŞ", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "ROCENEWKİ", "CURRENTDAY");
		addI18nAlias("currentday2", "ROCENEWKİ2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "NAMEYÊROCENEWKİ", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "SERRENEWKİ", "CURRENTYEAR");
		addI18nAlias("currenttime", "DEMENEWKİ", "CURRENTTIME");
		addI18nAlias("currenthour", "SEHATNEWKİ", "CURRENTHOUR");
		addI18nAlias("localmonth", "WAREYAŞMİ", "WAREYAŞMİ2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "WAREYAŞMİ1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "NAMEYÊWAREYAŞMİ", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "NAMEYWAREDÊAŞMİDACI", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "WAREYAŞMİKILMKERDIŞ", "LOCALMONTHABBREV");
		addI18nAlias("localday", "WAREYROCE", "LOCALDAY");
		addI18nAlias("localday2", "WAREYROCE2", "LOCALDAY2");
		addI18nAlias("localdayname", "NAMEYÊWAREYROCE", "LOCALDAYNAME");
		addI18nAlias("localyear", "WAREYSERRE", "LOCALYEAR");
		addI18nAlias("localtime", "WAREYDEME", "LOCALTIME");
		addI18nAlias("localhour", "WAREYSEHAT", "LOCALHOUR");
		addI18nAlias("numberofpages", "AMARİYAPELAN", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "AMARİYAWESİQAN", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "AMARİYADOSYAYAN", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "AMARİYAKARBERAN", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "AMARİYAAKTİVKARBERAN", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "AMARİYAVURNAYIŞAN", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "AMARİYAMOCNAYIŞAN", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "NAMEYPELA", "PAGENAME");
		addI18nAlias("pagenamee", "NAMEYPELAA", "PAGENAMEE");
		addI18nAlias("namespace", "CANAME", "NAMESPACE");
		addI18nAlias("namespacee", "CANAMEE", "NAMESPACEE");
		addI18nAlias("namespacenumber", "AMARİYACANAME", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "CAYÊWERÊNAYIŞİ", "TALKSPACE");
		addI18nAlias("talkspacee", "CAYÊWERÊNAYIŞAN", "TALKSPACEE");
		addI18nAlias("subjectspace", "CAYÊMESEL", "CAYÊWESİQE", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "CAYÊMESELAN", "CAYÊWESİQAN", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "NAMEYPELAPÊRO", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "NAMEYPELAPÊRON", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "NAMEYBINPELA", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "NAMEYBINPELAA", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "NAMEYSERPELA", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "NAMEYSERPELAA", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "NAMEYPELAWERÊNAYIŞ", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "NAMEYPELAWERÊNAYIŞAN", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "NAMEYPELAMESEL", "NAMEYPELAWESİQE", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "NAMEYPELAMESELER", "NAMEYPELAQESİQER", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "MSC", "MSG:");
		addI18nCIAlias("subst", "KOPYAKE", "ATEBERDE", "SUBST:");
		addI18nCIAlias("safesubst", "EMELEYATEBERDE", "SAFESUBST:");
		addI18nCIAlias("msgnw", "MSJNW:", "MSGNW:");
		addI18nAlias("img_thumbnail", "resmoqıckek", "qıckek", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "resmoqıckek=$1", "qıckek=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "raşt", "right");
		addI18nAlias("img_left", "çep", "left");
		addI18nAlias("img_none", "çıniyo", "none");
		addI18nAlias("img_width", "$1pik", "$1piksel", "$1px");
		addI18nAlias("img_center", "werte", "miyan", "center", "centre");
		addI18nAlias("img_framed", "çerçeweya", "çerçeweniyo", "çerçewe", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "bêçerçewe", "frameless");
		addI18nAlias("img_page", "pela=$1", "pela_$1", "page=$1", "page $1");
		addI18nAlias("img_upright", "disleg", "disleg=$1", "disleg_$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "sinor", "border");
		addI18nAlias("img_baseline", "Sinorêerdi", "baseline");
		addI18nAlias("img_sub", "bın", "sub");
		addI18nAlias("img_super", "corên", "cor", "super", "sup");
		addI18nAlias("img_top", "gedug", "top");
		addI18nAlias("img_text_top", "gedug-metin", "text-top");
		addI18nAlias("img_middle", "merkez", "middle");
		addI18nAlias("img_bottom", "erd", "bottom");
		addI18nAlias("img_text_bottom", "erd-metin", "text-bottom");
		addI18nAlias("img_link", "gre=$1", "link=$1");
		addI18nCIAlias("int", "İNT:", "INT:");
		addI18nAlias("sitename", "NAMEYSİTA", "SITENAME");
		addI18nCIAlias("ns", "CN", "NS:");
		addI18nCIAlias("nse", "CNV", "NSE:");
		addI18nCIAlias("localurl", "LOKALGRE", "LOCALURL:");
		addI18nCIAlias("localurle", "LOKALGREV", "LOCALURLE:");
		addI18nCIAlias("articlepath", "SOPAWESİQAN", "ARTICLEPATH");
		addI18nCIAlias("pageid", "NIMREYPELA", "PAGEID");
		addI18nCIAlias("server", "ARDEN", "SERVER");
		addI18nCIAlias("servername", "NAMEYARDEN", "SERVERNAME");
		addI18nCIAlias("scriptpath", "RAYASCRIPTİ", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "TERZÊTEWRİ", "STYLEPATH");
		addI18nCIAlias("grammar", "GRAMER:", "GRAMMAR:");
		addI18nCIAlias("gender", "CİNSİYET:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__SERNAMEVURNAYIŞÇINO__", "__SVÇ__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__ZERREVURNAYIŞÇINO__", "__ZVÇ__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "MEVCUDHEFTE", "CURRENTWEEK");
		addI18nAlias("currentdow", "MEVCUDWAREYHEFTİ", "CURRENTDOW");
		addI18nAlias("localweek", "WAREYHEFTİ", "LOCALWEEK");
		addI18nAlias("localdow", "WAREYROCAHEFTİ", "LOCALDOW");
		addI18nAlias("revisionid", "NIMREYREVİZYONİ", "REVISIONID");
		addI18nAlias("revisionday", "ROCAREVİZYONİ", "REVISIONDAY");
		addI18nAlias("revisionday2", "ROCAREVİZYON1", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "AŞMAREVİZYONİ", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "AŞMAREVİZYONİ1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "SERRAREVİZYONİ", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "MELUMATÊREVİZYONÊDEMİ", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "REVİZYONKARBER", "REVISIONUSER");
		addI18nCIAlias("plural", "ZAFEN:", "PLURAL:");
		addI18nCIAlias("fullurl", "GREPÊRO:", "FULLURL:");
		addI18nCIAlias("fullurle", "GREYOPÊRON:", "FULLURLE:");
		addI18nCIAlias("canonicalurl", "GREYÊKANONİK:", "CANONICALURL:");
		addI18nCIAlias("canonicalurle", "GREYOKANONİK:", "CANONICALURLE:");
		addI18nCIAlias("lcfirst", "KHİLK:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "BHİLK:", "UCFIRST:");
		addI18nCIAlias("lc", "KH:", "LC:");
		addI18nCIAlias("uc", "BH:", "UC:");
		addI18nCIAlias("raw", "XAM:", "RAW:");
		addI18nAlias("displaytitle", "SERNAMİBIMOCNE", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "__GREYÊSERNAMEDÊNEWİ__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__GREYÊSERNAMEDÊNEWİÇINO__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "VERSİYONÊNEWKİ", "CURRENTVERSION");
		addI18nAlias("currenttimestamp", "WAREYSEHATÊNEWKİ", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "MALUMATÊWAREYSEHAT", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "HETANIŞANKERDIŞ", "HETNIŞAN", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#ZIWAN", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "ZIWANÊESTİN", "ZIWESTEN", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "PELEYÊKECADÊNAMİDEYÊ", "PELECN", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "AMARİYAXİZMETKARAN", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "BABETNAYIŞ", "FORMATNUM");
		addI18nCIAlias("padleft", "ÇEPİPIRKE", "PADLEFT");
		addI18nCIAlias("padright", "RAŞTİPIRKE", "PADRIGHT");
		addI18nCIAlias("special", "xısusi", "special");
		addI18nCIAlias("speciale", "xısusiye", "speciale");
		addI18nAlias("defaultsort", "RATNAYIŞOHESBNAYIŞ", "SIRMEYRATNAYIŞOHESBNAYIŞ", "KATEGORİYARATNAYIŞOHESBNAYIŞ", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "RAYADOSYA:", "FILEPATH:");
		addI18nCIAlias("tag", "etiket", "tag");
		addI18nAlias("hiddencat", "__KATEGORİYANIMITİ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "PELEYÊKEKATEGORİDEYÊ", "KATDÊPELEY", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "EBATÊPELA", "PAGESIZE");
		addI18nAlias("index", "__SERSIQ__", "__INDEX__");
		addI18nAlias("noindex", "__SERSIQÇINYO__", "__NOINDEX__");
		addI18nAlias("numberingroup", "GRUBDEAMARE", "AMARİYAGRUBER", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__STATİKHETENAYIŞ__", "__STATICHETENAYIŞ__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "SEWİYEYÊSTARE", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "demêformati", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "RAY", "PATH");
		addI18nCIAlias("url_wiki", "WİKİ", "WIKI");
		addI18nCIAlias("url_query", "PERSİYE", "QUERY");
		addI18nCIAlias("defaultsort_noerror", "xırabinçıniya", "noerror");
		addI18nCIAlias("defaultsort_noreplace", "cewabçıniyo", "noreplace");
		addI18nCIAlias("pagesincategory_all", "pêro", "all");
		addI18nCIAlias("pagesincategory_pages", "peley", "pages");
		addI18nCIAlias("pagesincategory_subcats", "bınkati", "subcats");
		addI18nCIAlias("pagesincategory_files", "dosyey", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://diq.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "diq";
	}
}
