/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class DtpConfig extends TemplateConfig {
	public DtpConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Khas", "Istimewa");
		addNamespaceAlias(1, "Perbincangan", "Perbualan");
		addNamespaceAlias(2, "Pengguna");
		addNamespaceAlias(3, "Perbincangan_pengguna", "Perbualan_Pengguna");
		addNamespaceAlias(5, "Perbincangan_Wikipedia", "Perbualan_Wikipedia");
		addNamespaceAlias(6, "Fail", "Imej");
		addNamespaceAlias(7, "Perbincangan_fail", "Perbincangan_Imej", "Imej_Perbualan");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Perbincangan_MediaWiki", "MediaWiki_Perbualan");
		addNamespaceAlias(10, "Templat");
		addNamespaceAlias(11, "Perbincangan_templat", "Perbualan_Templat");
		addNamespaceAlias(12, "Bantuan");
		addNamespaceAlias(13, "Perbincangan_bantuan", "Perbualan_Bantuan");
		addNamespaceAlias(14, "Kategori");
		addNamespaceAlias(15, "Perbincangan_kategori", "Perbualan_Kategori");

		addI18nCIAlias("redirect", "#LENCONG", "#REDIRECT");
		addI18nAlias("currentmonth", "BULANSEMASA", "BULANSEMASA2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "BULANSEMASA1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "NAMABULANSEMASA", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "NAMABULANSEMASAGEN", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "SINGBULANSEMASA", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "HARISEMASA", "CURRENTDAY");
		addI18nAlias("currentday2", "HARISEMASA2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "NAMAHARISEMASA", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "TAHUNSEMASA", "CURRENTYEAR");
		addI18nAlias("currenttime", "WAKTUSEMASA", "CURRENTTIME");
		addI18nAlias("currenthour", "JAMSEMASA", "CURRENTHOUR");
		addI18nAlias("pagename", "NAMALAMAN", "PAGENAME");
		addI18nAlias("pagenamee", "NAMALAMANE", "PAGENAMEE");
		addI18nAlias("namespace", "RUANGNAMA", "NAMESPACE");
		addI18nAlias("namespacee", "RUANGNAMAE", "NAMESPACEE");
		addI18nAlias("namespacenumber", "NOMBORRUANGNAMA", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "RUANGBINCANG", "TALKSPACE");
		addI18nAlias("talkspacee", "RUANGBINCANGE", "TALKSPACEE");
		addI18nAlias("fullpagename", "NAMALAMANPENUH", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "NAMALAMANPENUHE", "FULLPAGENAMEE");
		addI18nCIAlias("msg", "PESAN:", "MSG:");
		addI18nCIAlias("subst", "TUKAR:", "SUBST:");
		addI18nAlias("img_right", "kiri", "right");
		addI18nAlias("img_left", "kanan", "left");
		addI18nAlias("img_none", "tiada", "none");
		addI18nAlias("img_center", "tengah", "center", "centre");
		addI18nAlias("img_border", "bingkai", "border");
		addI18nAlias("sitename", "NAMATAPAK", "SITENAME");
		addI18nCIAlias("ns", "RN:", "NS:");
		addI18nCIAlias("nse", "RNE:", "NSE:");
		addI18nCIAlias("gender", "JANTINA:", "GENDER:");
		addI18nAlias("currentweek", "MINGGUSEMASA", "CURRENTWEEK");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://dtp.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "dtp";
	}
}
