/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class EoConfig extends TemplateConfig {
	public EoConfig() {
		addNamespaceAlias(-2, "Aŭdvidaĵo");
		addNamespaceAlias(-1, "Specialaĵo", "Speciala");
		addNamespaceAlias(1, "Diskuto");
		addNamespaceAlias(2, "Uzanto", "Vikipediisto", "Uzulo", "Uzanto", "Uzanto", "Uzantino");
		addNamespaceAlias(3, "Uzanto-Diskuto", "Vikipediista_diskuto", "Uzula_diskuto", "Uzanta_diskuto", "Uzanto-Diskuto", "Uzantino-Diskuto");
		addNamespaceAlias(5, "Wikipedia-Diskuto", "Wikipedia_diskuto");
		addNamespaceAlias(6, "Dosiero");
		addNamespaceAlias(7, "Dosiero-Diskuto", "Dosiera_diskuto");
		addNamespaceAlias(8, "MediaWiki", "MediaVikio");
		addNamespaceAlias(9, "MediaWiki-Diskuto", "MediaWiki_diskuto", "MediaVikia_diskuto");
		addNamespaceAlias(10, "Ŝablono");
		addNamespaceAlias(11, "Ŝablono-Diskuto", "Ŝablona_diskuto");
		addNamespaceAlias(12, "Helpo");
		addNamespaceAlias(13, "Helpo-Diskuto", "Helpa_diskuto");
		addNamespaceAlias(14, "Kategorio");
		addNamespaceAlias(15, "Kategorio-Diskuto", "Kategoria_diskuto");

		addI18nCIAlias("redirect", "#ALIDIREKTI", "#ALIDIREKTU", "#AL", "#REDIRECT");
		addI18nCIAlias("notoc", "__NI__", "__NEINDEKSO__", "__NT__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__NG__", "__SENBILDARO__", "__SB__", "__SG__", "__SENGALERIO__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__FI__", "__FORTUINDEKSON__", "__FT__", "__FORCETOC__");
		addI18nCIAlias("toc", "__I__", "__T__", "__INDEKSO__", "__TOC__");
		addI18nCIAlias("noeditsection", "__SRS__", "__NES__", "__SENREDAKTISEKCIOJN__", "__SENREDAKTISEKCION__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "NUNAMONATO", "NUNAMONATO2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "NUNAMONATO1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "NUNAMONATNOMO", "NUNAMONATONOMO", "NUNAMONATANOMO", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "NUNAMONATNOMOGEN", "NUNAMONATONOMOGEN", "NUNAMONATANOMOGEN", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "NUNAMONATNOMOMAL", "NUNAMONATONOMOMAL", "NUNAMONATANOMOMAL", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "NUNATAGO", "CURRENTDAY");
		addI18nAlias("currentday2", "NUNATAGO2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "NUNATAGNOMO", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "NUNAJARO", "CURRENTYEAR");
		addI18nAlias("currenttime", "NUNATEMPO", "CURRENTTIME");
		addI18nAlias("currenthour", "NUNAHORO", "CURRENTHOUR");
		addI18nAlias("localmonth", "LOKAMONATO", "LOKAMONATO2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "LOKAMONATO1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "LOKAMONATNOMO", "LOKAMONATONOMO", "LOKAMONATANOMO", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "LOKAMONATNOMOGEN", "LOKAMONATONOMOGEN", "LOKAMONATANOMOGEN", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "LOKAMONATNOMOMAL", "LOKAMONATONOMOMAL", "LOKAMONATANOMOMAL", "LOCALMONTHABBREV");
		addI18nAlias("localday", "LOKATAGO", "LOCALDAY");
		addI18nAlias("localday2", "LOKATAGO2", "LOCALDAY2");
		addI18nAlias("localdayname", "LOKATAGNOMO", "LOKATAGONOMO", "LOKATAGANOMO", "LOCALDAYNAME");
		addI18nAlias("localyear", "LOKAJARO", "LOCALYEAR");
		addI18nAlias("localtime", "LOKATEMPO", "LOCALTIME");
		addI18nAlias("localhour", "LOKAHORO", "LOCALHOUR");
		addI18nAlias("numberofpages", "NOMBRODEPAĜOJ", "NOMBRODEPAGXOJ", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "NOMBRODEARTIKOLOJ", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "NOMBRODEDOSIEROJ", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "NOMBRODEUZANTOJ", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "NOMBRODEAKTIVAJUZANTOJ", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "NOMBRODEREDAKTOJ", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "NOMBRODEVIZITOJ", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "PAĜONOMO", "PAGXONOMO", "PAĜNOMO", "PAGXNOMO", "PAGENAME");
		addI18nAlias("pagenamee", "PAĜONOMOO", "PAGXONOMOO", "PAĜNOMOO", "PAGXNOMOO", "PAGENAMEE");
		addI18nAlias("namespace", "NOMSPACO", "NAMESPACE");
		addI18nAlias("namespacee", "NOMSPACOO", "NAMESPACEE");
		addI18nAlias("namespacenumber", "NUMERODENOMSPACO", "NOMSPACNUMERO", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "DISKUTNOMSPACO", "TALKSPACE");
		addI18nAlias("talkspacee", "DISKUTNOMSPACOO", "TALKSPACEE");
		addI18nAlias("fullpagename", "TUTAPAĜONOMO", "TUTAPAGXONOMO", "TUTAPAĜNOMO", "TUTAPAGXNOMO", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "TUTAPAĜONOMOO", "TUTAPAGXONOMOO", "TUTAPAĜNOMOO", "TUTAPAGXNOMOO", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "SUBPAĜONOMO", "SUBPAGXONOMO", "SUBPAĜNOMO", "SUBPAGXNOMO", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "SUBPAĜONOMOO", "SUBPAGXONOMOO", "SUBPAĜNOMOO", "SUBPAGXNOMOO", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "PATRAPAĜONOMO", "PATRAPAGXONOMO", "PATRAPAĜNOMO", "PATRAPAGXNOMO", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "PATRAPAĜONOMOO", "PATRAPAGXONOMOO", "PATRAPAĜNOMOO", "PATRAPAGXNOMOO", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "DISKUTPAĜONOMO", "DISKUTPAGXONOMO", "DISKUTPAĜNOMO", "DISKUTPAGXNOMO", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "DISKUTPAĜONOMOO", "DISKUTPAGXONOMOO", "DISKUTPAĜNOMOO", "DISKUTPAGXNOMOO", "TALKPAGENAMEE");
		addI18nCIAlias("msg", "MSĜ:", "MSGX:", "MSG:");
		addI18nCIAlias("subst", "ANSTAT:", "SUBST:");
		addI18nCIAlias("safesubst", "SEKURANSTAT:", "SAFESUBST:");
		addI18nCIAlias("msgnw", "NVMSĜ:", "NVMSGX:", "MSGNW:");
		addI18nAlias("img_thumbnail", "eta", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "eta=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "dekstra", "dekstre", "right");
		addI18nAlias("img_left", "maldekstra", "maldekstre", "left");
		addI18nAlias("img_none", "nenio", "neniu", "none");
		addI18nAlias("img_width", "$1ra", "$1px");
		addI18nAlias("img_center", "centra", "meza", "center", "centre");
		addI18nAlias("img_framed", "kadro", "enkadrita", "enkadrite", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "senkadra", "frameless");
		addI18nAlias("img_page", "paĝo=$1", "paĝo $1", "pagxo=$1", "pagxo_$1", "page=$1", "page $1");
		addI18nAlias("img_upright", "altdekstre", "altdekstre=$1", "altdekstre_$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "kadra", "kadrita", "kadrigita", "kadrite", "kadrigite", "border");
		addI18nAlias("img_sub", "sube", "malsupre", "sub");
		addI18nAlias("img_super", "supre", "malsube", "super", "sup");
		addI18nAlias("img_top", "alte", "top");
		addI18nAlias("img_text_top", "tekst-alte", "text-top");
		addI18nAlias("img_middle", "meze", "middle");
		addI18nAlias("img_bottom", "malalte", "bottom");
		addI18nAlias("img_text_bottom", "suba-teksto", "text-bottom");
		addI18nAlias("img_link", "ligilo=$1", "link=$1");
		addI18nAlias("img_alt", "alternative=$1", "alt=$1");
		addI18nAlias("img_class", "klaso=$1", "class=$1");
		addI18nCIAlias("int", "ENE:", "INT:");
		addI18nAlias("sitename", "TTT-NOMO", "RETPAĜNOMO", "RETPAGXNOMO", "RETEJNOMO", "SITENAME");
		addI18nCIAlias("nse", "NSS:", "NSO:", "NSE:");
		addI18nCIAlias("localurl", "LOKATTT:", "LOCALURL:");
		addI18nCIAlias("localurle", "LOKATTTT:", "LOCALURLE:");
		addI18nCIAlias("articlepath", "ARTIKOLAPADO", "ARTIKOLAVOJO", "ARTICLEPATH");
		addI18nCIAlias("pageid", "IDENTIGILODEPAĜO", "PAĜID", "PAGEID");
		addI18nCIAlias("server", "SERVILO", "SERVER");
		addI18nCIAlias("servername", "NOMODESERVILO", "SERVILANOMO", "SERVILONOMO", "SERVERNAME");
		addI18nCIAlias("scriptpath", "SKRIPTO-VOJO", "SKRIPTOVOJO", "SKRIPTVOJO", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "STILO-VOJO", "STILOVOJO", "STILVOJO", "STYLEPATH");
		addI18nCIAlias("grammar", "GRAMATIKO:", "GRAMMAR:");
		addI18nCIAlias("gender", "SEKSO:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__NEKONVERTUTITOLON__", "__NKT__", "__NTC__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__NEKONVERTUENHAVON__", "__NKH__", "__NCC__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "NUNASEMAJNO", "CURRENTWEEK");
		addI18nAlias("localweek", "LOKASEMAJNO", "LOCALWEEK");
		addI18nAlias("revisionyear", "JARODEREVIZIO", "REVISIONYEAR");
		addI18nCIAlias("plural", "PLURALA:", "PLURAL:");
		addI18nCIAlias("fullurl", "PLENALIGILO:", "PLENLIG:", "TUTATTT:", "FULLURL:");
		addI18nCIAlias("fullurle", "PLENALIGILOO:", "PLENLIGG:", "TUTATTTT:", "FULLURLE:");
		addI18nCIAlias("lcfirst", "MALMAJUSKLEUNUA:", "MINUSKLEUNUA:", "MMU:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "MAJUSKLEUNUA:", "MALMINUSKLEUNUA:", "MU:", "UCFIRST:");
		addI18nCIAlias("lc", "MALMAJUSKLE:", "MINUSKLE:", "LC:");
		addI18nCIAlias("uc", "MAJUSKLE:", "MALMINUSKLE:", "UC:");
		addI18nAlias("displaytitle", "MONTRUTITOLON:", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "__LIGILOALNOVASEKCIO__", "__NSL__", "__LNS__", "__LANS__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__SENLIGILOALNOVASEKCIO__", "__NNSL__", "__SLNS__", "__SLANS__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "NUNAVERSIO", "CURRENTVERSION");
		addI18nAlias("currenttimestamp", "NUNATEMPINDIKO", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "LOKATEMPINDIKO", "LOCALTIMESTAMP");
		addI18nCIAlias("language", "#LINGVO:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "ENHAVA-LINGVO", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "PAĜOJENNOMSPACO", "PAGXOJENNOMSPACO", "PAĜOJENS", "PAGXOJENNS", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "NOMBRODEADMINOJ", "NUMBEROFADMINS");
		addI18nCIAlias("special", "speciala", "special");
		addI18nAlias("defaultsort", "DEFAŬLTORDIGO:", "DEFAUXLTORDIGO:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "DOSIERO-VORO", "DOSIERVOJO", "FILEPATH:");
		addI18nCIAlias("tag", "marko", "etikedo", "tag");
		addI18nAlias("hiddencat", "__KK__", "__KAŜITAKATEGORIO__", "__KASXITAKATEGORIO__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "PAĜOJENKATEGORIO", "PAGXOJENKATEGORIO", "PAĜOJENKAT", "PAGXOJENKAT", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "PAĜOPEZO", "PAGXOPEZO", "PEZODEPAĜO", "PEZODEPAGXO", "PAGESIZE");
		addI18nAlias("index", "__INDEKSU__", "__INDEKSI__", "__INDEX__");
		addI18nAlias("noindex", "__NEINDEKSU__", "__NIU__", "__NOINDEX__");
		addI18nAlias("staticredirect", "__STATIKAALIDIREKTO__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "PROTEKTONIVELO", "PROTECTIONLEVEL");
		addI18nCIAlias("url_path", "VOJO", "PATH");
		addI18nCIAlias("url_wiki", "VIKIO", "WIKI");
		addI18nCIAlias("url_query", "INFORMPETO", "QUERY");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://eo.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "eo";
	}
}
