/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class FoConfig extends TemplateConfig {
	public FoConfig() {
		addNamespaceAlias(-2, "Miðil");
		addNamespaceAlias(-1, "Serstakt", "Serstakur");
		addNamespaceAlias(1, "Kjak");
		addNamespaceAlias(2, "Brúkari");
		addNamespaceAlias(3, "Brúkarakjak", "Brúkari_kjak");
		addNamespaceAlias(5, "Wikipedia-kjak", "Wikipedia_kjak");
		addNamespaceAlias(6, "Mynd");
		addNamespaceAlias(7, "Myndakjak", "Mynd_kjak");
		addNamespaceAlias(8, "MediaWiki", "MidiaWiki");
		addNamespaceAlias(9, "MediaWiki-kjak", "MidiaWiki_kjak");
		addNamespaceAlias(10, "Fyrimynd");
		addNamespaceAlias(11, "Fyrimyndakjak", "Fyrimynd_kjak");
		addNamespaceAlias(12, "Hjálp");
		addNamespaceAlias(13, "Hjálparkjak", "Hjálp_kjak");
		addNamespaceAlias(14, "Bólkur");
		addNamespaceAlias(15, "Bólkakjak", "Bólkur_kjak");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://fo.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "fo";
	}
}
