/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class GaConfig extends TemplateConfig {
	public GaConfig() {
		addNamespaceAlias(-2, "Meán");
		addNamespaceAlias(-1, "Speisialta");
		addNamespaceAlias(1, "Plé");
		addNamespaceAlias(2, "Úsáideoir");
		addNamespaceAlias(3, "Plé_úsáideora");
		addNamespaceAlias(5, "Plé_{{grammar:genitive|Wikipedia}}");
		addNamespaceAlias(6, "Íomhá");
		addNamespaceAlias(7, "Plé_íomhá", "Plé_í­omhá");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Plé_MediaWiki");
		addNamespaceAlias(10, "Teimpléad", "Múnla");
		addNamespaceAlias(11, "Plé_teimpléid", "Plé_múnla");
		addNamespaceAlias(12, "Cabhair");
		addNamespaceAlias(13, "Plé_cabhrach");
		addNamespaceAlias(14, "Catagóir", "Rang");
		addNamespaceAlias(15, "Plé_catagóire");

		addI18nCIAlias("redirect", "#athsheoladh", "#REDIRECT");
		addI18nCIAlias("notoc", "__GANCÁ__", "__NOTOC__");
		addI18nCIAlias("forcetoc", "__CÁGACHUAIR__", "__FORCETOC__");
		addI18nCIAlias("toc", "__CÁ__", "__TOC__");
		addI18nCIAlias("noeditsection", "__GANMHÍRATHRÚ__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "MÍLÁITHREACH", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "AINMNAMÍOSALÁITHREAÍ", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "GINAINMNAMÍOSALÁITHREAÍ", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "GIORRÚNAMÍOSALÁITHREAÍ", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "LÁLÁITHREACH", "CURRENTDAY");
		addI18nAlias("currentdayname", "AINMANLAELÁITHRIGH", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "BLIAINLÁITHREACH", "CURRENTYEAR");
		addI18nAlias("currenttime", "AMLÁITHREACH", "CURRENTTIME");
		addI18nAlias("numberofarticles", "LÍONNANALT", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "LÍONNAGCOMHAD", "NUMBEROFFILES");
		addI18nAlias("pagename", "AINMANLGH", "PAGENAME");
		addI18nAlias("pagenamee", "AINMANLGHB", "PAGENAMEE");
		addI18nAlias("namespace", "AINMSPÁS", "NAMESPACE");
		addI18nCIAlias("msg", "TCHT:", "MSG:");
		addI18nCIAlias("subst", "IONAD:", "SUBST:");
		addI18nCIAlias("msgnw", "TCHTFS:", "MSGNW:");
		addI18nAlias("img_thumbnail", "mionsamhail", "mion", "thumbnail", "thumb");
		addI18nAlias("img_right", "deas", "right");
		addI18nAlias("img_left", "clé", "left");
		addI18nAlias("img_none", "faic", "none");
		addI18nAlias("img_center", "lár", "center", "centre");
		addI18nAlias("img_framed", "fráma", "frámaithe", "framed", "enframed", "frame");
		addI18nCIAlias("int", "INMH:", "INT:");
		addI18nAlias("sitename", "AINMANTSUÍMH", "SITENAME");
		addI18nCIAlias("ns", "AS:", "NS:");
		addI18nCIAlias("localurl", "URLÁITIÚIL", "LOCALURL:");
		addI18nCIAlias("localurle", "URLÁITIÚILB", "LOCALURLE:");
		addI18nCIAlias("server", "FREASTALAÍ", "SERVER");
		addI18nCIAlias("servername", "AINMANFHREASTALAÍ", "SERVERNAME");
		addI18nCIAlias("scriptpath", "SCRIPTCHOSÁN", "SCRIPTPATH");
		addI18nCIAlias("grammar", "GRAMADACH:", "GRAMMAR:");
		addI18nCIAlias("notitleconvert", "__GANTIONTÚNADTEIDEAL__", "__GANTT__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__GANTIONTÚNANÁBHAIR__", "__GANTA__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "SEACHTAINLÁITHREACH", "CURRENTWEEK");
		addI18nAlias("currentdow", "LÁLÁITHREACHNAS", "CURRENTDOW");
		addI18nAlias("revisionid", "IDANLEASAITHE", "REVISIONID");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ga.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ga";
	}
}
