/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class HifConfig extends TemplateConfig {
	public HifConfig() {
		addNamespaceAlias(-2, "saadhan");
		addNamespaceAlias(-1, "khaas");
		addNamespaceAlias(1, "baat");
		addNamespaceAlias(2, "sadasya");
		addNamespaceAlias(3, "sadasya_ke_baat");
		addNamespaceAlias(5, "Wikipedia_baat");
		addNamespaceAlias(6, "file");
		addNamespaceAlias(7, "file_ke_baat");
		addNamespaceAlias(9, "Mediawiki_ke_baat");
		addNamespaceAlias(11, "Template_ke_baat");
		addNamespaceAlias(12, "madat");
		addNamespaceAlias(13, "madat_ke_baat");
		addNamespaceAlias(14, "vibhag");
		addNamespaceAlias(15, "voibhag_ke_baat");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://hif.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "hif";
	}
}
