/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class IeConfig extends TemplateConfig {
	public IeConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Special");
		addNamespaceAlias(1, "Discussion");
		addNamespaceAlias(2, "Usator");
		addNamespaceAlias(3, "Usator_Discussion");
		addNamespaceAlias(5, "Wikipedia_Discussion");
		addNamespaceAlias(6, "File");
		addNamespaceAlias(7, "File_Discussion");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_Discussion");
		addNamespaceAlias(10, "Avise");
		addNamespaceAlias(11, "Avise_Discussion");
		addNamespaceAlias(12, "Auxilie");
		addNamespaceAlias(13, "Auxilie_Discussion");
		addNamespaceAlias(14, "Categorie");
		addNamespaceAlias(15, "Categorie_Discussion");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ie.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ie";
	}
}
