/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class IoConfig extends TemplateConfig {
	public IoConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Specala");
		addNamespaceAlias(1, "Debato");
		addNamespaceAlias(2, "Uzanto");
		addNamespaceAlias(3, "Uzanto_Debato");
		addNamespaceAlias(5, "Wikipedia_Debato");
		addNamespaceAlias(6, "Arkivo", "Imajo");
		addNamespaceAlias(7, "Arkivo_Debato", "Imajo_Debato");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_Debato");
		addNamespaceAlias(10, "Shablono", "Modelo");
		addNamespaceAlias(11, "Shablono_Debato", "Modelo_Debato");
		addNamespaceAlias(12, "Helpo");
		addNamespaceAlias(13, "Helpo_Debato");
		addNamespaceAlias(14, "Kategorio");
		addNamespaceAlias(15, "Kategorio_Debato");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://io.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "io";
	}
}
