/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class JaConfig extends TemplateConfig {
	public JaConfig() {
		addNamespaceAlias(-2, "メディア");
		addNamespaceAlias(-1, "特別");
		addNamespaceAlias(1, "トーク", "ノート");
		addNamespaceAlias(2, "利用者");
		addNamespaceAlias(3, "利用者・トーク", "利用者‐会話");
		addNamespaceAlias(5, "Wikipedia・トーク", "Wikipedia‐ノート");
		addNamespaceAlias(6, "ファイル", "画像");
		addNamespaceAlias(7, "ファイル・トーク", "画像‐ノート", "ファイル‐ノート");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki・トーク", "MediaWiki‐ノート");
		addNamespaceAlias(10, "テンプレート");
		addNamespaceAlias(11, "テンプレート・トーク", "Template‐ノート");
		addNamespaceAlias(12, "ヘルプ");
		addNamespaceAlias(13, "ヘルプ・トーク", "Help‐ノート");
		addNamespaceAlias(14, "カテゴリ");
		addNamespaceAlias(15, "カテゴリ・トーク", "Category‐ノート");

		addI18nCIAlias("redirect", "#転送", "#リダイレクト", "＃転送", "＃リダイレクト", "#REDIRECT");
		addI18nCIAlias("notoc", "__目次非表示__", "＿＿目次非表示＿＿", "__NOTOC__");
		addI18nCIAlias("nogallery", "__ギャラリー非表示__", "＿＿ギャラリー非表示＿＿", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__目次強制__", "＿＿目次強制＿＿", "__FORCETOC__");
		addI18nCIAlias("toc", "__目次__", "＿＿目次＿＿", "__TOC__");
		addI18nCIAlias("noeditsection", "__節編集非表示__", "__セクション編集非表示__", "＿＿セクション編集非表示＿＿", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "現在の月", "協定月", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "現在の月1", "協定月1", "協定月１", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "現在の月名", "協定月名", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "現在の月属格", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "現在の月省略形", "省略協定月", "協定月省略", "協定月省略形", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "現在の日", "協定日", "CURRENTDAY");
		addI18nAlias("currentday2", "現在の日2", "協定日2", "協定日２", "CURRENTDAY2");
		addI18nAlias("currentdayname", "現在の曜日名", "協定曜日", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "現在の年", "協定年", "CURRENTYEAR");
		addI18nAlias("currenttime", "現在の時刻", "協定時間", "協定時刻", "CURRENTTIME");
		addI18nAlias("currenthour", "現在の時", "協定時", "CURRENTHOUR");
		addI18nAlias("localmonth", "地方時の月", "現地月", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "地方時の月1", "現地月1", "現地月１", "LOCALMONTH1");
		addI18nAlias("localmonthname", "地方時の月名1", "現地月名", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "地方時の月属格", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "地方時の月省略形", "省略現地月", "LOCALMONTHABBREV");
		addI18nAlias("localday", "地方時の日", "現地日", "ローカルデイ", "LOCALDAY");
		addI18nAlias("localday2", "地方時の日2", "現地日2", "現地日２", "LOCALDAY2");
		addI18nAlias("localdayname", "地方時の曜日名", "現地曜日", "ローカルデイネーム", "LOCALDAYNAME");
		addI18nAlias("localyear", "地方時の年", "現地年", "ローカルイヤー", "LOCALYEAR");
		addI18nAlias("localtime", "地方時の時刻", "現地時間", "ローカルタイム", "LOCALTIME");
		addI18nAlias("localhour", "地方時の時", "現地時", "LOCALHOUR");
		addI18nAlias("numberofpages", "ページ数", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "記事数", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "ファイル数", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "利用者数", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "活動利用者数", "有効な利用者数", "有効利用者数", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "編集回数", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "閲覧回数", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "ページ名", "PAGENAME");
		addI18nAlias("pagenamee", "ページ名E", "ページ名Ｅ", "PAGENAMEE");
		addI18nAlias("namespace", "名前空間", "NAMESPACE");
		addI18nAlias("namespacee", "名前空間E", "名前空間Ｅ", "NAMESPACEE");
		addI18nAlias("talkspace", "トーク空間", "ノート空間", "会話空間", "トークスペース", "TALKSPACE");
		addI18nAlias("talkspacee", "トーク空間E", "トーク空間Ｅ", "ノート空間E", "会話空間E", "ノート空間Ｅ", "会話空間Ｅ", "トークスペースE", "トークスペースＥ", "TALKSPACEE");
		addI18nAlias("subjectspace", "主空間", "標準空間", "記事空間", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "主空間E", "標準空間E", "標準空間Ｅ", "記事空間E", "記事空間Ｅ", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "完全なページ名", "フルページ名", "完全な記事名", "完全記事名", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "完全なページ名E", "フルページ名E", "フルページ名Ｅ", "完全なページ名Ｅ", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "サブページ名", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "サブページ名E", "サブページ名Ｅ", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "親ページ名", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "親ページ名E", "親ページ名Ｅ", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "トークページ名", "会話ページ名", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "トークページ名E", "会話ページ名E", "会話ページ名Ｅ", "トークページ名Ｅ", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "主ページ名", "記事ページ名", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "主ページ名E", "記事ページ名E", "主ページ名Ｅ", "記事ページ名Ｅ", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "メッセージ:", "MSG:");
		addI18nCIAlias("subst", "展開:", "展開：", "SUBST:");
		addI18nCIAlias("safesubst", "安全展開:", "SAFESUBST:");
		addI18nCIAlias("msgnw", "ウィキ無効メッセージ:", "MSGNW:");
		addI18nAlias("img_thumbnail", "サムネイル", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "代替画像=$1", "サムネイル=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "右", "right");
		addI18nAlias("img_left", "左", "left");
		addI18nAlias("img_none", "なし", "無し", "none");
		addI18nAlias("img_width", "$1ピクセル", "$1px");
		addI18nAlias("img_center", "中央", "center", "centre");
		addI18nAlias("img_framed", "フレーム", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "フレームなし", "frameless");
		addI18nAlias("img_page", "ページ=$1", "ページ $1", "page=$1", "page $1");
		addI18nAlias("img_upright", "右上", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "境界", "ボーダー", "border");
		addI18nAlias("img_baseline", "下線", "ベースライン", "baseline");
		addI18nAlias("img_sub", "下付き", "sub");
		addI18nAlias("img_super", "上付き", "super", "sup");
		addI18nAlias("img_top", "上端", "top");
		addI18nAlias("img_text_top", "文上端", "text-top");
		addI18nAlias("img_middle", "中心", "middle");
		addI18nAlias("img_bottom", "下端", "bottom");
		addI18nAlias("img_text_bottom", "文下端", "text-bottom");
		addI18nAlias("img_link", "リンク=$1", "link=$1");
		addI18nAlias("img_alt", "代替文=$1", "alt=$1");
		addI18nCIAlias("int", "インターフェース:", "インタ:", "インターフェース：", "インタ：", "インターフェイス:", "インターフェイス：", "INT:");
		addI18nAlias("sitename", "サイト名", "サイトネーム", "SITENAME");
		addI18nCIAlias("ns", "名前空間:", "名前空間：", "名空:", "名空：", "NS:");
		addI18nCIAlias("nse", "名前空間E:", "NSE:");
		addI18nCIAlias("localurl", "ローカルURL:", "ローカルＵＲＬ：", "LOCALURL:");
		addI18nCIAlias("localurle", "ローカルURLE:", "ローカルＵＲＬＥ：", "LOCALURLE:");
		addI18nCIAlias("articlepath", "記事パス", "ARTICLEPATH");
		addI18nCIAlias("server", "サーバー", "サーバ", "SERVER");
		addI18nCIAlias("servername", "サーバー名", "サーバーネーム", "サーバ名", "サーバネーム", "SERVERNAME");
		addI18nCIAlias("scriptpath", "スクリプトパス", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "スタイルパス", "STYLEPATH");
		addI18nCIAlias("grammar", "文法:", "GRAMMAR:");
		addI18nCIAlias("gender", "性別:", "性別：", "GENDER:");
		addI18nCIAlias("notitleconvert", "__タイトル変換無効__", "__タイトルコンバート拒否__", "＿＿タイトルコンバート拒否＿＿", "__タイトル非表示__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__内容変換無効__", "__内容変換抑制__", "＿＿内容変換抑制＿＿", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "現在の週", "CURRENTWEEK");
		addI18nAlias("currentdow", "現在の曜日番号", "CURRENTDOW");
		addI18nAlias("localweek", "地方時の週", "現地週", "ローカルウィーク", "LOCALWEEK");
		addI18nAlias("localdow", "地方時の曜日番号", "LOCALDOW");
		addI18nAlias("revisionid", "版のID", "リビジョンID", "差分ID", "リビジョンＩＤ", "差分ＩＤ", "REVISIONID");
		addI18nAlias("revisionday", "版の日", "リビジョン日", "差分日", "REVISIONDAY");
		addI18nAlias("revisionday2", "版の日2", "リビジョン日2", "差分日2", "リビジョン日２", "差分日２", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "版の月", "リビジョン月", "差分月", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "版の月1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "版の年", "リビジョン年", "差分年", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "版のタイムスタンプ", "リビジョンタイムスタンプ", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "版の利用者", "リビジョンユーザー", "リビジョンユーザ", "リビジョン利用者", "差分利用者", "REVISIONUSER");
		addI18nCIAlias("plural", "複数:", "複数：", "PLURAL:");
		addI18nCIAlias("fullurl", "完全なURL:", "フルURL:", "完全なＵＲＬ：", "フルＵＲＬ：", "FULLURL:");
		addI18nCIAlias("fullurle", "完全なURLE:", "フルURLE:", "完全なＵＲＬＥ：", "フルＵＲＬＥ：", "FULLURLE:");
		addI18nCIAlias("lcfirst", "先頭小文字:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "先頭大文字:", "UCFIRST:");
		addI18nCIAlias("lc", "小文字:", "LC:");
		addI18nCIAlias("uc", "大文字:", "UC:");
		addI18nCIAlias("raw", "生:", "RAW:");
		addI18nAlias("displaytitle", "表示タイトル:", "DISPLAYTITLE");
		addI18nAlias("rawsuffix", "生", "R");
		addI18nAlias("newsectionlink", "__新しい節リンク__", "__新しいセクションリンク__", "__新セクションリンク__", "＿＿新しいセクションリンク＿＿", "＿＿新セクションリンク＿＿", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__新しい節リンク非表示__", "__新しいセクションリンク非表示__", "＿＿新しいセクションリンク非表示＿＿", "__新セクションリンク非表示__", "＿＿新セクションリンク非表示＿＿", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "現在のバージョン", "ウィキバージョン", "MediaWikiバージョン", "メディアウィキバージョン", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "URLエンコード:", "ＵＲＬエンコード：", "URLENCODE:");
		addI18nCIAlias("anchorencode", "アンカー用エンコード", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "現在のタイムスタンプ", "協定タイムスタンプ", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "地方時のタイムスタンプ", "現地タイムスタンプ", "ローカルタイムスタンプ", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "方向印", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#言語:", "＃言語：", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "内容言語", "記事言語", "プロジェクト言語", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "名前空間内ページ数", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "管理者数", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "数整形", "FORMATNUM");
		addI18nCIAlias("padleft", "補充左", "PADLEFT");
		addI18nCIAlias("padright", "補充右", "PADRIGHT");
		addI18nCIAlias("special", "特別", "special");
		addI18nAlias("defaultsort", "デフォルトソート:", "デフォルトソート：", "デフォルトソートキー:", "デフォルトカテゴリソート:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "ファイルパス:", "ファイルパス：", "FILEPATH:");
		addI18nCIAlias("tag", "タグ", "tag");
		addI18nAlias("hiddencat", "__カテゴリ非表示__", "__カテ非表示__", "__非表示カテ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "カテゴリ内ページ数", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "ページサイズ", "PAGESIZE");
		addI18nAlias("index", "__インデックス__", "＿＿インデックス＿＿", "__INDEX__");
		addI18nAlias("noindex", "__インデックス拒否__", "＿＿インデックス拒否＿＿", "__NOINDEX__");
		addI18nAlias("numberingroup", "グループ人数", "グループ所属人数", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__静的転送__", "__二重転送解消無効__", "＿＿二重転送解消無効＿＿", "__二重転送修正無効__", "＿＿二重転送修正無効＿＿", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "保護レベル", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "日付整形", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "パス", "PATH");
		addI18nCIAlias("url_wiki", "ウィキ", "WIKI");
		addI18nCIAlias("url_query", "クエリ", "クエリー", "QUERY");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ja.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ja";
	}
}
