/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class KkConfig extends TemplateConfig {
	public KkConfig() {
		addNamespaceAlias(-2, "Таспа", "Taspa", "تاسپا");
		addNamespaceAlias(-1, "Арнайы", "Arnaýı", "ارنايى");
		addNamespaceAlias(1, "Талқылау", "Talqılaw", "تالقىلاۋ");
		addNamespaceAlias(2, "Қатысушы", "Qatıswşı", "قاتىسۋشى");
		addNamespaceAlias(3, "Қатысушы_талқылауы", "Qatıswşı_talqılawı", "قاتىسۋشى_تالقىلاۋى");
		addNamespaceAlias(5, "Wikipedia_талқылауы", "Wikipedia_talqılawı", "Wikipedia_تالقىلاۋى");
		addNamespaceAlias(6, "Сурет", "Swret", "سۋرەت");
		addNamespaceAlias(7, "Сурет_талқылауы", "Swret_talqılawı", "سۋرەت_تالقىلاۋى");
		addNamespaceAlias(8, "МедиаУики", "MedïaWïkï", "مەدياۋيكي");
		addNamespaceAlias(9, "МедиаУики_талқылауы", "MedïaWïkï_talqılawı", "مەدياۋيكي_تالقىلاۋى");
		addNamespaceAlias(10, "Үлгі", "Ülgi", "ٷلگٸ", "ٴۇلگٴى");
		addNamespaceAlias(11, "Үлгі_талқылауы", "Ülgi_talqılawı", "ٷلگٸ_تالقىلاۋى", "ٴۇلگٴى_تالقىلاۋى");
		addNamespaceAlias(12, "Анықтама", "Anıqtama", "انىقتاما");
		addNamespaceAlias(13, "Анықтама_талқылауы", "Anıqtama_talqılawı", "انىقتاما_تالقىلاۋى");
		addNamespaceAlias(14, "Санат", "Sanat", "سانات");
		addNamespaceAlias(15, "Санат_талқылауы", "Sanat_talqılawı", "سانات_تالقىلاۋى");

		addI18nCIAlias("redirect", "#АЙДАУ", "#REDIRECT");
		addI18nCIAlias("notoc", "__МАЗМҰНСЫЗ__", "__МСЫЗ__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__ҚОЙМАСЫЗ__", "__ҚСЫЗ__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__МАЗМҰНДАТҚЫЗУ__", "__МҚЫЗУ__", "__FORCETOC__");
		addI18nCIAlias("toc", "__МАЗМҰНЫ__", "__МЗМН__", "__TOC__");
		addI18nCIAlias("noeditsection", "__БӨЛІДІМӨНДЕМЕУ__", "__БӨЛІМӨНДЕТКІЗБЕУ__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "АҒЫМДАҒЫАЙ", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "АҒЫМДАҒЫАЙАТАУЫ", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "АҒЫМДАҒЫАЙІЛІКАТАУЫ", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "АҒЫМДАҒЫАЙЖИЫР", "АҒЫМДАҒЫАЙҚЫСҚА", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "АҒЫМДАҒЫКҮН", "CURRENTDAY");
		addI18nAlias("currentday2", "АҒЫМДАҒЫКҮН2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "АҒЫМДАҒЫКҮНАТАУЫ", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "АҒЫМДАҒЫЖЫЛ", "CURRENTYEAR");
		addI18nAlias("currenttime", "АҒЫМДАҒЫУАҚЫТ", "CURRENTTIME");
		addI18nAlias("currenthour", "АҒЫМДАҒЫСАҒАТ", "CURRENTHOUR");
		addI18nAlias("localmonth", "ЖЕРГІЛІКТІАЙ", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonthname", "ЖЕРГІЛІКТІАЙАТАУЫ", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "ЖЕРГІЛІКТІАЙІЛІКАТАУЫ", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "ЖЕРГІЛІКТІАЙЖИЫР", "ЖЕРГІЛІКТІАЙҚЫСҚАША", "ЖЕРГІЛІКТІАЙҚЫСҚА", "LOCALMONTHABBREV");
		addI18nAlias("localday", "ЖЕРГІЛІКТІКҮН", "LOCALDAY");
		addI18nAlias("localday2", "ЖЕРГІЛІКТІКҮН2", "LOCALDAY2");
		addI18nAlias("localdayname", "ЖЕРГІЛІКТІКҮНАТАУЫ", "LOCALDAYNAME");
		addI18nAlias("localyear", "ЖЕРГІЛІКТІЖЫЛ", "LOCALYEAR");
		addI18nAlias("localtime", "ЖЕРГІЛІКТІУАҚЫТ", "LOCALTIME");
		addI18nAlias("localhour", "ЖЕРГІЛІКТІСАҒАТ", "LOCALHOUR");
		addI18nAlias("numberofpages", "БЕТСАНЫ", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "МАҚАЛАСАНЫ", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "ФАЙЛСАНЫ", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "ҚАТЫСУШЫСАНЫ", "NUMBEROFUSERS");
		addI18nAlias("numberofedits", "ӨҢДЕМЕСАНЫ", "ТҮЗЕТУСАНЫ", "NUMBEROFEDITS");
		addI18nAlias("pagename", "БЕТАТАУЫ", "PAGENAME");
		addI18nAlias("pagenamee", "БЕТАТАУЫ2", "PAGENAMEE");
		addI18nAlias("namespace", "ЕСІМАЯСЫ", "NAMESPACE");
		addI18nAlias("namespacee", "ЕСІМАЯСЫ2", "NAMESPACEE");
		addI18nAlias("talkspace", "ТАЛҚЫЛАУАЯСЫ", "TALKSPACE");
		addI18nAlias("talkspacee", "ТАЛҚЫЛАУАЯСЫ2", "TALKSPACEE");
		addI18nAlias("subjectspace", "ТАҚЫРЫПБЕТІ", "МАҚАЛАБЕТІ", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "ТАҚЫРЫПБЕТІ2", "МАҚАЛАБЕТІ2", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "ТОЛЫҚБЕТАТАУЫ", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "ТОЛЫҚБЕТАТАУЫ2", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "БЕТШЕАТАУЫ", "АСТЫҢҒЫБЕТАТАУЫ", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "БЕТШЕАТАУЫ2", "АСТЫҢҒЫБЕТАТАУЫ2", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "НЕГІЗГІБЕТАТАУЫ", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "НЕГІЗГІБЕТАТАУЫ2", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "ТАЛҚЫЛАУБЕТАТАУЫ", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "ТАЛҚЫЛАУБЕТАТАУЫ2", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "ТАҚЫРЫПБЕТАТАУЫ", "МАҚАЛАБЕТАТАУЫ", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "ТАҚЫРЫПБЕТАТАУЫ2", "МАҚАЛАБЕТАТАУЫ2", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "ХБР:", "MSG:");
		addI18nCIAlias("subst", "БӘДЕЛ:", "SUBST:");
		addI18nCIAlias("msgnw", "УИКИСІЗХБР:", "MSGNW:");
		addI18nAlias("img_thumbnail", "нобай", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "нобай=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "оңға", "оң", "right");
		addI18nAlias("img_left", "солға", "сол", "left");
		addI18nAlias("img_none", "ешқандай", "жоқ", "none");
		addI18nAlias("img_width", "$1 нүкте", "$1px");
		addI18nAlias("img_center", "ортаға", "орта", "center", "centre");
		addI18nAlias("img_framed", "сүрмелі", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "сүрмесіз", "frameless");
		addI18nAlias("img_page", "бет=$1", "бет $1", "page=$1", "page $1");
		addI18nAlias("img_upright", "тікті", "тіктік=$1", "тіктік $1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "жиекті", "border");
		addI18nAlias("img_baseline", "тірекжол", "baseline");
		addI18nAlias("img_sub", "астылығы", "аст", "sub");
		addI18nAlias("img_super", "үстілігі", "үст", "super", "sup");
		addI18nAlias("img_top", "үстіне", "top");
		addI18nAlias("img_text_top", "мәтін-үстінде", "text-top");
		addI18nAlias("img_middle", "аралығына", "middle");
		addI18nAlias("img_bottom", "астына", "bottom");
		addI18nAlias("img_text_bottom", "мәтін-астында", "text-bottom");
		addI18nCIAlias("int", "ІШКІ:", "INT:");
		addI18nAlias("sitename", "ТОРАПАТАУЫ", "SITENAME");
		addI18nCIAlias("ns", "ЕА:", "ЕСІМАЯ:", "NS:");
		addI18nCIAlias("localurl", "ЖЕРГІЛІКТІЖАЙ:", "LOCALURL:");
		addI18nCIAlias("localurle", "ЖЕРГІЛІКТІЖАЙ2:", "LOCALURLE:");
		addI18nCIAlias("server", "СЕРВЕР", "SERVER");
		addI18nCIAlias("servername", "СЕРВЕРАТАУЫ", "SERVERNAME");
		addI18nCIAlias("scriptpath", "ӘМІРЖОЛЫ", "SCRIPTPATH");
		addI18nCIAlias("grammar", "СЕПТІГІ:", "СЕПТІК:", "GRAMMAR:");
		addI18nCIAlias("notitleconvert", "__ТАҚЫРЫПАТЫНТҮРЛЕНДІРГІЗБЕУ__", "__ТАТЖОҚ__", "__АТАУАЛМАСТЫРҒЫЗБАУ__", "__ААБАУ__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__МАҒЛҰМАТЫНТҮРЛЕНДІРГІЗБЕУ__", "__МАТЖОҚ__", "__МАҒЛҰМАТАЛМАСТЫРҒЫЗБАУ__", "__МАБАУ__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "АҒЫМДАҒЫАПТАСЫ", "АҒЫМДАҒЫАПТА", "CURRENTWEEK");
		addI18nAlias("currentdow", "АҒЫМДАҒЫАПТАКҮНІ", "CURRENTDOW");
		addI18nAlias("localweek", "ЖЕРГІЛІКТІАПТАСЫ", "ЖЕРГІЛІКТІАПТА", "LOCALWEEK");
		addI18nAlias("localdow", "ЖЕРГІЛІКТІАПТАКҮНІ", "LOCALDOW");
		addI18nAlias("revisionid", "ТҮЗЕТУНӨМІРІ", "НҰСҚАНӨМІРІ", "REVISIONID");
		addI18nAlias("revisionday", "ТҮЗЕТУКҮНІ", "НҰСҚАКҮНІ", "REVISIONDAY");
		addI18nAlias("revisionday2", "ТҮЗЕТУКҮНІ2", "НҰСҚАКҮНІ2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "ТҮЗЕТУАЙЫ", "НҰСҚААЙЫ", "REVISIONMONTH");
		addI18nAlias("revisionyear", "ТҮЗЕТУЖЫЛЫ", "НҰСҚАЖЫЛЫ", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "ТҮЗЕТУУАҚЫТЫТАҢБАСЫ", "НҰСҚАУАҚЫТТҮЙІНДЕМЕСІ", "REVISIONTIMESTAMP");
		addI18nCIAlias("plural", "КӨПШЕТҮРІ:", "КӨПШЕ:", "PLURAL:");
		addI18nCIAlias("fullurl", "ТОЛЫҚЖАЙЫ:", "ТОЛЫҚЖАЙ:", "FULLURL:");
		addI18nCIAlias("fullurle", "ТОЛЫҚЖАЙЫ2:", "ТОЛЫҚЖАЙ2:", "FULLURLE:");
		addI18nCIAlias("lcfirst", "КӘ1:", "КІШІӘРІППЕН1:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "БӘ1:", "БАСӘРІППЕН1:", "UCFIRST:");
		addI18nCIAlias("lc", "КӘ:", "КІШІӘРІППЕН:", "LC:");
		addI18nCIAlias("uc", "БӘ:", "БАСӘРІППЕН:", "UC:");
		addI18nCIAlias("raw", "ҚАМ:", "RAW:");
		addI18nAlias("displaytitle", "КӨРІНЕТІНТАҚЫРЫАПАТЫ", "КӨРСЕТІЛЕТІНАТАУ", "DISPLAYTITLE");
		addI18nAlias("rawsuffix", "Қ", "R");
		addI18nAlias("newsectionlink", "__ЖАҢАБӨЛІМСІЛТЕМЕСІ__", "__NEWSECTIONLINK__");
		addI18nAlias("currentversion", "БАҒДАРЛАМАНҰСҚАСЫ", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "ЖАЙДЫМҰҚАМДАУ:", "URLENCODE:");
		addI18nCIAlias("anchorencode", "ЖӘКІРДІМҰҚАМДАУ", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "АҒЫМДАҒЫУАҚЫТТҮЙІНДЕМЕСІ", "АҒЫМДАҒЫУАҚЫТТҮЙІН", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "ЖЕРГІЛІКТІУАҚЫТТҮЙІНДЕМЕСІ", "ЖЕРГІЛІКТІУАҚЫТТҮЙІН", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "БАҒЫТБЕЛГІСІ", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#ТІЛ:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "МАҒЛҰМАТТІЛІ", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "ЕСІМАЯБЕТСАНЫ:", "ЕАБЕТСАНЫ:", "АЯБЕТСАНЫ:", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "ӘКІМШІСАНЫ", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "САНПІШІМІ", "FORMATNUM");
		addI18nCIAlias("padleft", "СОЛҒАЫҒЫС", "СОЛЫҒЫС", "PADLEFT");
		addI18nCIAlias("padright", "ОҢҒАЫҒЫС", "ОҢЫҒЫС", "PADRIGHT");
		addI18nCIAlias("special", "арнайы", "special");
		addI18nAlias("defaultsort", "ӘДЕПКІСҰРЫПТАУ:", "ӘДЕПКІСАНАТСҰРЫПТАУ:", "ӘДЕПКІСҰРЫПТАУКІЛТІ:", "ӘДЕПКІСҰРЫП:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "ФАЙЛМЕКЕНІ:", "FILEPATH:");
		addI18nCIAlias("tag", "белгі", "tag");
		addI18nAlias("hiddencat", "__ЖАСЫРЫНСАНАТ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "САНАТТАҒЫБЕТТЕР", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "БЕТМӨЛШЕРІ", "PAGESIZE");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://kk.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "kk";
	}
}
