/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class KlConfig extends TemplateConfig {
	public KlConfig() {
		addNamespaceAlias(-1, "Immikkut", "Speciel", "Speciel");
		addNamespaceAlias(1, "Oqallinneq", "Diskussion", "Diskussion");
		addNamespaceAlias(2, "Atuisoq", "Bruger", "Bruger");
		addNamespaceAlias(3, "Atuisup_oqalliffia", "Brugerdiskussion", "Brugerdiskussion");
		addNamespaceAlias(5, "Wikipedia-p_oqalliffia", "Wikipedia-diskussion", "Wikipediaip oqalliffia", "Wikipedia_diskussion", "Wikipedia-diskussion");
		addNamespaceAlias(6, "Fiileq", "Fil", "Billede", "Fil", "Billede");
		addNamespaceAlias(7, "Fiilip_oqalliffia", "Fildiskussion", "Billeddiskussion", "Fildiskussion", "Billeddiskussion");
		addNamespaceAlias(8, "MediaWiki", "MediaWiki", "MediaWiki");
		addNamespaceAlias(9, "Mediawikip_oqalliffia", "MediaWiki-diskussion", "MediaWiki_diskussion", "MediaWiki-diskussion");
		addNamespaceAlias(10, "Ilisserut", "Skabelon", "Skabelon");
		addNamespaceAlias(11, "Ilisserummi_oqallinneq", "Skabelondiskussion", "Skabelondiskussion");
		addNamespaceAlias(12, "Ikiuutit", "Hjælp", "Hjælp");
		addNamespaceAlias(13, "Ikiuutini_oqallinneq", "Hjælp-diskussion", "Hjælp_diskussion", "Hjælp-diskussion");
		addNamespaceAlias(14, "Sumut_atassuseq", "Kategori", "Kategori");
		addNamespaceAlias(15, "Sumut_atassusermi_oqallinneq", "Kategoridiskussion", "Kategoridiskussion");
		addNamespaceAlias(-2, "Media");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://kl.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "kl";
	}
}
