/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class KuConfig extends TemplateConfig {
	public KuConfig() {
		addNamespaceAlias(-2, "Medya");
		addNamespaceAlias(-1, "Taybet");
		addNamespaceAlias(1, "Gotûbêj", "Nîqaş");
		addNamespaceAlias(2, "Bikarhêner");
		addNamespaceAlias(3, "Gotûbêja_bikarhêner", "Bikarhêner_nîqaş");
		addNamespaceAlias(5, "Wikipedia_gotûbêj", "Wikipedia_nîqaş");
		addNamespaceAlias(6, "Wêne");
		addNamespaceAlias(7, "Gotûbêja_wêneyî", "Wêne_nîqaş");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Gotûbêja_MediaWiki", "MediaWiki_nîqaş");
		addNamespaceAlias(10, "Şablon");
		addNamespaceAlias(11, "Gotûbêja_şablonê", "Şablon_nîqaş");
		addNamespaceAlias(12, "Alîkarî");
		addNamespaceAlias(13, "Gotûbêja_alîkariyê", "Alîkarî_nîqaş");
		addNamespaceAlias(14, "Kategorî");
		addNamespaceAlias(15, "Gotûbêja_kategoriyê", "Kategorî_nîqaş");

		addI18nCIAlias("redirect", "#BERALÎKIRIN", "#REDIRECT");
		addI18nCIAlias("notoc", "_NAVEROKTUNE_", "__NOTOC__");
		addI18nCIAlias("nogallery", "_GALERÎTUNE_", "__NOGALLERY__");
		addI18nCIAlias("toc", "_NAVEROK_", "__TOC__");
		addI18nAlias("currentmonth1", "MEHA_NIHA_1", "CURRENTMONTH1");
		addI18nAlias("currentday", "ROJA_NIHA", "CURRENTDAY");
		addI18nAlias("currentday2", "ROJA_NIHA2", "CURRENTDAY2");
		addI18nAlias("currenttime", "DEMA_NIHA", "CURRENTTIME");
		addI18nAlias("numberofpages", "HEJMARA_RÛPELAN", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "HEJMARA_GOTARAN", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "HEJMARA_DOSYEYAN", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "HEJMARA_BIKARHÊNERAN", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "HEJMARA_BIKARHÊNERÊN_ÇALAK", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "HEJMARA_GUHERTINAN", "NUMBEROFEDITS");
		addI18nAlias("subpagename", "BINRÛPEL", "SUBPAGENAME");
		addI18nAlias("img_right", "rast", "right");
		addI18nAlias("img_left", "çep", "left");
		addI18nAlias("img_link", "girêdan=$1", "link=$1");
		addI18nAlias("sitename", "NAVÊ_PROJEYÊ", "SITENAME");
		addI18nCIAlias("grammar", "RÊZIMAN.", "GRAMMAR:");
		addI18nCIAlias("gender", "ZAYEND.", "GENDER:");
		addI18nCIAlias("plural", "PIRRJIMAR:", "PLURAL:");
		addI18nAlias("currentversion", "VERSIYONA_NIHA", "CURRENTVERSION");
		addI18nCIAlias("language", "#ZIMAN", "#LANGUAGE:");
		addI18nAlias("numberofadmins", "HEJMARA_RÊVEBERAN", "NUMBEROFADMINS");
		addI18nCIAlias("special", "taybet", "special");
		addI18nCIAlias("pagesincategory_all", "hemû", "all");
		addI18nCIAlias("pagesincategory_pages", "rûpel", "pages");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ku.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ku";
	}
}
