/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class KyConfig extends TemplateConfig {
	public KyConfig() {
		addNamespaceAlias(-2, "Медиа");
		addNamespaceAlias(-1, "Атайын");
		addNamespaceAlias(1, "Баарлашуу");
		addNamespaceAlias(2, "Колдонуучу");
		addNamespaceAlias(3, "Колдонуучунун_баарлашуулары");
		addNamespaceAlias(5, "Wikipedia_баарлашуу");
		addNamespaceAlias(6, "Файл");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(10, "Калып");
		addNamespaceAlias(12, "Жардам");
		addNamespaceAlias(14, "Категория");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ky.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ky";
	}
}
