/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class LoConfig extends TemplateConfig {
	public LoConfig() {
		addNamespaceAlias(-2, "ສື່", "ສື່ອ");
		addNamespaceAlias(-1, "ພິເສດ");
		addNamespaceAlias(1, "ສົນທະນາ");
		addNamespaceAlias(2, "ຜູ້ໃຊ້");
		addNamespaceAlias(3, "ສົນທະນາຂອງຜູ້ໃຊ້");
		addNamespaceAlias(5, "ສົນທະນາກ່ຽວກັບWikipedia");
		addNamespaceAlias(6, "ຮູບ");
		addNamespaceAlias(7, "ສົນທະນາກ່ຽວກັບຮູບ");
		addNamespaceAlias(8, "ມີເດຍວິກິ");
		addNamespaceAlias(9, "ສົນທະນາກ່ຽວກັບມີເດຍວິກິ");
		addNamespaceAlias(10, "ແມ່ແບບ");
		addNamespaceAlias(11, "ສົນທະນາກ່ຽວກັບແມ່ແບບ");
		addNamespaceAlias(12, "ຊ່ວຍເຫຼືອ");
		addNamespaceAlias(13, "ສົນທະນາກ່ຽວກັບຊ່ວຍເຫຼືອ");
		addNamespaceAlias(14, "ໝວດ");
		addNamespaceAlias(15, "ສົນທະນາກ່ຽວກັບໝວດ");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://lo.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "lo";
	}
}
