/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class LtConfig extends TemplateConfig {
	public LtConfig() {
		addNamespaceAlias(-2, "Medija");
		addNamespaceAlias(-1, "Specialus");
		addNamespaceAlias(1, "Aptarimas");
		addNamespaceAlias(2, "Naudotojas", "Naudotojas", "Naudotoja");
		addNamespaceAlias(3, "Naudotojo_aptarimas", "Naudotojo_aptarimas", "Naudotojos_aptarimas");
		addNamespaceAlias(5, "Wikipedia_aptarimas");
		addNamespaceAlias(6, "Vaizdas");
		addNamespaceAlias(7, "Vaizdo_aptarimas");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_aptarimas");
		addNamespaceAlias(10, "Šablonas");
		addNamespaceAlias(11, "Šablono_aptarimas");
		addNamespaceAlias(12, "Pagalba");
		addNamespaceAlias(13, "Pagalbos_aptarimas");
		addNamespaceAlias(14, "Kategorija");
		addNamespaceAlias(15, "Kategorijos_aptarimas");

		addI18nCIAlias("redirect", "#PERADRESAVIMAS", "#REDIRECT");
		addI18nCIAlias("notoc", "__BETURIN__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__BEGALERIJOS__", "__NOGALLERY__");
		addI18nCIAlias("toc", "__TURINYS__", "__TOC__");
		addI18nCIAlias("noeditsection", "__BEREDAGSEKC__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "DABARTINISMĖNESIS", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "DABARTINIOMĖNESIOPAVADINIMAS", "CURRENTMONTHNAME");
		addI18nAlias("currentday", "DABARTINĖDIENA", "CURRENTDAY");
		addI18nAlias("currentday2", "DABARTINĖDIENA2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "DABARTINĖSDIENOSPAVADINIMAS", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "DABARTINIAIMETAI", "CURRENTYEAR");
		addI18nAlias("currenttime", "DABARTINISLAIKAS", "CURRENTTIME");
		addI18nAlias("currenthour", "DABARTINĖVALANDA", "CURRENTHOUR");
		addI18nAlias("numberofpages", "PUSLAPIŲSKAIČIUS", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "STRAIPSNIŲSKAIČIUS", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "FAILŲSKAIČIUS", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "NAUDOTOJŲSKAIČIUS", "NUMBEROFUSERS");
		addI18nAlias("numberofedits", "KEITIMŲSKAIČIUS", "NUMBEROFEDITS");
		addI18nAlias("img_thumbnail", "miniatiūra", "mini", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "miniatiūra=$1", "mini=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "dešinėje", "right");
		addI18nAlias("img_left", "kairėje", "left");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://lt.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "lt";
	}
}
