/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class LzzConfig extends TemplateConfig {
	public LzzConfig() {
		addNamespaceAlias(-2, "Medya", "Medya", "Ortam", "Medya");
		addNamespaceAlias(-1, "Doxmeli", "Özel", "Özel");
		addNamespaceAlias(1, "Ğarğala", "Tartışma", "Tartışma");
		addNamespaceAlias(2, "Maxmare", "Kullanıcı", "Kullanıcı");
		addNamespaceAlias(3, "Maxmare_mesaji", "Kullanıcı_mesaj", "Kullanıcı_mesaj");
		addNamespaceAlias(5, "Wikipedia_ğarğala", "Wikipedia_tartışma", "Wikipedia_tartışma");
		addNamespaceAlias(6, "Dosya", "Dosya", "Dosya", "Resim");
		addNamespaceAlias(7, "Dosya_ğarğala", "Dosya_tartışma", "Dosya_tartışma", "Resim_tartışma");
		addNamespaceAlias(8, "MediaWiki", "MediaWiki", "MedyaViki");
		addNamespaceAlias(9, "MediaWiki_ğarğala", "MediaWiki_tartışma", "MediaWiki_tartışma", "MedyaViki_tartışma");
		addNamespaceAlias(10, "Şabloni", "Şablon", "Şablon");
		addNamespaceAlias(11, "Şabloni_ğarğala", "Şablon_tartışma", "Şablon_tartışma");
		addNamespaceAlias(12, "Meşvela", "Yardım", "Yardım");
		addNamespaceAlias(13, "Meşvela_ğarğala", "Yardım_tartışma", "Yardım_tartışma");
		addNamespaceAlias(14, "Kʼatʼegori", "Kategori", "Kategori");
		addNamespaceAlias(15, "Kʼatʼegori_ğarğala", "Kategori_tartışma", "Kategori_tartışma");

		addI18nCIAlias("redirect", "#YÖNLENDİRME", "#YÖNLENDİR", "#REDIRECT");
		addI18nCIAlias("notoc", "__İÇİNDEKİLERYOK__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__GALERİYOK__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__İÇİNDEKİLERZORUNLU__", "__FORCETOC__");
		addI18nCIAlias("toc", "__İÇİNDEKİLER__", "__TOC__");
		addI18nCIAlias("noeditsection", "__DEĞİŞTİRYOK__", "__DÜZENLEMEYOK__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "MEVCUTAY", "MEVCUTAY2", "GÜNCELAY", "GÜNCELAY2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "MEVCUTAY1", "GÜNCELAY1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "MEVCUTAYADI", "GÜNCELAYADI", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "MEVCUTAYADIİYELİK", "GÜNCELAYADIİYELİK", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "MEVCUTAYKISALTMASI", "GÜNCELAYKISALTMASI", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "MEVCUTGÜN", "GÜNCELGÜN", "CURRENTDAY");
		addI18nAlias("currentday2", "MEVCUTGÜN2", "GÜNCELGÜN2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "MEVCUTGÜNADI", "GÜNCELGÜNADI", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "MEVCUTYIL", "GÜNCELYIL", "CURRENTYEAR");
		addI18nAlias("currenttime", "MEVCUTZAMAN", "GÜNCELZAMAN", "CURRENTTIME");
		addI18nAlias("currenthour", "MEVCUTSAAT", "GÜNCELSAAT", "CURRENTHOUR");
		addI18nAlias("localmonth", "YERELAY", "YERELAY2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "YERELAY1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "YERELAYADI", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "YERELAYADIİYELİK", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "YERELAYKISALTMASI", "LOCALMONTHABBREV");
		addI18nAlias("localday", "YERELGÜN", "LOCALDAY");
		addI18nAlias("localday2", "YERELGÜN2", "LOCALDAY2");
		addI18nAlias("localdayname", "YERELGÜNADI", "LOCALDAYNAME");
		addI18nAlias("localyear", "YERELYIL", "LOCALYEAR");
		addI18nAlias("localtime", "YERELZAMAN", "LOCALTIME");
		addI18nAlias("localhour", "YERELSAAT", "LOCALHOUR");
		addI18nAlias("numberofpages", "SAYFASAYISI", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "MADDESAYISI", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "DOSYASAYISI", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "KULLANICISAYISI", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "AKTİFKULLANICISAYISI", "ETKİNKULLANICISAYISI", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "DEĞİŞİKLİKSAYISI", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "GÖRÜNTÜLEMESAYISI", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "SAYFAADI", "PAGENAME");
		addI18nAlias("pagenamee", "SAYFAADIU", "PAGENAMEE");
		addI18nAlias("namespace", "ADALANI", "İSİMALANI", "NAMESPACE");
		addI18nAlias("namespacee", "ADALANIU", "İSİMALANIU", "NAMESPACEE");
		addI18nAlias("namespacenumber", "ADALANINUMARASI", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "TARTIŞMAALANI", "TARTIŞMABOŞLUĞU", "TALKSPACE");
		addI18nAlias("talkspacee", "TARTIŞMAALANIU", "TARTIŞMABOŞLUĞUU", "TALKSPACEE");
		addI18nAlias("subjectspace", "KONUALANI", "MADDEALANI", "KONUBOŞLUĞU", "MADDEBOŞLUĞU", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "KONUALANIU", "MADDEALANIU", "KONUBOŞLUĞUU", "MADDEBOŞLUĞUU", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "TAMSAYFAADI", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "TAMSAYFAADIU", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "ALTSAYFAADI", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "ALTSAYFAADIU", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "ÜSTSAYFAADI", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "ÜSTSAYFAADIU", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "TARTIŞMASAYFASIADI", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "TARTIŞMASAYFASIADIU", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "KONUSAYFASIADI", "MADDESAYFASIADI", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "KONUSAYFASIADIU", "MADDESAYFASIADIU", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "MSJ:", "İLT:", "MSG:");
		addI18nCIAlias("subst", "YK:", "YERİNEKOY:", "KOPYALA:", "AKTAR:", "YAPIŞTIR:", "SUBST:");
		addI18nCIAlias("safesubst", "GÜVENLİYERİNEKOY:", "GÜVENLİKOPYALA:", "GÜVENLİAKTAR:", "GÜVENLİYAPIŞTIR:", "SAFESUBST:");
		addI18nCIAlias("msgnw", "MSJYN:", "İLTYN:", "MSGNW:");
		addI18nAlias("img_thumbnail", "küçükresim", "küçük", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "küçükresim=$1", "küçük=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "sağ", "right");
		addI18nAlias("img_left", "sol", "left");
		addI18nAlias("img_none", "yok", "none");
		addI18nAlias("img_width", "$1pik", "$1piksel", "$1px");
		addI18nAlias("img_center", "orta", "center", "centre");
		addI18nAlias("img_framed", "çerçeveli", "çerçeve", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "çerçevesiz", "frameless");
		addI18nAlias("img_page", "sayfa=$1", "sayfa $1", "page=$1", "page $1");
		addI18nAlias("img_upright", "dikey", "dikey=$1", "dikey $1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "sınır", "border");
		addI18nAlias("img_baseline", "tabançizgisi", "altçizgi", "baseline");
		addI18nAlias("img_sub", "alt", "sub");
		addI18nAlias("img_super", "üst", "üs", "super", "sup");
		addI18nAlias("img_top", "tavan", "tepe", "top");
		addI18nAlias("img_text_top", "metin-tavan", "metin-tepe", "text-top");
		addI18nAlias("img_middle", "merkez", "middle");
		addI18nAlias("img_bottom", "taban", "bottom");
		addI18nAlias("img_text_bottom", "metin-taban", "text-bottom");
		addI18nAlias("img_link", "bağlantı=$1", "link=$1");
		addI18nAlias("img_class", "sınıf=$1", "class=$1");
		addI18nCIAlias("int", "İNT:", "INT:");
		addI18nAlias("sitename", "SİTEADI", "SITENAME");
		addI18nCIAlias("ns", "AA:", "AB:", "NS:");
		addI18nCIAlias("nse", "AAU:", "ABU:", "NSE:");
		addI18nCIAlias("localurl", "YERELURL:", "LOCALURL:");
		addI18nCIAlias("localurle", "YERELURLU:", "LOCALURLE:");
		addI18nCIAlias("articlepath", "MADDEYOLU", "ARTICLEPATH");
		addI18nCIAlias("pageid", "SAYFANO", "PAGEID");
		addI18nCIAlias("server", "SUNUCU", "SERVER");
		addI18nCIAlias("servername", "SUNUCUADI", "SERVERNAME");
		addI18nCIAlias("scriptpath", "BETİKYOLU", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "BİÇEMYOLU", "STYLEPATH");
		addI18nCIAlias("grammar", "DİLBİLGİSİ:", "GRAMER:", "GRAMMAR:");
		addI18nCIAlias("gender", "CİNSİYET:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__BAŞLIKDÖNÜŞÜMÜYOK__", "__BDY__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__İÇERİKDÖNÜŞÜMÜYOK__", "__İDY__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "MEVCUTHAFTA", "GÜNCELHAFTA", "CURRENTWEEK");
		addI18nAlias("currentdow", "MEVCUTHAFTANINGÜNÜ", "GÜNCELHAFTANINGÜNÜ", "CURRENTDOW");
		addI18nAlias("localweek", "YERELHAFTA", "LOCALWEEK");
		addI18nAlias("localdow", "YERELHAFTANINGÜNÜ", "LOCALDOW");
		addI18nAlias("revisionid", "SÜRÜMNU", "SÜRÜMNO", "REVİZYONNU", "REVİZYONNO", "REVISIONID");
		addI18nAlias("revisionday", "SÜRÜMGÜNÜ", "REVISIONDAY");
		addI18nAlias("revisionday2", "SÜRÜMGÜNÜ2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "SÜRÜMAYI", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "SÜRÜMAYI1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "SÜRÜMYILI", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "SÜRÜMZAMANBİLGİSİ", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "SÜRÜMKULLANICI", "REVISIONUSER");
		addI18nCIAlias("plural", "ÇOĞUL:", "PLURAL:");
		addI18nCIAlias("fullurl", "TAMURL:", "FULLURL:");
		addI18nCIAlias("fullurle", "TAMURLU:", "FULLURLE:");
		addI18nCIAlias("canonicalurl", "KURALLIURL:", "CANONICALURL:");
		addI18nCIAlias("canonicalurle", "KURALLIURLU:", "CANONICALURLE:");
		addI18nCIAlias("lcfirst", "KHİLK:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "BHİLK:", "UCFIRST:");
		addI18nCIAlias("lc", "KH:", "LC:");
		addI18nCIAlias("uc", "BH:", "UC:");
		addI18nCIAlias("raw", "HAM:", "RAW:");
		addI18nAlias("displaytitle", "BAŞLIKGÖSTER", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "__YENİBAŞLIKBAĞLANTISI__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__YENİBAŞLIKBAĞLANTISIYOK__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "MEVCUTSÜRÜM", "GÜNCELSÜRÜM", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "URLKODLAMA:", "URLENCODE:");
		addI18nCIAlias("anchorencode", "ÇENGELKODLAMA:", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "MEVCUTZAMANBİLGİSİ", "GÜNCELZAMANBİLGİSİ", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "YERELZAMANBİLGİSİ", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "YÖNİŞARETİ:", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#DİL:", "#LİSAN:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "İÇERİKDİLİ", "İÇERİKLİSANI", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "İSİMALANINDAKİSAYFALAR", "İADAKİSAYFALAR", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "HİZMETLİSAYISI", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "BİÇİMNUM", "FORMATNUM");
		addI18nCIAlias("padleft", "DOLSOL", "PADLEFT");
		addI18nCIAlias("padright", "DOLSAĞ", "PADRIGHT");
		addI18nCIAlias("special", "özel", "special");
		addI18nCIAlias("speciale", "özelu", "speciale");
		addI18nAlias("defaultsort", "VARSAYILANSIRALA:", "VARSAYILANSIRALAMAANAHTARI:", "VARSAYILANKATEGORİSIRALA:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "DOSYAYOLU:", "DOSYA_YOLU:", "FILEPATH:");
		addI18nCIAlias("tag", "etiket", "tag");
		addI18nAlias("hiddencat", "__GİZLİKAT__", "__GİZLİKATEGORİ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "KATEGORİDEKİSAYFALAR", "KATTAKİSAYFALAR", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "SAYFABOYUTU", "PAGESIZE");
		addI18nAlias("index", "__DİZİN__", "__ENDEKS__", "__INDEX__");
		addI18nAlias("noindex", "__DİZİNYOK__", "__ENDEKSYOK__", "__NOINDEX__");
		addI18nAlias("numberingroup", "GRUPTAKİSAYI", "GRUBUNSAYISI", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__STATİKYÖNLENDİRME__", "__SABİTYÖNLENDİRME__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "KORUMASEVİYESİ", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "biçimtarih", "tarihbiçimi", "formattarihi", "tarihformatı", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "YOL", "PATH");
		addI18nCIAlias("url_wiki", "VİKİ", "WIKI");
		addI18nCIAlias("url_query", "SORGU", "QUERY");
		addI18nCIAlias("defaultsort_noerror", "hatayok", "hatasız", "noerror");
		addI18nCIAlias("pagesincategory_all", "tüm", "all");
		addI18nCIAlias("pagesincategory_pages", "sayfalar", "pages");
		addI18nCIAlias("pagesincategory_subcats", "altkategoriler", "subcats");
		addI18nCIAlias("pagesincategory_files", "dosyalar", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://lzz.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "lzz";
	}
}
