/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class MdfConfig extends TemplateConfig {
	public MdfConfig() {
		addNamespaceAlias(-2, "Медиа");
		addNamespaceAlias(-1, "Башка", "Служебная");
		addNamespaceAlias(1, "Корхнема", "Обсуждение");
		addNamespaceAlias(2, "Тиись", "Участник");
		addNamespaceAlias(3, "Тиись_корхнема", "Обсуждение_участника");
		addNamespaceAlias(5, "Wikipedia_корхнема", "Обсуждение_{{GRAMMAR:genitive|Wikipedia}}");
		addNamespaceAlias(6, "Няйф", "Изображение");
		addNamespaceAlias(7, "Няйф_корхнема", "Обсуждение_изображения");
		addNamespaceAlias(8, "МедиаВики", "MediaWiki");
		addNamespaceAlias(9, "МедиаВики_корхнема", "Обсуждение_MediaWiki");
		addNamespaceAlias(10, "Шаблон", "Шаблон");
		addNamespaceAlias(11, "Шаблон_корхнема", "Обсуждение_шаблона");
		addNamespaceAlias(12, "Лезкс", "Справка");
		addNamespaceAlias(13, "Лезкс_корхнема", "Обсуждение_справки");
		addNamespaceAlias(14, "Категорие", "Категория");
		addNamespaceAlias(15, "Категорие_корхнема", "Обсуждение_категории");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://mdf.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "mdf";
	}
}
