/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class MlConfig extends TemplateConfig {
	public MlConfig() {
		addNamespaceAlias(-2, "മീഡിയ");
		addNamespaceAlias(-1, "പ്രത്യേകം", "പ്രത്യേ");
		addNamespaceAlias(1, "സംവാദം", "സം");
		addNamespaceAlias(2, "ഉപയോക്താവ്", "അംഗം", "ഉ");
		addNamespaceAlias(3, "ഉപയോക്താവിന്റെ_സംവാദം", "അംഗങ്ങളുടെ സംവാദം", "ഉസം");
		addNamespaceAlias(5, "Wikipedia_സംവാദം");
		addNamespaceAlias(6, "പ്രമാണം", "ചി", "ചിത്രം", "പ്ര");
		addNamespaceAlias(7, "പ്രമാണത്തിന്റെ_സംവാദം", "ചിസം", "ചിത്രത്തിന്റെ_സംവാദം", "പ്രസം");
		addNamespaceAlias(8, "മീഡിയവിക്കി", "മീ");
		addNamespaceAlias(9, "മീഡിയവിക്കി_സംവാദം", "മീസം");
		addNamespaceAlias(10, "ഫലകം", "ഫ");
		addNamespaceAlias(11, "ഫലകത്തിന്റെ_സംവാദം", "ഫസം");
		addNamespaceAlias(12, "സഹായം", "സ");
		addNamespaceAlias(13, "സഹായത്തിന്റെ_സംവാദം", "സസം");
		addNamespaceAlias(14, "വർഗ്ഗം", "വി", "വ", "വിഭാഗം", "വർഗ്ഗം");
		addNamespaceAlias(15, "വർഗ്ഗത്തിന്റെ_സംവാദം", "വിസം", "വസം", "വിഭാഗത്തിന്റെ_സംവാദം", "വർഗ്ഗത്തിന്റെ_സംവാദം");

		addI18nCIAlias("redirect", "#തിരിച്ചുവിടുക", "#തിരിച്ചുവിടൽ", "#REDIRECT");
		addI18nCIAlias("notoc", "__ഉള്ളടക്കംവേണ്ട__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__ചിത്രസഞ്ചയംവേണ്ട__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__ഉള്ളടക്കംഇടുക__", "__FORCETOC__");
		addI18nCIAlias("toc", "__ഉള്ളടക്കം__", "__TOC__");
		addI18nCIAlias("noeditsection", "__സംശോധിക്കേണ്ട__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "ഈമാസം", "ഈമാസം2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "ഈമാസം1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "ഈമാസത്തിന്റെപേര്‌", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "ഈമാസത്തിന്റെപേരുസൃഷ്ടിക്കുക", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "ഈമാസത്തിന്റെപേര്‌സംഗ്രഹം", "ഈമാസത്തിന്റെപേര്‌ചുരുക്കം", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "ഈദിവസം", "CURRENTDAY");
		addI18nAlias("currentday2", "ഈദിവസം2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "ഈദിവസത്തിന്റെപേര്‌", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "ഈവർഷം", "CURRENTYEAR");
		addI18nAlias("currenttime", "ഈസമയം", "CURRENTTIME");
		addI18nAlias("currenthour", "ഈമണിക്കൂർ", "CURRENTHOUR");
		addI18nAlias("localmonth", "പ്രാദേശികമാസം", "പ്രാദേശികമാസം2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "പ്രാദേശികമാസം1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "പ്രാദേശികമാസത്തിന്റെപേര്‌", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "പ്രാദേശികമാസത്തിന്റെപേരുസൃഷ്ടിക്കുക", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "പ്രാദേശികമാസത്തിന്റെപേര്‌സംഗ്രഹം", "പ്രാദേശികമാസത്തിന്റെപേര്‌ചുരുക്കം", "LOCALMONTHABBREV");
		addI18nAlias("localday", "പ്രാദേശികദിവസം", "LOCALDAY");
		addI18nAlias("localday2", "പ്രാദേശികദിവസം2", "LOCALDAY2");
		addI18nAlias("localdayname", "പ്രാദേശികദിവസത്തിന്റെപേര്‌", "LOCALDAYNAME");
		addI18nAlias("localyear", "പ്രാദേശികവർഷം", "LOCALYEAR");
		addI18nAlias("localtime", "പ്രാദേശികസമയം", "LOCALTIME");
		addI18nAlias("localhour", "പ്രാദേശികമണിക്കൂർ", "LOCALHOUR");
		addI18nAlias("numberofpages", "താളുകളുടെയെണ്ണം", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "ലേഖനങ്ങളുടെയെണ്ണം", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "പ്രമാണങ്ങളുടെയെണ്ണം", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "ഉപയോക്താക്കളുടെയെണ്ണം", "അംഗങ്ങളുടെയെണ്ണം", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "സജീവോപയാക്താക്കളുടെയെണ്ണം", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "തിരുത്തലുകളുടെണ്ണം", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "എടുത്തുനോക്കലുകളുടെണ്ണം", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "താളിന്റെപേര്‌", "PAGENAME");
		addI18nAlias("pagenamee", "താളിന്റെപേര്‌സമഗ്രം", "PAGENAMEE");
		addI18nAlias("namespace", "നാമമേഖല", "NAMESPACE");
		addI18nAlias("namespacee", "നാമമേഖലസമഗ്രം", "NAMESPACEE");
		addI18nAlias("namespacenumber", "നാമമേഖലാസംഖ്യ", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "സംവാദമേഖല", "TALKSPACE");
		addI18nAlias("talkspacee", "സംവാദമേഖലസമഗ്രം", "TALKSPACEE");
		addI18nAlias("subjectspace", "വിഷയമേഖല", "ലേഖനമേഖല", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "വിഷയമേഖലസമഗ്രം", "ലേഖനമേഖലസമഗ്രം", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "താളിന്റെമുഴുവൻപേര്‌", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "താളിന്റെമുഴുവൻപേര്സമഗ്രം", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "അനുബന്ധതാളിന്റെപേര്‌", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "അനുബന്ധതാളിന്റെപേര്സമഗ്രം", "SUBPAGENAMEE");
		addI18nAlias("rootpagename", "മൂലതാളിന്റെപേര്", "ROOTPAGENAME");
		addI18nAlias("rootpagenamee", "മൂലതാളിന്റെപേര്‌സമഗ്രം", "ROOTPAGENAMEE");
		addI18nAlias("basepagename", "അടിസ്ഥാനതാളിന്റെപേര്‌", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "അടിസ്ഥാനതാളിന്റെപേര്‌സമഗ്രം", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "സംവാദതാളിന്റെപേര്‌", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "സംവാദതാളിന്റെപേര്‌സമഗ്രം", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "ലേഖനതാളിന്റെപേര്‌", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "ലേഖനതാളിന്റെപേര്‌സമഗ്രം", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "സന്ദേശം:", "MSG:");
		addI18nCIAlias("subst", "ബദൽ:", "ഉൾപ്പെടുത്തൽ:", "SUBST:");
		addI18nCIAlias("safesubst", "സംരക്ഷിതബദൽ:", "സംരക്ഷിതയുൾപ്പെടുത്തൽ:", "SAFESUBST:");
		addI18nCIAlias("msgnw", "മൂലരൂപം:", "MSGNW:");
		addI18nAlias("img_thumbnail", "ലഘുചിത്രം", "ലഘു", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "ലഘുചിത്രം=$1", "ലഘു=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "വലത്ത്‌", "വലത്‌", "right");
		addI18nAlias("img_left", "ഇടത്ത്‌", "ഇടത്‌", "left");
		addI18nAlias("img_none", "ശൂന്യം", "none");
		addI18nAlias("img_width", "$1ബിന്ദു", "$1px");
		addI18nAlias("img_center", "നടുവിൽ", "നടുക്ക്‌", "center", "centre");
		addI18nAlias("img_framed", "ചട്ടം", "ചട്ടത്തിൽ", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "ചട്ടരഹിതം", "frameless");
		addI18nAlias("img_lang", "ഭാഷ=$1", "lang=$1");
		addI18nAlias("img_page", "താൾ=$1", "താൾ_$1", "page=$1", "page $1");
		addI18nAlias("img_upright", "നേരേകുത്തനെ", "നേരേകുത്തനെ=$1", "നേരേകുത്തനെ_$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "അതിർവര", "border");
		addI18nAlias("img_baseline", "താഴെയുള്ളവര", "baseline");
		addI18nAlias("img_sub", "കീഴെയെഴുത്ത്", "sub");
		addI18nAlias("img_super", "മേലേയെഴുത്ത്", "super", "sup");
		addI18nAlias("img_top", "മേലെ", "top");
		addI18nAlias("img_text_top", "എഴുത്ത്-മേലെ", "text-top");
		addI18nAlias("img_middle", "മദ്ധ്യം", "middle");
		addI18nAlias("img_bottom", "താഴെ", "bottom");
		addI18nAlias("img_text_bottom", "എഴുത്ത്-താഴെ", "text-bottom");
		addI18nAlias("img_link", "കണ്ണി=$1", "link=$1");
		addI18nAlias("img_alt", "പകരം=$1", "alt=$1");
		addI18nAlias("img_class", "ശ്രേണി=$1", "class=$1");
		addI18nCIAlias("int", "സമ്പർക്കം:", "INT:");
		addI18nAlias("sitename", "സൈറ്റിന്റെപേര്", "SITENAME");
		addI18nCIAlias("ns", "നാമേ:", "NS:");
		addI18nCIAlias("nse", "നാമേസ:", "NSE:");
		addI18nCIAlias("localurl", "ലോക്കൽയുആർഎൽ:", "LOCALURL:");
		addI18nCIAlias("localurle", "ലോക്കൽയുആർഎൽഇ:", "LOCALURLE:");
		addI18nCIAlias("articlepath", "ലേഖനപഥം", "ARTICLEPATH");
		addI18nCIAlias("pageid", "താൾഐ‌ഡി", "PAGEID");
		addI18nCIAlias("server", "സെർവർ", "SERVER");
		addI18nCIAlias("servername", "സെർവറിന്റെപേര്", "SERVERNAME");
		addI18nCIAlias("scriptpath", "സ്ക്രിപ്റ്റ്പഥം", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "സ്റ്റൈൽപഥം", "STYLEPATH");
		addI18nCIAlias("grammar", "വ്യാകരണം:", "GRAMMAR:");
		addI18nCIAlias("gender", "ലിംഗം:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__തലക്കെട്ട്മാറ്റേണ്ട__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__ഉള്ളടക്കംമാറ്റേണ്ട__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "ആഴ്ച", "ആഴ്‌ച", "CURRENTWEEK");
		addI18nAlias("currentdow", "ദിവസത്തിന്റെപേര്‌അക്കത്തിൽ", "CURRENTDOW");
		addI18nAlias("localweek", "പ്രാദേശികആഴ്ച", "പ്രാദേശികആഴ്‌ച", "LOCALWEEK");
		addI18nAlias("localdow", "ആഴ്ചയുടെപേര്‌അക്കത്തിൽ", "ആഴ്‌ചയുടെപേര്‌അക്കത്തിൽ", "LOCALDOW");
		addI18nAlias("revisionid", "തിരുത്തൽഅടയാളം", "REVISIONID");
		addI18nAlias("revisionday", "തിരുത്തിയദിവസം", "തിരുത്തിയദിനം", "REVISIONDAY");
		addI18nAlias("revisionday2", "തിരുത്തിയദിവസം2", "തിരുത്തിയദിനം2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "തിരുത്തിയമാസം", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "തിരുത്തിയമാസം1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "തിരുത്തിയവർഷം", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "തിരുത്തിയസമയമുദ്ര", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "അവസാനംതിരുത്തിയയാൾ", "REVISIONUSER");
		addI18nCIAlias("plural", "ബഹുവചനം:", "PLURAL:");
		addI18nCIAlias("fullurl", "പൂർണ്ണവിലാസം:", "FULLURL:");
		addI18nCIAlias("fullurle", "പൂർണ്ണവിലാസംസമഗ്രം:", "FULLURLE:");
		addI18nCIAlias("canonicalurl", "കാനോനിക്കൽവിലാസം:", "CANONICALURL:");
		addI18nCIAlias("canonicalurle", "കാനോനിക്കൽവിലാസംസമഗ്രം:", "CANONICALURLE:");
		addI18nCIAlias("raw", "അസംസ്കൃതം:", "RAW:");
		addI18nAlias("displaytitle", "ശീർഷകംപ്രദർശിപ്പിക്കുക", "തലക്കെട്ട്പ്രദർശിപ്പിക്കുക", "DISPLAYTITLE");
		addI18nAlias("rawsuffix", "വ", "R");
		addI18nAlias("newsectionlink", "__പുതിയവിഭാഗംകണ്ണി__", "__പുതിയഖണ്ഡിക്കണ്ണി__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__പുതിയവിഭാഗംകണ്ണിവേണ്ട__", "__പുതിയഖണ്ഡിക്കണ്ണിവേണ്ട__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "ഈപതിപ്പ്", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "വിലാസഗൂഢീകരണം:", "URLENCODE:");
		addI18nAlias("currenttimestamp", "സമയമുദ്ര", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "പ്രാദേശികസമയമുദ്ര", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "ദിശാസൂചിക", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#ഭാഷ:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "ഉള്ളടക്കഭാഷ", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "നാമമേഖലയിലുള്ളതാളുകൾ", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "കാര്യനിർവ്വാഹകരുടെഎണ്ണം", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "ദശാംശഘടന", "സംഖ്യാഘടന", "FORMATNUM");
		addI18nCIAlias("padleft", "ഇടത്ത്നിറക്കുക", "PADLEFT");
		addI18nCIAlias("padright", "വലത്ത്നിറക്കുക", "PADRIGHT");
		addI18nCIAlias("special", "പ്രത്യേകം", "special");
		addI18nCIAlias("speciale", "സവിശേഷം", "speciale");
		addI18nAlias("defaultsort", "സ്വതവേയുള്ളക്രമപ്പെടുത്തൽ:", "സ്വതവേയുള്ളക്രമപ്പെടുത്തൽചാവി:", "സ്വതവേയുള്ളവർഗ്ഗക്രമപ്പെടുത്തൽ:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "പ്രമാണപഥം:", "FILEPATH:");
		addI18nCIAlias("tag", "റ്റാഗ്", "ടാഗ്", "tag");
		addI18nAlias("hiddencat", "‌‌__മറഞ്ഞിരിക്കുംവർഗ്ഗം__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "വർഗ്ഗത്തിലുള്ളതാളുകൾ", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "താൾവലിപ്പം", "PAGESIZE");
		addI18nAlias("index", "‌‌__സൂചിക__", "__INDEX__");
		addI18nAlias("noindex", "__സൂചികവേണ്ട__", "__NOINDEX__");
		addI18nAlias("numberingroup", "ഗണത്തിലെയെണ്ണം", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "_സ്ഥിരസ്ഥിതതിരിച്ചുവിടൽ_", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "സംരക്ഷണതലം", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "ദിനരേഖീകരണരീതി", "ദിവസരേഖീകരണരീതി", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "പഥം", "PATH");
		addI18nCIAlias("url_wiki", "വിക്കി", "WIKI");
		addI18nCIAlias("url_query", "ക്വറി", "QUERY");
		addI18nCIAlias("defaultsort_noerror", "പിഴവില്ല", "noerror");
		addI18nCIAlias("defaultsort_noreplace", "മാറ്റേണ്ടതില്ല", "noreplace");
		addI18nCIAlias("pagesincategory_all", "എല്ലാം", "all");
		addI18nCIAlias("pagesincategory_pages", "താളുകൾ", "pages");
		addI18nCIAlias("pagesincategory_subcats", "ഉപവർഗ്ഗങ്ങൾ", "subcats");
		addI18nCIAlias("pagesincategory_files", "പ്രമാണങ്ങൾ", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ml.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ml";
	}
}
