/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class MnConfig extends TemplateConfig {
	public MnConfig() {
		addNamespaceAlias(-2, "Медиа");
		addNamespaceAlias(-1, "Тусгай");
		addNamespaceAlias(1, "Хэлэлцүүлэг");
		addNamespaceAlias(2, "Хэрэглэгч");
		addNamespaceAlias(3, "Хэрэглэгчийн_яриа");
		addNamespaceAlias(5, "Wikipedia-н_хэлэлцүүлэг");
		addNamespaceAlias(6, "Файл", "Зураг");
		addNamespaceAlias(7, "Файлын_хэлэлцүүлэг", "Зургийн_хэлэлцүүлэг");
		addNamespaceAlias(8, "МедиаВики");
		addNamespaceAlias(9, "МедиаВикигийн_хэлэлцүүлэг");
		addNamespaceAlias(10, "Загвар");
		addNamespaceAlias(11, "Загварын_хэлэлцүүлэг");
		addNamespaceAlias(12, "Тусламж");
		addNamespaceAlias(13, "Тусламжийн_хэлэлцүүлэг");
		addNamespaceAlias(14, "Ангилал");
		addNamespaceAlias(15, "Ангиллын_хэлэлцүүлэг");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://mn.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "mn";
	}
}
