/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class MyvConfig extends TemplateConfig {
	public MyvConfig() {
		addNamespaceAlias(-2, "Медия", "Медиа");
		addNamespaceAlias(-1, "Башка тевень", "Служебная");
		addNamespaceAlias(1, "Кортамо", "Обсуждение");
		addNamespaceAlias(2, "Теиця", "Участник", "Участник", "Участница");
		addNamespaceAlias(3, "Теицянь кортамось", "Обсуждение_участника", "Обсуждение_участника", "Обсуждение_участницы");
		addNamespaceAlias(5, "Wikipedia кортамось", "Обсуждение_{{GRAMMAR:genitive|Wikipedia}}");
		addNamespaceAlias(6, "Артовкс", "Файл", "Изображение");
		addNamespaceAlias(7, "Артовксто кортамось", "Обсуждение_файла", "Обсуждение_изображения");
		addNamespaceAlias(8, "MediaWiki", "MediaWiki");
		addNamespaceAlias(9, "MediaWiki-нь кортамось", "Обсуждение_MediaWiki");
		addNamespaceAlias(10, "ЛопаПарцун", "Шаблон");
		addNamespaceAlias(11, "ЛопаПарцундо кортамось", "Обсуждение_шаблона");
		addNamespaceAlias(12, "Лезкс", "Справка");
		addNamespaceAlias(13, "Лезкстэ кортамось", "Обсуждение_справки");
		addNamespaceAlias(14, "Категория", "Категория");
		addNamespaceAlias(15, "Категориядо кортамось", "Обсуждение_категории");

		addI18nAlias("currentmonth", "МОЛИЦЯКОВ", "ТЕКУЩИЙ_МЕСЯЦ", "ТЕКУЩИЙ_МЕСЯЦ_2", "CURRENTMONTH", "CURRENTMONTH2", "Array");
		addI18nAlias("currentmonthname", "МОЛИЦЯКОВЛЕМ", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА", "CURRENTMONTHNAME", "Array");
		addI18nAlias("currentmonthnamegen", "МОЛИЦЯКОВЛЕМГЕН", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_РОД", "CURRENTMONTHNAMEGEN", "Array");
		addI18nAlias("currentmonthabbrev", "МОЛИЦЯКОВКИРЬТЯНЬХВОРМА", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_АБР", "CURRENTMONTHABBREV", "Array");
		addI18nAlias("currentday", "МОЛИЦЯЧЫ", "ТЕКУЩИЙ_ДЕНЬ", "CURRENTDAY", "Array");
		addI18nAlias("currentday2", "МОЛИЦЯЧЫ2", "ТЕКУЩИЙ_ДЕНЬ_2", "CURRENTDAY2", "Array");
		addI18nAlias("currentdayname", "МОЛИЦЯЧЫЛЕМ", "НАЗВАНИЕ_ТЕКУЩЕГО_ДНЯ", "CURRENTDAYNAME", "Array");
		addI18nAlias("currentyear", "МОЛИЦЯИЕ", "ТЕКУЩИЙ_ГОД", "CURRENTYEAR", "Array");
		addI18nAlias("currenttime", "МОЛИЦЯШКА", "ТЕКУЩЕЕ_ВРЕМЯ", "CURRENTTIME", "Array");
		addI18nAlias("currenthour", "МОЛИЦЯЦЯС", "ТЕКУЩИЙ_ЧАС", "CURRENTHOUR", "Array");
		addI18nAlias("localmonth", "ТЕСКЭНЬКОВ", "МЕСТНЫЙ_МЕСЯЦ", "МЕСТНЫЙ_МЕСЯЦ_2", "LOCALMONTH", "LOCALMONTH2", "Array");
		addI18nAlias("localmonthname", "ТЕСКЭНЬКОВЛЕМ", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА", "LOCALMONTHNAME", "Array");
		addI18nAlias("localmonthnamegen", "ТЕСКЭНЬКОВЛЕМГЕН", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_РОД", "LOCALMONTHNAMEGEN", "Array");
		addI18nAlias("localmonthabbrev", "ТЕСКЭНЬКОВКИРЬТЯНЬХВОРМА", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_АБР", "LOCALMONTHABBREV", "Array");
		addI18nAlias("localday", "ТЕСКЭНЬЧЫ", "МЕСТНЫЙ_ДЕНЬ", "LOCALDAY", "Array");
		addI18nAlias("localday2", "ТЕСКЭНЬЧЫ2", "МЕСТНЫЙ_ДЕНЬ_2", "LOCALDAY2", "Array");
		addI18nAlias("localdayname", "ТЕСКЭНЬЧЫЛЕМ", "НАЗВАНИЕ_МЕСТНОГО_ДНЯ", "LOCALDAYNAME", "Array");
		addI18nAlias("localyear", "ТЕСКЭНЬИЕ", "МЕСТНЫЙ_ГОД", "LOCALYEAR", "Array");
		addI18nAlias("localtime", "ТЕСКЭНЬШКА", "МЕСТНОЕ_ВРЕМЯ", "LOCALTIME", "Array");
		addI18nAlias("localhour", "ТЕСКЭНЬЦЯС", "МЕСТНЫЙ_ЧАС", "LOCALHOUR", "Array");
		addI18nAlias("numberofpages", "ЗЯРОЛОПАТ", "КОЛИЧЕСТВО_СТРАНИЦ", "NUMBEROFPAGES", "Array");
		addI18nAlias("numberofarticles", "ЗЯРОСЁРМАДОВКСТ", "КОЛИЧЕСТВО_СТАТЕЙ", "NUMBEROFARTICLES", "Array");
		addI18nAlias("numberoffiles", "ЗЯРОФАЙЛАТ", "КОЛИЧЕСТВО_ФАЙЛОВ", "NUMBEROFFILES", "Array");
		addI18nAlias("numberofusers", "ЗЯРОТЕИЦЯТ", "КОЛИЧЕСТВО_УЧАСТНИКОВ", "NUMBEROFUSERS", "Array");
		addI18nAlias("numberofedits", "ЗЯРОВИТНЕМАТПЕТНЕМАТ", "КОЛИЧЕСТВО_ПРАВОК", "NUMBEROFEDITS", "Array");
		addI18nAlias("pagename", "ЛОПАЛЕМ", "НАЗВАНИЕ_СТРАНИЦЫ", "PAGENAME", "Array");
		addI18nAlias("namespace", "ЛЕМПОТМО", "ПРОСТРАНСТВО_ИМЁН", "NAMESPACE", "Array");
		addI18nAlias("talkspace", "КОРТАМОПОТМО", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ", "TALKSPACE", "Array");
		addI18nAlias("fullpagename", "ЛОПАЛЕМКУВАКАСТО", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ", "FULLPAGENAME", "Array");
		addI18nAlias("talkpagename", "КОРТАМОЛОПАЛЕМ", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ", "TALKPAGENAME", "Array");
		addI18nCIAlias("msg", "ПАЧТЯМНЭ:", "СООБЩЕНИЕ:", "СООБЩ:", "MSG:", "Array");
		addI18nAlias("img_thumbnail", "кенжешка", "мини", "миниатюра", "thumbnail", "thumb", "Array");
		addI18nAlias("img_right", "вить_кедь", "справа", "right", "Array");
		addI18nAlias("img_left", "керш_кедь", "слева", "left", "Array");
		addI18nAlias("img_none", "вейкеяк_арась", "без", "none", "Array");
		addI18nAlias("img_center", "куншкасо", "центр", "center", "centre", "Array");
		addI18nAlias("img_framed", "кундсо", "обрамить", "framed", "enframed", "frame", "Array");
		addI18nAlias("img_frameless", "кундовтомо", "безрамки", "frameless", "Array");
		addI18nAlias("img_page", "лопа=$1", "лопа_$1", "страница=$1", "страница_$1", "страница $1", "page=$1", "page $1", "Array");
		addI18nAlias("img_top", "верькс", "сверху", "top", "Array");
		addI18nAlias("img_text_top", "текст-верькс", "текст-сверху", "text-top", "Array");
		addI18nAlias("img_middle", "куншка", "посередине", "middle", "Array");
		addI18nAlias("img_bottom", "алкс", "снизу", "bottom", "Array");
		addI18nAlias("img_text_bottom", "текст-алкс", "текст-снизу", "text-bottom", "Array");
		addI18nAlias("sitename", "САЙТЛЕМ", "НАЗВАНИЕ_САЙТА", "SITENAME", "Array");
		addI18nCIAlias("gender", "СЫМЕ:", "ПОЛ:", "GENDER:", "Array");
		addI18nAlias("currentweek", "МОЛИЦЯ_ТАРГО", "ТЕКУЩАЯ_НЕДЕЛЯ", "CURRENTWEEK", "Array");
		addI18nAlias("currentdow", "МОЛИЦЯ_ЧИ", "ТЕКУЩИЙ_ДЕНЬ_НЕДЕЛИ", "CURRENTDOW", "Array");
		addI18nAlias("localweek", "ТЕСКЭНЬТАРГО", "МЕСТНАЯ_НЕДЕЛЯ", "LOCALWEEK", "Array");
		addI18nAlias("revisionid", "ЛИЯКСТОМТОМАID", "ИД_ВЕРСИИ", "REVISIONID", "Array");
		addI18nAlias("revisionday", "ЛИЯКСТОМТОМАЧЫ", "ДЕНЬ_ВЕРСИИ", "REVISIONDAY", "Array");
		addI18nAlias("revisionday2", "ЛИЯКСТОМТОМАЧЫ2", "ДЕНЬ_ВЕРСИИ_2", "REVISIONDAY2", "Array");
		addI18nAlias("revisionmonth", "ЛИЯКСТОМТОМАКОВ", "МЕСЯЦ_ВЕРСИИ", "REVISIONMONTH", "Array");
		addI18nAlias("revisionyear", "ЛИЯКСТОМТОМАИЕ", "ГОД_ВЕРСИИ", "REVISIONYEAR", "Array");
		addI18nCIAlias("plural", "ЛАМОНЬЧИСЛА", "МНОЖЕСТВЕННОЕ_ЧИСЛО:", "PLURAL:", "Array");
		addI18nCIAlias("lcfirst", "ВАСЕНЦЕ_ТЕШТЬКЕСЬ_ВИШКИНЕ:", "ПЕРВАЯ_БУКВА_МАЛЕНЬКАЯ:", "LCFIRST:", "Array");
		addI18nCIAlias("ucfirst", "ВАСЕНЦЕ_ТЕШТЬКЕСЬ_ПОКШ:", "ПЕРВАЯ_БУКВА_БОЛЬШАЯ:", "UCFIRST:", "Array");
		addI18nCIAlias("lc", "ВИШКА_ТЕШТЬКЕСЭ:", "МАЛЕНЬКИМИ_БУКВАМИ:", "LC:", "Array");
		addI18nCIAlias("uc", "ПОШК_ТЕШТЬКЕСЭ:", "БОЛЬШИМИ_БУКВАМИ:", "UC:", "Array");
		addI18nCIAlias("raw", "ВЕРЕКСТЭ", "НЕОБРАБ:", "RAW:", "Array");
		addI18nAlias("displaytitle", "НЕВТЕМС_КОНЯКС", "ПОКАЗАТЬ_ЗАГОЛОВОК", "DISPLAYTITLE", "Array");
		addI18nAlias("currentversion", "ТЕВАТЕВЕРСИЯ", "ТЕКУЩАЯ_ВЕРСИЯ", "CURRENTVERSION", "Array");
		addI18nCIAlias("language", "#КЕЛЕСЬ:", "#ЯЗЫК:", "#LANGUAGE:", "Array");
		addI18nAlias("numberofadmins", "ЗЯРОАДМИНТНЭДЕ", "КОЛИЧЕСТВО_АДМИНИСТРАТОРОВ", "NUMBEROFADMINS", "Array");
		addI18nCIAlias("special", "башка_тевень", "служебная", "special", "Array");
		addI18nCIAlias("filepath", "ФАЙЛАНЬКИ", "ПУТЬ_К_ФАЙЛУ:", "FILEPATH:", "Array");
		addI18nAlias("pagesize", "ЛОПАКУВАЛМО", "РАЗМЕР_СТРАНИЦЫ", "PAGESIZE", "Array");
		addI18nCIAlias("url_path", "ЯН", "ПУТЬ", "PATH", "Array");
		addI18nCIAlias("url_wiki", "ВИКИ", "WIKI", "Array");
		addI18nCIAlias("redirect", "#перенаправление", "#перенапр", "#REDIRECT");
		addI18nCIAlias("notoc", "__БЕЗ_ОГЛАВЛЕНИЯ__", "__БЕЗ_ОГЛ__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__БЕЗ_ГАЛЕРЕИ__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__ОБЯЗАТЕЛЬНОЕ_ОГЛАВЛЕНИЕ__", "__ОБЯЗ_ОГЛ__", "__FORCETOC__");
		addI18nCIAlias("toc", "__ОГЛАВЛЕНИЕ__", "__ОГЛ__", "__TOC__");
		addI18nCIAlias("noeditsection", "__БЕЗ_РЕДАКТИРОВАНИЯ_РАЗДЕЛА__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth1", "ТЕКУЩИЙ_МЕСЯЦ_1", "CURRENTMONTH1");
		addI18nAlias("localmonth1", "МЕСТНЫЙ_МЕСЯЦ_1", "LOCALMONTH1");
		addI18nAlias("numberofactiveusers", "КОЛИЧЕСТВО_АКТИВНЫХ_УЧАСТНИКОВ", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofviews", "КОЛИЧЕСТВО_ПРОСМОТРОВ", "NUMBEROFVIEWS");
		addI18nAlias("pagenamee", "НАЗВАНИЕ_СТРАНИЦЫ_2", "PAGENAMEE");
		addI18nAlias("namespacee", "ПРОСТРАНСТВО_ИМЁН_2", "NAMESPACEE");
		addI18nAlias("namespacenumber", "НОМЕР_ПРОСТРАНСТВА_ИМЁН", "NAMESPACENUMBER");
		addI18nAlias("talkspacee", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ_2", "TALKSPACEE");
		addI18nAlias("subjectspace", "ПРОСТРАНСТВО_СТАТЕЙ", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "ПРОСТРАНСТВО_СТАТЕЙ_2", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagenamee", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ_2", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "НАЗВАНИЕ_ПОДСТРАНИЦЫ", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "НАЗВАНИЕ_ПОДСТРАНИЦЫ_2", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ_2", "BASEPAGENAMEE");
		addI18nAlias("talkpagenamee", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ_2", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ_2", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("subst", "ПОДСТАНОВКА:", "ПОДСТ:", "SUBST:");
		addI18nCIAlias("safesubst", "ЗАЩПОДСТ:", "SAFESUBST:");
		addI18nCIAlias("msgnw", "СООБЩ_БЕЗ_ВИКИ:", "MSGNW:");
		addI18nAlias("img_manualthumb", "мини=$1", "миниатюра=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_width", "$1пкс", "$1px");
		addI18nAlias("img_upright", "сверхусправа", "сверхусправа=$1", "сверхусправа $1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "граница", "border");
		addI18nAlias("img_baseline", "основание", "baseline");
		addI18nAlias("img_sub", "под", "sub");
		addI18nAlias("img_super", "над", "super", "sup");
		addI18nAlias("img_link", "ссылка=$1", "link=$1");
		addI18nAlias("img_alt", "альт=$1", "alt=$1");
		addI18nCIAlias("int", "ВНУТР:", "INT:");
		addI18nCIAlias("ns", "ПИ:", "NS:");
		addI18nCIAlias("nse", "ПИК:", "NSE:");
		addI18nCIAlias("localurl", "ЛОКАЛЬНЫЙ_АДРЕС:", "LOCALURL:");
		addI18nCIAlias("localurle", "ЛОКАЛЬНЫЙ_АДРЕС_2:", "LOCALURLE:");
		addI18nCIAlias("articlepath", "ПУТЬ_К_СТАТЬЕ", "ARTICLEPATH");
		addI18nCIAlias("pageid", "ИДЕНТИФИКАТОР_СТРАНИЦЫ", "PAGEID");
		addI18nCIAlias("server", "СЕРВЕР", "SERVER");
		addI18nCIAlias("servername", "НАЗВАНИЕ_СЕРВЕРА", "SERVERNAME");
		addI18nCIAlias("scriptpath", "ПУТЬ_К_СКРИПТУ", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "ПУТЬ_К_СТИЛЮ", "STYLEPATH");
		addI18nCIAlias("grammar", "ПАДЕЖ:", "GRAMMAR:");
		addI18nCIAlias("notitleconvert", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ЗАГОЛОВКА__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ТЕКСТА__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("localdow", "МЕСТНЫЙ_ДЕНЬ_НЕДЕЛИ", "LOCALDOW");
		addI18nAlias("revisionmonth1", "МЕСЯЦ_ВЕРСИИ_1", "REVISIONMONTH1");
		addI18nAlias("revisiontimestamp", "ОТМЕТКА_ВРЕМЕНИ_ВЕРСИИ", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "ВЕРСИЯ_УЧАСТНИКА", "REVISIONUSER");
		addI18nCIAlias("fullurl", "ПОЛНЫЙ_АДРЕС:", "FULLURL:");
		addI18nCIAlias("fullurle", "ПОЛНЫЙ_АДРЕС_2:", "FULLURLE:");
		addI18nAlias("rawsuffix", "Н", "R");
		addI18nAlias("newsectionlink", "__ССЫЛКА_НА_НОВЫЙ_РАЗДЕЛ__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__БЕЗ_ССЫЛКИ_НА_НОВЫЙ_РАЗДЕЛ__", "__NONEWSECTIONLINK__");
		addI18nCIAlias("urlencode", "ЗАКОДИРОВАННЫЙ_АДРЕС:", "URLENCODE:");
		addI18nCIAlias("anchorencode", "КОДИРОВАТЬ_МЕТКУ", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "ОТМЕТКА_ТЕКУЩЕГО_ВРЕМЕНИ", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "ОТМЕТКА_МЕСТНОГО_ВРЕМЕНИ", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "НАПРАВЛЕНИЕ_ПИСЬМА", "DIRECTIONMARK", "DIRMARK");
		addI18nAlias("contentlanguage", "ЯЗЫК_СОДЕРЖАНИЯ", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "СТРАНИЦ_В_ПРОСТРАНСТВЕ_ИМЁН:", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nCIAlias("formatnum", "ФОРМАТИРОВАТЬ_ЧИСЛО", "FORMATNUM");
		addI18nCIAlias("padleft", "ЗАПОЛНИТЬ_СЛЕВА", "PADLEFT");
		addI18nCIAlias("padright", "ЗАПОЛНИТЬ_СПРАВА", "PADRIGHT");
		addI18nAlias("defaultsort", "СОРТИРОВКА_ПО_УМОЛЧАНИЮ", "КЛЮЧ_СОРТИРОВКИ", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("tag", "метка", "тег", "тэг", "tag");
		addI18nAlias("hiddencat", "__СКРЫТАЯ_КАТЕГОРИЯ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "СТРАНИЦ_В_КАТЕГОРИИ", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("index", "__ИНДЕКС__", "__INDEX__");
		addI18nAlias("noindex", "__БЕЗ_ИНДЕКСА__", "__NOINDEX__");
		addI18nAlias("numberingroup", "ЧИСЛО_В_ГРУППЕ", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__СТАТИЧЕСКОЕ_ПЕРЕНАПРАВЛЕНИЕ__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "УРОВЕНЬ_ЗАЩИТЫ", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "форматдаты", "formatdate", "dateformat");
		addI18nCIAlias("url_query", "ЗАПРОС", "QUERY");
		addI18nCIAlias("pagesincategory_all", "все", "all");
		addI18nCIAlias("pagesincategory_pages", "страницы", "pages");
		addI18nCIAlias("pagesincategory_subcats", "подкатегории", "subcats");
		addI18nCIAlias("pagesincategory_files", "файлы", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://myv.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "myv";
	}
}
