/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class NanConfig extends TemplateConfig {
	public NanConfig() {
		addNamespaceAlias(-2, "媒體", "媒體", "媒體");
		addNamespaceAlias(-1, "特殊", "特殊", "特殊");
		addNamespaceAlias(1, "討論", "討論", "對話", "討論");
		addNamespaceAlias(2, "用戶", "用戶", "用戶");
		addNamespaceAlias(3, "用戶討論", "用戶討論", "用戶對話", "用戶討論");
		addNamespaceAlias(5, "Wikipedia討論", "Wikipedia討論");
		addNamespaceAlias(6, "文件", "檔案", "圖像", "檔案", "文件", "Image");
		addNamespaceAlias(7, "文件討論", "檔案討論", "Image_talk", "圖像對話", "圖像討論", "檔案對話", "檔案討論", "文件對話", "文件討論");
		addNamespaceAlias(8, "媒體維基", "MediaWiki");
		addNamespaceAlias(9, "媒體維基討論", "MediaWiki討論");
		addNamespaceAlias(10, "模板", "模板", "樣板", "模板");
		addNamespaceAlias(11, "模板討論", "模板討論", "樣板對話", "樣板討論", "模板對話", "模板討論");
		addNamespaceAlias(12, "幫助", "幫助", "幫助");
		addNamespaceAlias(13, "幫助討論", "幫助討論", "幫助對話", "幫助討論");
		addNamespaceAlias(14, "分類", "分類", "分類");
		addNamespaceAlias(15, "分類討論", "分類討論", "分類對話", "分類討論");

		addI18nCIAlias("redirect", "#重定向", "#REDIRECT");
		addI18nCIAlias("notoc", "__無目錄__", "__无目录__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__無圖庫__", "__无图库__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__強制目錄__", "__强显目录__", "__FORCETOC__");
		addI18nCIAlias("toc", "__目錄__", "__目录__", "__TOC__");
		addI18nCIAlias("noeditsection", "__無段落編輯__", "__无段落编辑__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "本月", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthabbrev", "本月簡稱", "本月简称", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "今天", "CURRENTDAY");
		addI18nAlias("currenttime", "當前時間", "此時", "此时", "当前时间", "CURRENTTIME");
		addI18nAlias("img_thumbnail", "縮圖", "缩略图", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "縮圖=$1", "缩略图=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "右", "right");
		addI18nAlias("img_left", "左", "left");
		addI18nAlias("img_none", "無", "无", "none");
		addI18nAlias("img_width", "$1像素", "$1px");
		addI18nAlias("img_center", "置中", "居中", "center", "centre");
		addI18nAlias("img_framed", "有框", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "無框", "无框", "frameless");
		addI18nAlias("img_page", "頁=$1", "$1頁", "页数=$1", "$1页", "page=$1", "page $1");
		addI18nAlias("img_link", "連結=$1", "链接=$1", "link=$1");
		addI18nAlias("sitename", "網站名稱", "站点名称", "SITENAME");
		addI18nCIAlias("ns", "名字空間:", "名字空间:", "NS:");
		addI18nCIAlias("nse", "名字空間E:", "名字空间E:", "NSE:");
		addI18nCIAlias("localurl", "本地URL:", "LOCALURL:");
		addI18nCIAlias("localurle", "本地URLE:", "LOCALURLE:");
		addI18nCIAlias("pageid", "頁面ID", "页面ID", "PAGEID");
		addI18nCIAlias("server", "伺服器", "服务器", "SERVER");
		addI18nCIAlias("servername", "伺服器名稱", "服务器名", "SERVERNAME");
		addI18nCIAlias("gender", "性別:", "性别:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__不轉換標題__", "__不转换标题__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__不轉換內容__", "__不转换内容__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("displaytitle", "顯示標題", "显示标题", "DISPLAYTITLE");
		addI18nAlias("currentversion", "當前版本", "当前版本", "CURRENTVERSION");
		addI18nCIAlias("language", "#語言:", "#语言:", "#LANGUAGE:");
		addI18nAlias("hiddencat", "__隱藏分類__", "__隐藏分类__", "__HIDDENCAT__");
		addI18nAlias("staticredirect", "__靜態重定向__", "__静态重定向__", "__STATICREDIRECT__");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://nan.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "nan";
	}
}
