/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class NvConfig extends TemplateConfig {
	public NvConfig() {
		addNamespaceAlias(-2, "Media");
		addNamespaceAlias(-1, "Special");
		addNamespaceAlias(1, "Naaltsoos_baa_yáshtiʼ");
		addNamespaceAlias(2, "Choyoołʼįįhí");
		addNamespaceAlias(3, "Choyoołʼįįhí_bichʼįʼ_yáshtiʼ");
		addNamespaceAlias(5, "Wikipedia_baa_yáshtiʼ");
		addNamespaceAlias(6, "Eʼelyaaígíí");
		addNamespaceAlias(7, "Eʼelyaaígíí_baa_yáshtiʼ");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_baa_yáshtiʼ");
		addNamespaceAlias(10, "Bee_álnééhí");
		addNamespaceAlias(11, "Bee_álnééhí_baa_yáshtiʼ");
		addNamespaceAlias(12, "Anáʼálwoʼ");
		addNamespaceAlias(13, "Anáʼálwoʼ_baa_yáshtiʼ");
		addNamespaceAlias(14, "Tʼááłáhági_átʼéego");
		addNamespaceAlias(15, "Tʼááłáhági_átʼéego_baa_yáshtiʼ");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://nv.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "nv";
	}
}
