/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class OcConfig extends TemplateConfig {
	public OcConfig() {
		addNamespaceAlias(-2, "Mèdia");
		addNamespaceAlias(-1, "Especial");
		addNamespaceAlias(1, "Discutir");
		addNamespaceAlias(2, "Utilizaire", "Utilisator");
		addNamespaceAlias(3, "Discussion_Utilizaire", "Discussion_Utilisator", "Discutida_Utilisator");
		addNamespaceAlias(5, "Discussion_Wikipedia");
		addNamespaceAlias(6, "Fichièr", "Imatge");
		addNamespaceAlias(7, "Discussion_Fichièr", "Discutida_Imatge", "Discussion_Imatge");
		addNamespaceAlias(8, "MediaWiki", "Mediaòiqui");
		addNamespaceAlias(9, "Discussion_MediaWiki", "Discussion_Mediaòiqui", "Discutida_Mediaòiqui");
		addNamespaceAlias(10, "Modèl");
		addNamespaceAlias(11, "Discussion_Modèl", "Discutida_Modèl");
		addNamespaceAlias(12, "Ajuda");
		addNamespaceAlias(13, "Discussion_Ajuda", "Discutida_Ajuda");
		addNamespaceAlias(14, "Categoria");
		addNamespaceAlias(15, "Discussion_Categoria", "Discutida_Categoria");

		addI18nCIAlias("redirect", "#REDIRECCION", "#REDIRECT");
		addI18nCIAlias("notoc", "__CAPDETAULA__", "__PASCAPDESOMARI__", "__PASCAPDETDM__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__CAPDEGALARIÁ__", "__CAPDEGALARIA__", "__PASCAPDEDEGALARIÁ__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__FORÇARTAULA__", "__FORÇARSOMARI__", "__FORÇARTDM__", "__FORCETOC__");
		addI18nCIAlias("toc", "__TAULA__", "__SOMARI__", "__TDM__", "__TOC__");
		addI18nCIAlias("noeditsection", "__SECCIONNONEDITABLA__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "MESCORRENT", "MESACTUAL", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "NOMMESCORRENT", "NOMMESACTUAL", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "NOMGENMESCORRENT", "NOMGENMESACTUAL", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "ABREVMESCORRENT", "ABREVMESACTUAL", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "JORNCORRENT", "JORNACTUAL", "CURRENTDAY");
		addI18nAlias("currentday2", "JORNCORRENT2", "JORNACTUAL2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "NOMJORNCORRENT", "NOMJORNACTUAL", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "ANNADACORRENTA", "ANNADAACTUALA", "CURRENTYEAR");
		addI18nAlias("currenttime", "DATACORRENTA", "DATAACTUALA", "CURRENTTIME");
		addI18nAlias("currenthour", "ORACORRENTA", "ORAACTUALA", "CURRENTHOUR");
		addI18nAlias("localmonth", "MESLOCAL", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonthname", "NOMMESLOCAL", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "NOMGENMESLOCAL", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "ABREVMESLOCAL", "LOCALMONTHABBREV");
		addI18nAlias("localday", "JORNLOCAL", "LOCALDAY");
		addI18nAlias("localday2", "JORNLOCAL2", "LOCALDAY2");
		addI18nAlias("localdayname", "NOMJORNLOCAL", "LOCALDAYNAME");
		addI18nAlias("localyear", "ANNADALOCALA", "LOCALYEAR");
		addI18nAlias("localtime", "ORARILOCAL", "LOCALTIME");
		addI18nAlias("localhour", "ORALOCALA", "LOCALHOUR");
		addI18nAlias("numberofpages", "NOMBREPAGINAS", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "NOMBREARTICLES", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "NOMBREFICHIÈRS", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "NOMBREUTILIZAIRES", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "NOMBREUTILIZAIRESACTIUS", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "NOMBREEDICIONS", "NOMBREMODIFS", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "NOMBREVISTAS", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "NOMPAGINA", "PAGENAME");
		addI18nAlias("pagenamee", "NOMPAGINAX", "PAGENAMEE");
		addI18nAlias("namespace", "ESPACINOMENATGE", "NAMESPACE");
		addI18nAlias("namespacee", "ESPACINOMENATGEX", "NAMESPACEE");
		addI18nAlias("talkspace", "ESPACIDISCUSSION", "TALKSPACE");
		addI18nAlias("talkspacee", "ESPACIDISCUSSIONX", "TALKSPACEE");
		addI18nAlias("subjectspace", "ESPACISUBJECTE", "ESPACISUBJÈCTE", "ESPACIARTICLE", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "ESPACISUBJECTEX", "ESPACISUBJÈCTEX", "ESPACIARTICLEX", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "NOMPAGINACOMPLET", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "NOMPAGINACOMPLETX", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "NOMSOSPAGINA", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "NOMSOSPAGINAX", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "NOMBASADEPAGINA", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "NOMBASADEPAGINAX", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "NOMPAGINADISCUSSION", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "NOMPAGINADISCUSSIONX", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "NOMPAGINASUBJECTE", "NOMPAGINASUBJÈCTE", "NOMPAGINAARTICLE", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "NOMPAGINASUBJECTEX", "NOMPAGINASUBJÈCTEX", "NOMPAGINAARTICLEX", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nAlias("img_thumbnail", "vinheta", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "vinheta=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "drecha", "dreta", "right");
		addI18nAlias("img_left", "esquèrra", "senèstra", "gaucha", "left");
		addI18nAlias("img_none", "neant", "nonrés", "none");
		addI18nAlias("img_center", "centrat", "center", "centre");
		addI18nAlias("img_framed", "quadre", "enquagrat", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "sens_quadre", "frameless");
		addI18nAlias("img_upright", "redreça", "redreça$1", "redreça $1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "bordadura", "border");
		addI18nAlias("img_baseline", "linha_de_basa", "baseline");
		addI18nAlias("img_sub", "indici", "ind", "sub");
		addI18nAlias("img_super", "exp", "super", "sup");
		addI18nAlias("img_top", "naut", "top");
		addI18nAlias("img_text_top", "naut-tèxte", "naut-txt", "text-top");
		addI18nAlias("img_middle", "mitan", "middle");
		addI18nAlias("img_bottom", "bas", "bottom");
		addI18nAlias("img_text_bottom", "bas-tèxte", "bas-txt", "text-bottom");
		addI18nAlias("img_link", "ligam=$1", "link=$1");
		addI18nAlias("sitename", "NOMSIT", "NOMSITE_NOMSITI", "SITENAME");
		addI18nCIAlias("ns", "ESPACEN:", "NS:");
		addI18nCIAlias("localurl", "URLLOCALA:", "LOCALURL:");
		addI18nCIAlias("localurle", "URLLOCALAX:", "LOCALURLE:");
		addI18nCIAlias("server", "SERVIDOR", "SERVER");
		addI18nCIAlias("servername", "NOMSERVIDOR", "SERVERNAME");
		addI18nCIAlias("scriptpath", "CAMINESCRIPT", "SCRIPTPATH");
		addI18nCIAlias("grammar", "GRAMATICA:", "GRAMMAR:");
		addI18nCIAlias("gender", "GENRE:", "GENDER:");
		addI18nAlias("currentweek", "SETMANACORRENTA", "CURRENTWEEK");
		addI18nAlias("currentdow", "JDSCORRENT", "CURRENTDOW");
		addI18nAlias("localweek", "SETMANALOCALA", "LOCALWEEK");
		addI18nAlias("localdow", "JDSLOCAL", "LOCALDOW");
		addI18nAlias("revisionid", "NUMÈROVERSION", "REVISIONID");
		addI18nAlias("revisionday", "DATAVERSION", "REVISIONDAY");
		addI18nAlias("revisionday2", "DATAVERSION2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "MESREVISION", "REVISIONMONTH");
		addI18nAlias("revisionyear", "ANNADAREVISION", "ANREVISION", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "ORAREVISION", "REVISIONTIMESTAMP");
		addI18nCIAlias("fullurl", "URLCOMPLETA:", "FULLURL:");
		addI18nCIAlias("fullurle", "URLCOMPLETAX:", "FULLURLE:");
		addI18nCIAlias("lcfirst", "INITMINUS:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "INITMAJUS:", "UCFIRST:");
		addI18nCIAlias("lc", "MINUS:", "LC:");
		addI18nCIAlias("uc", "MAJUS:", "CAPIT:", "UC:");
		addI18nCIAlias("raw", "LINHA:", "BRUT:", "RAW:");
		addI18nAlias("displaytitle", "AFICHARTÍTOL", "DISPLAYTITLE");
		addI18nAlias("rawsuffix", "BRUT", "B", "R");
		addI18nAlias("newsectionlink", "__LIGAMSECCIONNOVÈLA__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__PASCAPDELIGAMSECCIONNOVÈLA__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "VERSIONACTUALA", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "ENCÒDAURL:", "URLENCODE:");
		addI18nCIAlias("anchorencode", "ENCÒDAANCÒRA", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "INSTANTACTUAL", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "INSTANTLOCAL", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "MARCADIRECCION", "MARCADIR", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#LENGA:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "LENGACONTENGUT", "LENGCONTENGUT", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "PAGINASDINSESPACI:", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "NOMBREADMINS", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "FORMATNOMBRE", "FORMATNUM");
		addI18nCIAlias("padleft", "BORRATGEESQUÈRRA", "PADLEFT");
		addI18nCIAlias("padright", "BORRATGEDRECHA", "PADRIGHT");
		addI18nCIAlias("special", "especial", "special");
		addI18nAlias("defaultsort", "ORDENA:", "CLAUDETRIADA:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "CAMIN:", "FILEPATH:");
		addI18nCIAlias("tag", "balisa", "tag");
		addI18nAlias("hiddencat", "__CATAMAGADA__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "PAGINASDINSCAT", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "TALHAPAGINA", "PAGESIZE");
		addI18nAlias("noindex", "__PASCAPDINDÈX__", "__NOINDEX__");
		addI18nAlias("staticredirect", "__REDIRECCIONESTATICA__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "NIVÈLDEPROTECCION", "PROTECTIONLEVEL");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://oc.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "oc";
	}
}
