/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class OrConfig extends TemplateConfig {
	public OrConfig() {
		addNamespaceAlias(-2, "ମାଧ୍ୟମ");
		addNamespaceAlias(-1, "ବିଶେଷ");
		addNamespaceAlias(1, "ଆଲୋଚନା");
		addNamespaceAlias(2, "ବ୍ୟବହାରକାରୀ", "ବ୍ୟବହାରକାରି", "ବ୍ୟବାହାରକାରୀ");
		addNamespaceAlias(3, "ବ୍ୟବହାରକାରୀଙ୍କ_ଆଲୋଚନା", "ବ୍ୟବହାରକାରିଁକ_ଆଲୋଚନା", "ବ୍ୟବାହାରକାରୀଙ୍କ_ଆଲୋଚନା");
		addNamespaceAlias(5, "Wikipedia_ଆଲୋଚନା", "ଉଇକିପିଡ଼ିଆ_ଆଲୋଚନା");
		addNamespaceAlias(6, "ଫାଇଲ");
		addNamespaceAlias(7, "ଫାଇଲ_ଆଲୋଚନା");
		addNamespaceAlias(8, "ମିଡ଼ିଆଉଇକି");
		addNamespaceAlias(9, "ମିଡ଼ିଆଉଇକି_ଆଲୋଚନା");
		addNamespaceAlias(10, "ଛାଞ୍ଚ", "ଟେଁପଲେଟ", "ଟେମ୍ପଲେଟ");
		addNamespaceAlias(11, "ଛାଞ୍ଚ_ଆଲୋଚନା", "ଟେଁପଲେଟ_ଆଲୋଚନା", "ଟେମ୍ପଲେଟ_ଆଲୋଚନା");
		addNamespaceAlias(12, "ସହଯୋଗ", "ସାହାଯ୍ୟ");
		addNamespaceAlias(13, "ସହଯୋଗ_ଆଲୋଚନା", "ସାହାଯ୍ୟ_ଆଲୋଚନା");
		addNamespaceAlias(14, "ଶ୍ରେଣୀ", "ବିଭାଗ");
		addNamespaceAlias(15, "ଶ୍ରେଣୀ_ଆଲୋଚନା", "ବିଭାଗିୟ_ଆଲୋଚନା");

		addI18nCIAlias("redirect", "#ଲେଉଟାଣି", "#REDIRECT");
		addI18nCIAlias("noeditsection", "_ବଦଳା_ନହେବାଶ୍ରେଣୀ_", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "ଏବେକାର_ମାସ", "ଏବେର_ମାସ୨", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "ଏବେର_ମାସ", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "ଏବେକାର_ମାସ_ନାଆଁ", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "ଏବେକାର_ମାସ_ନାଆଁ_ସାଧାରଣ", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "ଏବେକାର_ମାସ_ନାଆଁ_ସଂକ୍ଷିପ୍ତ", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "ଏବେକାର_ଦିନ", "CURRENTDAY");
		addI18nAlias("currentday2", "ଏବେକାର_ଦିନ୨", "CURRENTDAY2");
		addI18nAlias("currentdayname", "ଏବେକାର_ଦିନ_ନାଆଁ", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "ଏବେକାର_ବର୍ଷ", "CURRENTYEAR");
		addI18nAlias("currenttime", "ଏବେକାର_ସମୟ", "CURRENTTIME");
		addI18nAlias("currenthour", "ଏବେକାର_ଘଣ୍ଟା", "CURRENTHOUR");
		addI18nAlias("localmonth", "ଏବେର_ମାସ୧", "ସ୍ଥାନୀୟ_ମାସ୨", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "ଏବେକାର_ମାସ୧", "LOCALMONTH1");
		addI18nAlias("localmonthname", "ମାସ୧ର_ନାଆଁ", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "ସ୍ଥାନୀୟ_ମାସ୧_ନାଆଁ_ସାଧାରଣ", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "ସ୍ଥାନୀୟ_ମାସର୧_ନାଆଁ_ସଂକ୍ଷିପ୍ତ", "LOCALMONTHABBREV");
		addI18nAlias("localday", "Local_ଦିନ", "LOCALDAY");
		addI18nAlias("localday2", "ସ୍ଥାନୀୟ_ଦିନ୨", "LOCALDAY2");
		addI18nAlias("localdayname", "ଦିନ", "LOCALDAYNAME");
		addI18nAlias("localyear", "ସ୍ଥାନୀୟ_ବର୍ଷ", "LOCALYEAR");
		addI18nAlias("localtime", "ସ୍ଥାନୀୟ_ସମୟ", "LOCALTIME");
		addI18nAlias("localhour", "ସ୍ଥାନୀୟ_ଘଣ୍ଟା", "LOCALHOUR");
		addI18nAlias("numberofpages", "ପୃଷ୍ଠା_ସଂଖ୍ୟା", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "ଲେଖା_ସଂଖ୍ୟା", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "ଫାଇଲ_ସଂଖ୍ୟା", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "ବ୍ୟବାହାରକାରୀ_ସଂଖ୍ୟା", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "ସଚଳ_ବ୍ୟବାହାରକାରୀଙ୍କ_ସଂଖ୍ୟା", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "ବଦଳ_ସଂଖ୍ୟା", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "କେତେଥର_ଦେଖାଯାଇଛି", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "ପୃଷ୍ଠା_ନାଆଁ", "PAGENAME");
		addI18nAlias("pagenamee", "ପୃଷ୍ଠା_ନାମକାରଣକାରୀ", "PAGENAMEE");
		addI18nAlias("namespace", "ନେମସ୍ପେସ", "NAMESPACE");
		addI18nAlias("namespacee", "ନେମସ୍ପେସକାରୀ", "NAMESPACEE");
		addI18nAlias("talkspace", "ଟକସ୍ପେସ", "TALKSPACE");
		addI18nAlias("talkspacee", "ଟକସ୍ପେସକାରୀ", "TALKSPACEE");
		addI18nAlias("subjectspace", "ବିଷୟସ୍ପେସ", "ଲେଖାସ୍ପେସ", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nCIAlias("msg", "ମେସେଜ:", "MSG:");
		addI18nAlias("img_manualthumb", "ନଖଦେଖଣା=$1", "ଦେଖଣା=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "ଡାହାଣ", "right");
		addI18nAlias("img_left", "ବାଆଁ", "left");
		addI18nAlias("img_none", "କିଛି_ନୁହେଁ", "none");
		addI18nAlias("img_width", "$1_ପିକସେଲ", "$1px");
		addI18nAlias("img_center", "କେନ୍ଦ୍ର", "center", "centre");
		addI18nAlias("img_framed", "ଫ୍ରେମକରା", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "ଫ୍ରେମନଥିବା", "frameless");
		addI18nAlias("img_border", "ବର୍ଡର", "border");
		addI18nAlias("img_baseline", "ବେସଲାଇନ", "baseline");
		addI18nAlias("img_top", "ଉପର", "top");
		addI18nAlias("img_text_top", "ଲେଖା-ଉପର", "text-top");
		addI18nAlias("img_middle", "ମଝି", "middle");
		addI18nAlias("img_bottom", "ତଳ", "bottom");
		addI18nAlias("img_text_bottom", "ଲେଖା-ତଳ", "text-bottom");
		addI18nAlias("img_link", "ଲିଙ୍କ=$1", "link=$1");
		addI18nCIAlias("articlepath", "ଲେଖାର_ପଥ", "ARTICLEPATH");
		addI18nCIAlias("server", "ସର୍ଭର", "SERVER");
		addI18nCIAlias("grammar", "ବ୍ୟାକରଣ", "GRAMMAR:");
		addI18nCIAlias("gender", "ଲିଙ୍ଗ", "GENDER:");
		addI18nCIAlias("plural", "ବହୁବଚନ:", "PLURAL:");
		addI18nCIAlias("raw", "କଞ୍ଚା", "RAW:");
		addI18nAlias("displaytitle", "ଦେଖଣାନାଆଁ", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "_ନୂଆବିଭାଗଲିଙ୍କ_", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "_ନୂଆ_ବିଭାଗ_ନକରିବା_ଲିଙ୍କ_", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "ନଗଦ_ରିଭିଜନ", "CURRENTVERSION");
		addI18nAlias("numberofadmins", "ପରିଛାମାନଙ୍କତାଲିକା", "NUMBEROFADMINS");
		addI18nCIAlias("padleft", "ବାଆଁପ୍ୟାଡ଼", "PADLEFT");
		addI18nCIAlias("padright", "ଡାହାଣପ୍ୟାଡ଼", "PADRIGHT");
		addI18nCIAlias("special", "ବିଶେଷ", "special");
		addI18nCIAlias("filepath", "ଫାଇଲରାହା:", "FILEPATH:");
		addI18nCIAlias("tag", "ଟାଗ", "tag");
		addI18nAlias("hiddencat", "_ଲୁଚିଥିବାବିଭାଗ_", "__HIDDENCAT__");
		addI18nAlias("pagesize", "ଫରଦଆକାର", "PAGESIZE");
		addI18nAlias("protectionlevel", "ପ୍ରତିରକ୍ଷାସ୍ତର", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "ତାରିଖରପ୍ରକାର", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "ବାଟ", "PATH");
		addI18nCIAlias("url_wiki", "ଉଇକି", "WIKI");
		addI18nCIAlias("url_query", "ପ୍ରଶ୍ନ", "QUERY");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://or.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "or";
	}
}
