/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class PntConfig extends TemplateConfig {
	public PntConfig() {
		addNamespaceAlias(-2, "Μέσον");
		addNamespaceAlias(-1, "Ειδικόν");
		addNamespaceAlias(1, "Καλάτσεμαν");
		addNamespaceAlias(2, "Χρήστες");
		addNamespaceAlias(3, "Καλάτσεμαν_χρήστε");
		addNamespaceAlias(5, "Wikipedia_καλάτσεμαν");
		addNamespaceAlias(6, "Αρχείον", "Εικόναν");
		addNamespaceAlias(7, "Καλάτσεμαν_αρχείονος", "Καλάτσεμαν_εικόνας");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_talk");
		addNamespaceAlias(10, "Πρότυπον");
		addNamespaceAlias(11, "Καλάτσεμαν_πρότυπι");
		addNamespaceAlias(12, "Βοήθειαν");
		addNamespaceAlias(13, "Καλάτσεμαν_βοήθειας");
		addNamespaceAlias(14, "Κατηγορίαν");
		addNamespaceAlias(15, "Καλάτσεμαν_κατηγορίας");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://pnt.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "pnt";
	}
}
