/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class PsConfig extends TemplateConfig {
	public PsConfig() {
		addNamespaceAlias(-2, "رسنۍ");
		addNamespaceAlias(-1, "ځانګړی");
		addNamespaceAlias(1, "خبرې_اترې");
		addNamespaceAlias(2, "کارن", "کارونکی");
		addNamespaceAlias(3, "د_کارن_خبرې_اترې", "د_کارونکي_خبرې_اترې");
		addNamespaceAlias(5, "د_Wikipedia_خبرې_اترې");
		addNamespaceAlias(6, "دوتنه", "انځور");
		addNamespaceAlias(7, "د_دوتنې_خبرې_اترې", "د_انځور_خبرې_اترې");
		addNamespaceAlias(8, "ميډياويکي");
		addNamespaceAlias(9, "د_ميډياويکي_خبرې_اترې");
		addNamespaceAlias(10, "کينډۍ");
		addNamespaceAlias(11, "د_کينډۍ_خبرې_اترې");
		addNamespaceAlias(12, "لارښود");
		addNamespaceAlias(13, "د_لارښود_خبرې_اترې");
		addNamespaceAlias(14, "وېشنيزه");
		addNamespaceAlias(15, "د_وېشنيزې_خبرې_اترې");

		addI18nCIAlias("notoc", "__بی‌نيولک__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__بی‌نندارتونه__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__نيوليکداره__", "__FORCETOC__");
		addI18nCIAlias("toc", "__نيوليک__", "__TOC__");
		addI18nCIAlias("noeditsection", "__بی‌برخې__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "روانه_مياشت", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "دروانې_مياشت_نوم", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthabbrev", "دروانې_مياشت_لنډون", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "نن", "CURRENTDAY");
		addI18nAlias("currentday2", "نن۲", "CURRENTDAY2");
		addI18nAlias("currentdayname", "دننۍورځې_نوم", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "سږکال", "CURRENTYEAR");
		addI18nAlias("currenttime", "داوخت", "CURRENTTIME");
		addI18nAlias("currenthour", "دم_ګړۍ", "CURRENTHOUR");
		addI18nAlias("localmonth", "سيمه_يزه_مياشت", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonthname", "دسيمه_يزې_مياشت_نوم", "LOCALMONTHNAME");
		addI18nAlias("localmonthabbrev", "دسيمه_يزې_مياشت_لنډون", "LOCALMONTHABBREV");
		addI18nAlias("localday", "سيمه_يزه_ورځ", "LOCALDAY");
		addI18nAlias("localday2", "سيمه_يزه_ورځ۲", "LOCALDAY2");
		addI18nAlias("localdayname", "دسيمه_يزې_ورځ_نوم", "LOCALDAYNAME");
		addI18nAlias("localyear", "سيمه_يزکال", "LOCALYEAR");
		addI18nAlias("localtime", "سيمه_يزوخت", "LOCALTIME");
		addI18nAlias("localhour", "سيمه_يزه_ګړۍ", "LOCALHOUR");
		addI18nAlias("numberofpages", "دمخونوشمېر", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "دليکنوشمېر", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "ددوتنوشمېر", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "دکارونکوشمېر", "NUMBEROFUSERS");
		addI18nAlias("pagename", "دمخ_نوم", "PAGENAME");
		addI18nAlias("pagenamee", "دمخ_نښه", "PAGENAMEE");
		addI18nAlias("namespace", "نوم_تشيال", "NAMESPACE");
		addI18nAlias("namespacee", "د_نوم_تشيال_نښه", "NAMESPACEE");
		addI18nAlias("talkspace", "دخبرواترو_تشيال", "TALKSPACE");
		addI18nAlias("talkspacee", "دخبرواترو_تشيال_نښه", "TALKSPACEE");
		addI18nAlias("subjectspace", "دسکالوتشيال", "دليکنې_تشيال", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "دسکالوتشيال_نښه", "دليکنې_تشيال_نښه", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "دمخ_بشپړنوم", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "دمخ_بشپړنوم_نښه", "FULLPAGENAMEE");
		addI18nCIAlias("msg", "پیغام:", "پ:", "MSG:");
		addI18nAlias("img_thumbnail", "بټنوک", "thumbnail", "thumb");
		addI18nAlias("img_right", "ښي", "right");
		addI18nAlias("img_left", "کيڼ", "left");
		addI18nAlias("img_none", "هېڅ", "none");
		addI18nAlias("img_center", "مېنځ،_center", "center", "centre");
		addI18nAlias("sitename", "دوېبځي_نوم", "SITENAME");
		addI18nCIAlias("server", "پالنګر", "SERVER");
		addI18nCIAlias("servername", "دپالنګر_نوم", "SERVERNAME");
		addI18nCIAlias("grammar", "ګرامر:", "GRAMMAR:");
		addI18nAlias("currentweek", "روانه_اوونۍ", "CURRENTWEEK");
		addI18nAlias("currentdow", "داوونۍورځ", "CURRENTDOW");
		addI18nAlias("localweek", "سيمه_يزه_اوونۍ", "LOCALWEEK");
		addI18nCIAlias("plural", "جمع:", "PLURAL:");
		addI18nCIAlias("language", "#ژبه:", "#LANGUAGE:");
		addI18nCIAlias("special", "ځانګړی", "special");
		addI18nAlias("hiddencat", "__پټه_وېشنيزه__", "__HIDDENCAT__");
		addI18nAlias("pagesize", "مخکچه", "PAGESIZE");
		addI18nAlias("index", "__ليکلړ__", "__INDEX__");
		addI18nAlias("noindex", "__بې_ليکلړ__", "__NOINDEX__");
		addI18nAlias("protectionlevel", "ژغورکچه", "PROTECTIONLEVEL");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ps.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ps";
	}
}
