/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class QugConfig extends TemplateConfig {
	public QugConfig() {
		addNamespaceAlias(-2, "Midya", "Midya", "Medio");
		addNamespaceAlias(-1, "Sapak", "Sapaq", "Especial");
		addNamespaceAlias(1, "Rimanakuy", "Rimanakuy", "Discusión");
		addNamespaceAlias(2, "Rurak", "Ruraq", "Usuario", "Usuario", "Usuaria");
		addNamespaceAlias(3, "Rurakpa_rimanakuy", "Ruraq_rimanakuy", "Usuario_discusión", "Usuario_Discusión", "Usuaria_Discusión");
		addNamespaceAlias(5, "Wikipedia-pa_rimanakuy", "Wikipedia_rimanakuy", "Wikipedia_discusión");
		addNamespaceAlias(6, "Rikcha", "Rikcha", "Archivo", "Imagen");
		addNamespaceAlias(7, "Rikchapa_rimanakuy", "Rikcha_rimanakuy", "Archivo_discusión", "Imagen_Discusión");
		addNamespaceAlias(8, "MediaWiki", "MediaWiki", "MediaWiki");
		addNamespaceAlias(9, "MediaWikipa_rimanakuy", "MediaWiki_rimanakuy", "MediaWiki_discusión");
		addNamespaceAlias(10, "Plantilla", "Plantilla", "Plantilla");
		addNamespaceAlias(11, "Plantillapa_rimanakuy", "Plantilla_rimanakuy", "Plantilla_discusión");
		addNamespaceAlias(12, "Yanapa", "Yanapa", "Ayuda");
		addNamespaceAlias(13, "Yanapapak_rimanakuy", "Yanapa_rimanakuy", "Ayuda_discusión");
		addNamespaceAlias(14, "Samiyachiy", "Katiguriya", "Categoría");
		addNamespaceAlias(15, "Samiyachiy_rimanakuy", "Katiguriya_rimanakuy", "Categoría_discusión");

		addI18nCIAlias("redirect", "#PUSAPUNA", "#REDIRECCIÓN", "#REDIRECCION", "#REDIRECT", "Array");
		addI18nCIAlias("notoc", "__YUYARINANNAQ__", "__NOTDC__", "__SIN_TDC__", "__NOTOC__", "Array");
		addI18nCIAlias("nogallery", "__RIKCHASUYUNNAQ__", "__NOGALERÍA__", "__NOGALERIA__", "__SIN_GALERÍA__", "__NOGALLERY__", "Array");
		addI18nCIAlias("forcetoc", "__YUYARINATAATIPACHIY__", "__FORZARTDC__", "__FORZARTOC__", "__FORZAR_TDC__", "__FORCETOC__", "Array");
		addI18nCIAlias("toc", "__YUYARINA__", "__TDC__", "__TOC__", "Array");
		addI18nCIAlias("noeditsection", "__AMARAKITAHUKCHAYCHU__", "__NOEDITARSECCIÓN__", "__NOEDITARSECCION__", "__NO_EDITAR_SECCIÓN__", "__NOEDITSECTION__", "Array");
		addI18nAlias("currentmonth", "KUNANKILLA", "MESACTUAL", "MES_ACTUAL", "MESACTUAL2", "CURRENTMONTH", "CURRENTMONTH2", "Array");
		addI18nAlias("currentmonthname", "KUNANKILLASUTI", "NOMBREMESACTUAL", "NOMBRE_MES_ACTUAL", "MESACTUALCOMPLETO", "CURRENTMONTHNAME", "Array");
		addI18nAlias("currentmonthnamegen", "KUNANKILLASUTIP", "GENERADORNOMBREMESACTUAL", "MESACTUALGENITIVO", "CURRENTMONTHNAMEGEN", "Array");
		addI18nAlias("currentmonthabbrev", "KUNANKILLAPISI", "ABREVIACIONNOMBREMESACTUAL", "ABREVIACIÓNNOMBREMESACTUAL", "MESACTUALABREVIADO", "CURRENTMONTHABBREV", "Array");
		addI18nAlias("currentday", "KUNANPUNCHAW", "DÍAACTUAL", "DIAACTUAL", "DÍA_ACTUAL", "DIA_ACTUAL", "CURRENTDAY", "Array");
		addI18nAlias("currentday2", "KUNANPUNCHAW2", "DÍAACTUAL2", "DIAACTUAL2", "DÍA_ACTUAL2", "DIA_ACTUAL2", "CURRENTDAY2", "Array");
		addI18nAlias("currentdayname", "KUNANPUNCHAWSUTI", "NOMBREDÍAACTUAL", "NOMBREDIAACTUAL", "CURRENTDAYNAME", "Array");
		addI18nAlias("currentyear", "KUNANWATA", "AÑOACTUAL", "AÑO_ACTUAL", "CURRENTYEAR", "Array");
		addI18nAlias("currenttime", "KUNANPACHA", "HORAACTUAL", "HORA_ACTUAL", "HORA_MINUTOS_ACTUAL", "HORAMINUTOSACTUAL", "TIEMPOACTUAL", "CURRENTTIME", "Array");
		addI18nAlias("currenthour", "KUNANURA", "HORAACTUAL", "HORA_ACTUAL", "CURRENTHOUR", "Array");
		addI18nAlias("localmonth", "KAYPIKILLA", "MESLOCAL", "MESLOCAL2", "LOCALMONTH", "LOCALMONTH2", "Array");
		addI18nAlias("localmonthname", "KAYPIKILLASUTI", "NOMBREMESLOCAL", "MESLOCALCOMPLETO", "LOCALMONTHNAME", "Array");
		addI18nAlias("localmonthnamegen", "KAYPIKILLASUTIP", "GENERADORNOMBREMESLOCAL", "MESLOCALGENITIVO", "LOCALMONTHNAMEGEN", "Array");
		addI18nAlias("localmonthabbrev", "KAYPIKILLAPISI", "ABREVIACIONMESLOCAL", "MESLOCALABREVIADO", "LOCALMONTHABBREV", "Array");
		addI18nAlias("localday", "KAYPIPUNCHAW", "DÍALOCAL", "DIALOCAL", "LOCALDAY", "Array");
		addI18nAlias("localday2", "KAYPIPUNCHAW2", "DIALOCAL2", "DÍALOCAL2", "LOCALDAY2", "Array");
		addI18nAlias("localdayname", "KAYPIPUNCHAWSUTI", "NOMBREDIALOCAL", "NOMBREDÍALOCAL", "LOCALDAYNAME", "Array");
		addI18nAlias("localyear", "KAYPIWATA", "AÑOLOCAL", "LOCALYEAR", "Array");
		addI18nAlias("localtime", "KAYPIPACHA", "HORALOCAL", "HORAMINUTOSLOCAL", "TIEMPOLOCAL", "LOCALTIME", "Array");
		addI18nAlias("localhour", "KAYPIURA", "HORALOCAL", "LOCALHOUR", "Array");
		addI18nAlias("numberofpages", "HAYKAPANQA", "NÚMERODEPÁGINAS", "NUMERODEPAGINAS", "NUMBEROFPAGES", "Array");
		addI18nAlias("numberofarticles", "HAYKAQILLQA", "NÚMERODEARTÍCULOS", "NUMERODEARTICULOS", "NUMBEROFARTICLES", "Array");
		addI18nAlias("numberoffiles", "HAYKAWILLANIQI", "NÚMERODEARCHIVOS", "NUMERODEARCHIVOS", "NUMBEROFFILES", "Array");
		addI18nAlias("numberofusers", "HAYKARURAQ", "NÚMERODEUSUARIOS", "NUMERODEUSUARIOS", "NUMBEROFUSERS", "Array");
		addI18nAlias("numberofactiveusers", "HAYKARURACHKAQ", "NÚMERODEUSUARIOSACTIVOS", "NUMERODEUSUARIOSACTIVOS", "NUMBEROFACTIVEUSERS", "Array");
		addI18nAlias("numberofedits", "HAYKALLAMKAPUSQA", "NÚMERODEEDICIONES", "NUMERODEEDICIONES", "NUMBEROFEDITS", "Array");
		addI18nAlias("numberofviews", "HAYKAQHAWASQA", "HAYKAQAWASQA", "NÚMERODEVISTAS", "NUMERODEVISTAS", "NUMBEROFVIEWS", "Array");
		addI18nAlias("pagename", "PANQASUTI", "NOMBREDEPAGINA", "NOMBREDEPÁGINA", "PAGENAME", "Array");
		addI18nAlias("pagenamee", "PANQASUTIE", "NOMBREDEPAGINAC", "NOMBREDEPÁGINAC", "PAGENAMEE", "Array");
		addI18nAlias("namespace", "SUTIKITI", "ESPACIODENOMBRE", "NAMESPACE", "Array");
		addI18nAlias("namespacee", "SUTIKITIE", "ESPACIODENOMBREC", "NAMESPACEE", "Array");
		addI18nAlias("talkspace", "RIMANAKUYKITI", "RIMAYKITI", "ESPACIODEDISCUSION", "ESPACIODEDISCUSIÓN", "TALKSPACE", "Array");
		addI18nAlias("talkspacee", "RIMANAKUYKITIE", "RIMAYKITIE", "ESPACIODEDISCUSIONC", "TALKSPACEE", "Array");
		addI18nAlias("subjectspace", "QILLQAKITI", "ESPACIODEASUNTO", "ESPACIODETEMA", "ESPACIODEARTÍCULO", "ESPACIODEARTICULO", "SUBJECTSPACE", "ARTICLESPACE", "Array");
		addI18nAlias("subjectspacee", "QILLQAKITIE", "ESPACIODETEMAC", "ESPACIODEASUNTOC", "ESPACIODEARTICULOC", "ESPACIODEARTÍCULOC", "SUBJECTSPACEE", "ARTICLESPACEE", "Array");
		addI18nAlias("fullpagename", "HUNTAPANQASUTI", "NOMBREDEPÁGINACOMPLETA", "NOMBREDEPAGINACOMPLETA", "NOMBREDEPÁGINAENTERA", "NOMBREDEPAGINAENTERA", "NOMBRECOMPLETODEPÁGINA", "NOMBRECOMPLETODEPAGINA", "FULLPAGENAME", "Array");
		addI18nAlias("fullpagenamee", "HUNTAPANQASUTIE", "NOMBRECOMPLETODEPAGINAC", "NOMBRECOMPLETODEPÁGINAC", "FULLPAGENAMEE", "Array");
		addI18nAlias("subpagename", "URINPANQASUTI", "NOMBREDESUBPAGINA", "NOMBREDESUBPÁGINA", "SUBPAGENAME", "Array");
		addI18nAlias("subpagenamee", "URINPANQASUTIE", "NOMBREDESUBPAGINAC", "NOMBREDESUBPÁGINAC", "SUBPAGENAMEE", "Array");
		addI18nAlias("basepagename", "TIKSIPANQASUTI", "NOMBREDEPAGINABASE", "NOMBREDEPÁGINABASE", "BASEPAGENAME", "Array");
		addI18nAlias("basepagenamee", "TIKSIPANQASUTIE", "NOMBREDEPAGINABASEC", "NOMBREDEPÁGINABASEC", "BASEPAGENAMEE", "Array");
		addI18nAlias("talkpagename", "RIMANAKUYPANQASUTI", "NOMBREDEPÁGINADEDISCUSIÓN", "NOMBREDEPAGINADEDISCUSION", "NOMBREDEPAGINADISCUSION", "NOMBREDEPÁGINADISCUSIÓN", "TALKPAGENAME", "Array");
		addI18nAlias("talkpagenamee", "RIMANAKUYPANQASUTIE", "NOMBREDEPÁGINADEDISCUSIÓNC", "NOMBREDEPAGINADEDISCUSIONC", "NOMBREDEPAGINADISCUSIONC", "NOMBREDEPÁGINADISCUSIÓNC", "TALKPAGENAMEE", "Array");
		addI18nAlias("subjectpagename", "QILLQAPANQASUTI", "NOMBREDEPAGINADETEMA", "NOMBREDEPÁGINADETEMA", "NOMBREDEPÁGINADEASUNTO", "NOMBREDEPAGINADEASUNTO", "NOMBREDEPAGINADEARTICULO", "NOMBREDEPÁGINADEARTÍCULO", "SUBJECTPAGENAME", "ARTICLEPAGENAME", "Array");
		addI18nAlias("subjectpagenamee", "QILLQAPANQASUTIE", "NOMBREDEPAGINADETEMAC", "NOMBREDEPÁGINADETEMAC", "NOMBREDEPÁGINADEASUNTOC", "NOMBREDEPAGINADEASUNTOC", "NOMBREDEPAGINADEARTICULOC", "NOMBREDEPÁGINADEARTÍCULOC", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE", "Array");
		addI18nCIAlias("msg", "WILLA:", "MSJ:", "MSG:", "Array");
		addI18nCIAlias("subst", "WAKCHAY:", "SUST:", "FIJAR:", "SUBST:", "Array");
		addI18nCIAlias("msgnw", "WILLAMUSUQ:", "MSGNW:");
		addI18nAlias("img_thumbnail", "rikchacha", "miniaturadeimagen", "miniatura", "mini", "thumbnail", "thumb", "Array");
		addI18nAlias("img_manualthumb", "rikchacha=$1", "miniaturadeimagen=$1", "miniatura=$1", "thumbnail=$1", "thumb=$1", "Array");
		addI18nAlias("img_right", "paña", "alliq", "derecha", "dcha", "der", "right", "Array");
		addI18nAlias("img_left", "lluqi", "ichuq", "izquierda", "izda", "izq", "left", "Array");
		addI18nAlias("img_none", "manaima", "mana", "ninguna", "nada", "no", "ninguno", "none", "Array");
		addI18nAlias("img_center", "chawpi", "centro", "centrado", "centrada", "centrar", "center", "centre", "Array");
		addI18nAlias("img_framed", "inchuyuq", "inchu", "marco", "enmarcado", "enmarcada", "framed", "enframed", "frame", "Array");
		addI18nAlias("img_frameless", "inchunnaq", "sinmarco", "sin_embarcar", "sinenmarcar", "sin_enmarcar", "frameless", "Array");
		addI18nAlias("img_page", "panqa=$1", "pagina=$1", "página=$1", "pagina_$1", "página_$1", "page=$1", "page $1", "Array");
		addI18nAlias("img_upright", "sayaq", "sayaq=$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "saywa", "borde", "border", "Array");
		addI18nAlias("img_baseline", "tiksisiqi", "baseline");
		addI18nAlias("img_sub", "uran", "sub");
		addI18nAlias("img_super", "hanan", "super", "sup");
		addI18nAlias("img_top", "hawa", "top");
		addI18nAlias("img_text_top", "qillqahawa", "text-top");
		addI18nAlias("img_middle", "ukhupi", "middle");
		addI18nAlias("img_bottom", "sikipi", "bottom");
		addI18nAlias("img_text_bottom", "qillqasiki", "text-bottom");
		addI18nAlias("img_link", "tinki=$1", "vínculo=$1", "vinculo=$1", "enlace=$1", "link=$1", "Array");
		addI18nAlias("img_alt", "wak=$1", "alt=$1");
		addI18nCIAlias("int", "WILLAY:", "INT:");
		addI18nAlias("sitename", "TIYAYSUTI", "NOMBREDESITIO", "NOMBREDELSITIO", "SITENAME", "Array");
		addI18nCIAlias("ns", "SKITI:", "EN:", "NS:", "Array");
		addI18nCIAlias("localurl", "KAYLLAURL:", "URLLOCAL", "LOCALURL:", "Array");
		addI18nCIAlias("localurle", "KAYLLAURLE:", "URLLOCALC:", "LOCALURLE:", "Array");
		addI18nCIAlias("server", "SIRWIQ", "SERVIDOR", "SERVER", "Array");
		addI18nCIAlias("servername", "SIRWIQSUTI", "NOMBRESERVIDOR", "SERVERNAME", "Array");
		addI18nCIAlias("scriptpath", "QILLQAÑAN", "QILLQANAN", "RUTASCRIPT", "RUTADESCRIPT", "SCRIPTPATH", "Array");
		addI18nCIAlias("grammar", "SIMIKAMACHIY:", "GRAMATICA:", "GRAMÁTICA:", "GRAMMAR:", "Array");
		addI18nCIAlias("gender", "QHARIWARMI:", "QARIWARMI:", "GÉNERO:", "GENERO:", "GENDER:", "Array");
		addI18nCIAlias("notitleconvert", "__AMASUTITAHUKCHAYCHU__", "__NOCONVERTIRTITULO__", "__NOCONVERTIRTÍTULO__", "__NOCT___", "__NOTITLECONVERT__", "__NOTC__", "Array");
		addI18nCIAlias("nocontentconvert", "__AMASAMIQTAHUKCHAYCHU__", "__NOCONVERTIRCONTENIDO__", "__NOCC___", "__NOCONTENTCONVERT__", "__NOCC__", "Array");
		addI18nAlias("currentweek", "KUNANSIMANA", "SEMANAACTUAL", "CURRENTWEEK", "Array");
		addI18nAlias("currentdow", "KUNANSIMANAPUNCHAW", "DDSACTUAL", "DIADESEMANAACTUAL", "DÍADESEMANAACTUAL", "CURRENTDOW", "Array");
		addI18nAlias("localweek", "KAYLLASIMANA", "SEMANALOCAL", "LOCALWEEK", "Array");
		addI18nAlias("localdow", "KAYLLASIMANAPUNCHAW", "DDSLOCAL", "DIADESEMANALOCAL", "DÍADESEMANALOCAL", "LOCALDOW", "Array");
		addI18nAlias("revisionid", "MUSUQCHASQAID", "IDDEREVISION", "IDREVISION", "IDDEREVISIÓN", "IDREVISIÓN", "REVISIONID", "Array");
		addI18nAlias("revisionday", "MUSUQCHASQAPUNCHAW", "DIADEREVISION", "DIAREVISION", "DÍADEREVISIÓN", "DÍAREVISIÓN", "REVISIONDAY", "Array");
		addI18nAlias("revisionday2", "MUSUQCHASQAPUNCHAW2", "DIADEREVISION2", "DIAREVISION2", "DÍADEREVISIÓN2", "DÍAREVISIÓN2", "REVISIONDAY2", "Array");
		addI18nAlias("revisionmonth", "MUSUQCHASQAKILLA", "MESDEREVISION", "MESDEREVISIÓN", "MESREVISION", "MESREVISIÓN", "REVISIONMONTH", "Array");
		addI18nAlias("revisionyear", "MUSUQCHASQAWATA", "AÑODEREVISION", "AÑODEREVISIÓN", "AÑOREVISION", "AÑOREVISIÓN", "REVISIONYEAR", "Array");
		addI18nAlias("revisiontimestamp", "MUSUQCHASQAPACHAQILLPA", "MARCADEHORADEREVISION", "MARCADEHORADEREVISIÓN", "REVISIONTIMESTAMP", "Array");
		addI18nAlias("revisionuser", "MUSUQCHASQARURAQ", "USUARIODEREVISION", "USUARIODEREVISIÓN", "REVISIONUSER", "Array");
		addI18nCIAlias("plural", "ACHKA:", "PLURAL:");
		addI18nCIAlias("fullurl", "HUNTAURL:", "URLCOMPLETA:", "FULLURL:", "Array");
		addI18nCIAlias("fullurle", "HUNTAURLE:", "URLCOMPLETAC:", "FULLURLE:", "Array");
		addI18nCIAlias("lcfirst", "UCHUYÑAWPAQ:", "UCHUYNAWPAQ:", "PRIMEROMINUS;", "PRIMEROMINÚS:", "LCFIRST:", "Array");
		addI18nCIAlias("ucfirst", "HATUNÑAWPAQ:", "HATUNNAWPAQ:", "PRIMEROMAYUS;", "PRIMEROMAYÚS:", "UCFIRST:", "Array");
		addI18nCIAlias("lc", "UCHUY:", "MINUS:", "MINÚS:", "LC:", "Array");
		addI18nCIAlias("uc", "HATUN:", "MAYUS:", "MAYÚS:", "UC:", "Array");
		addI18nCIAlias("raw", "CHAWA:", "SINFORMATO", "SINPUNTOS", "RAW:", "Array");
		addI18nAlias("displaytitle", "SUTITARIKUCHIY", "MOSTRARTÍTULO", "MOSTRARTITULO", "DISPLAYTITLE", "Array");
		addI18nAlias("currentversion", "KUNANMUSUQCHASQA", "REVISIÓNACTUAL", "VERSIONACTUAL", "VERSIÓNACTUAL", "CURRENTVERSION", "Array");
		addI18nCIAlias("urlencode", "URLLLAWICHAY", "URL-LLAWICHAY", "CODIFICAR", "CODIFICARURL:", "URLENCODE:", "Array");
		addI18nCIAlias("anchorencode", "WATANALLAWICHAY", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "KUNANPACHAQILLPA", "MARCADEHORAACTUAL", "CURRENTTIMESTAMP", "Array");
		addI18nAlias("localtimestamp", "KAYLLAPACHAQILLPA", "MARCADEHORALOCAL", "LOCALTIMESTAMP", "Array");
		addI18nAlias("directionmark", "PURIRIYSANANCHA", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#RIMAY:", "#IDIOMA:", "#LANGUAGE:", "Array");
		addI18nAlias("contentlanguage", "SAMIQRIMAY", "IDIOMADELCONTENIDO", "IDIOMADELCONT", "CONTENTLANGUAGE", "CONTENTLANG", "Array");
		addI18nAlias("pagesinnamespace", "SUTIKITIPIPANQAKUNA:", "PÁGINASENESPACIO", "PAGESINNAMESPACE:", "PAGESINNS:", "Array");
		addI18nAlias("numberofadmins", "HAYKAKAMACHIQ", "NÚMEROADMINISITRADORES", "NÚMEROADMINS", "NUMEROADMINS", "NUMEROADMINISTRADORES", "NUMERODEADMINISTRADORES", "NUMERODEADMINS", "NÚMERODEADMINISTRADORES", "NÚMERODEADMINS", "NÚMEROADMINIISTRADORES", "NUMBEROFADMINS", "Array");
		addI18nCIAlias("formatnum", "YUPAYRIKCHAKUY", "FORMATONÚMERO", "FORMATONUMERO", "FORMATNUM", "Array");
		addI18nCIAlias("padleft", "PADLLUQI", "PADICHUQ", "PADLEFT");
		addI18nCIAlias("padright", "PADPAÑA", "PADALLIQ", "PADRIGHT");
		addI18nCIAlias("special", "sapaq", "especial", "special", "Array");
		addI18nAlias("defaultsort", "ALLINCHAY:", "SIQINCHAY:", "ORDENAR:", "ORDENPREDETERMINADO:", "CLAVEDEORDENPREDETERMINADO:", "ORDENDECATEGORIAPREDETERMINADO:", "ORDENDECATEGORÍAPREDETERMINADO:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:", "Array");
		addI18nCIAlias("filepath", "WILLAÑIQIÑAN", "WILLANIQINAN", "RUTAARCHIVO", "RUTARCHIVO", "RUTAARCHIVO:", "RUTARCHIVO:", "RUTADEARCHIVO:", "FILEPATH:", "Array");
		addI18nCIAlias("tag", "unanchacha", "UNANCHACHA", "etiqueta", "ETIQUETA", "tag", "Array");
		addI18nAlias("hiddencat", "__PAKASQAKATIGURIYA__", "__CATEGORÍAOCULTA__", "__HIDDENCAT__", "Array");
		addI18nAlias("pagesincategory", "KATIGURIYAPIPANQAKUNA", "PÁGINASENCATEGORÍA", "PÁGINASENCAT", "PAGSENCAT", "PAGINASENCATEGORIA", "PAGINASENCAT", "PAGESINCATEGORY", "PAGESINCAT", "Array");
		addI18nAlias("pagesize", "PANQACHHIKAN", "PANQACHIKAN", "PANQACHIKA", "TAMAÑOPÁGINA", "TAMAÑODEPÁGINA", "TAMAÑOPAGINA", "TAMAÑODEPAGINA", "PAGESIZE", "Array");
		addI18nAlias("index", "__UNANCHAY__", "__INDEXAR__", "__INDEX__", "Array");
		addI18nAlias("noindex", "__AMAUNANCHAYCHU__", "__NOINDEXAR__", "__NOINDEX__", "Array");
		addI18nAlias("numberingroup", "HUÑUPIYUPAY", "HUNUPIYUPAY", "NÚMEROENGRUPO", "NUMEROENGRUPO", "NUMENGRUPO", "NÚMENGRUPO", "NUMBERINGROUP", "NUMINGROUP", "Array");
		addI18nAlias("staticredirect", "__TIYAQLLAPUSAPUNA__", "__REDIRECCIONESTATICA__", "__REDIRECCIÓNESTÁTICA__", "__STATICREDIRECT__", "Array");
		addI18nAlias("protectionlevel", "HAYKAAMACHAY", "IMASINCHIAMACHAY", "NIVELDEPROTECCIÓN", "PROTECTIONLEVEL", "Array");
		addI18nAlias("currentmonth1", "MESACTUAL1", "CURRENTMONTH1");
		addI18nAlias("localmonth1", "MESLOCAL1", "LOCALMONTH1");
		addI18nAlias("namespacenumber", "NÚMERODELESPACIO", "NAMESPACENUMBER");
		addI18nAlias("rootpagename", "NOMBREDEPAGINARAIZ", "NOMBREDEPÁGINARAÍZ", "ROOTPAGENAME");
		addI18nAlias("rootpagenamee", "NOMBREDEPAGINARAIZC", "NOMBREDEPÁGINARAÍZC", "ROOTPAGENAMEE");
		addI18nCIAlias("stylepath", "RUTAESTILO", "RUTADEESTILO", "STYLEPATH");
		addI18nCIAlias("canonicalurl", "URLCANONICA:", "CANONICALURL:");
		addI18nCIAlias("canonicalurle", "URLCANONICAC:", "CANONICALURLE:");
		addI18nAlias("rawsuffix", "SF", "R");
		addI18nAlias("newsectionlink", "__VINCULARANUEVASECCION__", "__ENLACECREARSECCIÓN__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__NOVINCULARANUEVASECCION__", "__SINENLACECREARSECCIÓN__", "__NONEWSECTIONLINK__");
		addI18nCIAlias("formatdate", "formatodefecha", "formatearfecha", "formatdate", "dateformat");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://qug.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "qug";
	}
}
