/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class RueConfig extends TemplateConfig {
	public RueConfig() {
		addNamespaceAlias(-2, "Медіа", "Медіа", "Медиа");
		addNamespaceAlias(-1, "Шпеціална", "Спеціальна", "Спеціальні", "Служебная");
		addNamespaceAlias(1, "Діскузія", "Діскузіа", "Обговорення", "Обсуждение");
		addNamespaceAlias(2, "Хоснователь", "Користувач", "Участник", "Участник", "Участница");
		addNamespaceAlias(3, "Діскузія_з_хоснователём", "Діскузіа_з_хоснователём", "Обговорення_користувача", "Обсуждение_участника", "Обсуждение_участника", "Обсуждение_участницы");
		addNamespaceAlias(5, "Діскузія_ку_{{grammar:3sg|Wikipedia}}", "Обговорення_{{GRAMMAR:genitive|Wikipedia}}", "Обсуждение_{{GRAMMAR:genitive|Wikipedia}}");
		addNamespaceAlias(6, "Файл", "Файл", "Зображення", "Файл", "Изображение");
		addNamespaceAlias(7, "Діскузія_ку_файлу", "Обговорення_файлу", "Обговорення_зображення", "Обсуждение_файла", "Обсуждение_изображения");
		addNamespaceAlias(8, "MediaWiki", "MediaWiki", "MediaWiki");
		addNamespaceAlias(9, "Діскузія_ку_MediaWiki", "Дізкузія_ку_MediaWiki", "Обговорення_MediaWiki", "Обсуждение_MediaWiki");
		addNamespaceAlias(10, "Шаблона", "Шаблон", "Шаблон");
		addNamespaceAlias(11, "Діскузія_ку_шаблонї", "Обговорення_шаблону", "Обговорення_шаблона", "Обсуждение_шаблона");
		addNamespaceAlias(12, "Поміч", "Довідка", "Справка");
		addNamespaceAlias(13, "Діскузія_ку_помочі", "Обговорення_довідки", "Обсуждение_справки");
		addNamespaceAlias(14, "Катеґорія", "Категорія", "Категория");
		addNamespaceAlias(15, "Діскузія_ку_катеґорії", "Обговорення_категорії", "Обсуждение_категории");

		addI18nCIAlias("redirect", "#ПЕРЕНАПРАВЛЕННЯ", "#ПЕРЕНАПР", "#перенапр", "#перенаправление", "#REDIRECT", "Array");
		addI18nCIAlias("notoc", "__БЕЗ_ЗМІСТУ__", "__БЕЗ_ОГЛАВЛЕНИЯ__", "__БЕЗ_ОГЛ__", "__NOTOC__", "Array");
		addI18nCIAlias("nogallery", "__БЕЗ_ГАЛЕРЕЇ__", "__БЕЗ_ГАЛЕРЕИ__", "__NOGALLERY__", "Array");
		addI18nCIAlias("forcetoc", "__ОБОВ_ЗМІСТ__", "__ОБЯЗАТЕЛЬНОЕ_ОГЛАВЛЕНИЕ__", "__ОБЯЗ_ОГЛ__", "__FORCETOC__", "Array");
		addI18nCIAlias("toc", "__ЗМІСТ__", "__ОГЛАВЛЕНИЕ__", "__ОГЛ__", "__TOC__", "Array");
		addI18nCIAlias("noeditsection", "__БЕЗ_РЕДАГУВ_РОЗДІЛУ__", "__БЕЗ_РЕДАКТИРОВАНИЯ_РАЗДЕЛА__", "__NOEDITSECTION__", "Array");
		addI18nAlias("currentmonth", "ПОТОЧНИЙ_МІСЯЦЬ", "ПОТОЧНИЙ_МІСЯЦЬ_2", "ТЕКУЩИЙ_МЕСЯЦ", "ТЕКУЩИЙ_МЕСЯЦ_2", "CURRENTMONTH", "CURRENTMONTH2", "Array");
		addI18nAlias("currentmonth1", "ПОТОЧНИЙ_МІСЯЦЬ_1", "ТЕКУЩИЙ_МЕСЯЦ_1", "CURRENTMONTH1", "Array");
		addI18nAlias("currentmonthname", "НАЗВА_ПОТОЧНОГО_МІСЯЦЯ", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА", "CURRENTMONTHNAME", "Array");
		addI18nAlias("currentmonthnamegen", "НАЗВА_ПОТОЧНОГО_МІСЯЦЯ_РОД", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_РОД", "CURRENTMONTHNAMEGEN", "Array");
		addI18nAlias("currentmonthabbrev", "НАЗВА_ПОТОЧНОГО_МІСЯЦЯ_АБР", "НАЗВАНИЕ_ТЕКУЩЕГО_МЕСЯЦА_АБР", "CURRENTMONTHABBREV", "Array");
		addI18nAlias("currentday", "ПОТОЧНИЙ_ДЕНЬ", "ТЕКУЩИЙ_ДЕНЬ", "CURRENTDAY", "Array");
		addI18nAlias("currentday2", "ПОТОЧНИЙ_ДЕНЬ_2", "ТЕКУЩИЙ_ДЕНЬ_2", "CURRENTDAY2", "Array");
		addI18nAlias("currentdayname", "НАЗВА_ПОТОЧНОГО_ДНЯ", "НАЗВАНИЕ_ТЕКУЩЕГО_ДНЯ", "CURRENTDAYNAME", "Array");
		addI18nAlias("currentyear", "ПОТОЧНИЙ_РІК", "ТЕКУЩИЙ_ГОД", "CURRENTYEAR", "Array");
		addI18nAlias("currenttime", "ПОТОЧНИЙ_ЧАС", "ТЕКУЩЕЕ_ВРЕМЯ", "CURRENTTIME", "Array");
		addI18nAlias("currenthour", "ПОТОЧНА_ГОДИНА", "ТЕКУЩИЙ_ЧАС", "CURRENTHOUR", "Array");
		addI18nAlias("localmonth", "ЛОКАЛЬНИЙ_МІСЯЦЬ", "ЛОКАЛЬНИЙ_МІСЯЦЬ_2", "МЕСТНЫЙ_МЕСЯЦ", "МЕСТНЫЙ_МЕСЯЦ_2", "LOCALMONTH", "LOCALMONTH2", "Array");
		addI18nAlias("localmonth1", "ЛОКАЛЬНИЙ_МІСЯЦЬ_1", "МЕСТНЫЙ_МЕСЯЦ_1", "LOCALMONTH1", "Array");
		addI18nAlias("localmonthname", "НАЗВА_ЛОКАЛЬНОГО_МІСЯЦЯ", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА", "LOCALMONTHNAME", "Array");
		addI18nAlias("localmonthnamegen", "НАЗВА_ЛОКАЛЬНОГО_МІСЯЦЯ_РОД", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_РОД", "LOCALMONTHNAMEGEN", "Array");
		addI18nAlias("localmonthabbrev", "НАЗВА_ЛОКАЛЬНОГО_МІСЯЦЯ_АБР", "НАЗВАНИЕ_МЕСТНОГО_МЕСЯЦА_АБР", "LOCALMONTHABBREV", "Array");
		addI18nAlias("localday", "ЛОКАЛЬНИЙ_ДЕНЬ", "МЕСТНЫЙ_ДЕНЬ", "LOCALDAY", "Array");
		addI18nAlias("localday2", "ЛОКАЛЬНИЙ_ДЕНЬ_2", "МЕСТНЫЙ_ДЕНЬ_2", "LOCALDAY2", "Array");
		addI18nAlias("localdayname", "НАЗВА_ЛОКАЛЬНОГО_ДНЯ", "НАЗВАНИЕ_МЕСТНОГО_ДНЯ", "LOCALDAYNAME", "Array");
		addI18nAlias("localyear", "ЛОКАЛЬНИЙ_РІК", "МЕСТНЫЙ_ГОД", "LOCALYEAR", "Array");
		addI18nAlias("localtime", "ЛОКАЛЬНИЙ_ЧАС", "МЕСТНОЕ_ВРЕМЯ", "LOCALTIME", "Array");
		addI18nAlias("localhour", "ЛОКАЛЬНА_ГОДИНА", "МЕСТНЫЙ_ЧАС", "LOCALHOUR", "Array");
		addI18nAlias("numberofpages", "КІЛЬКІСТЬ_СТОРІНОК", "КОЛИЧЕСТВО_СТРАНИЦ", "NUMBEROFPAGES", "Array");
		addI18nAlias("numberofarticles", "КІЛЬКІСТЬ_СТАТЕЙ", "КОЛИЧЕСТВО_СТАТЕЙ", "NUMBEROFARTICLES", "Array");
		addI18nAlias("numberoffiles", "КІЛЬКІСТЬ_ФАЙЛІВ", "КОЛИЧЕСТВО_ФАЙЛОВ", "NUMBEROFFILES", "Array");
		addI18nAlias("numberofusers", "КІЛЬКІСТЬ_КОРИСТУВАЧІВ", "КОЛИЧЕСТВО_УЧАСТНИКОВ", "NUMBEROFUSERS", "Array");
		addI18nAlias("numberofactiveusers", "КІЛЬКІСТЬ_АКТИВНИХ_КОРИСТУВАЧІВ", "КОЛИЧЕСТВО_АКТИВНЫХ_УЧАСТНИКОВ", "NUMBEROFACTIVEUSERS", "Array");
		addI18nAlias("numberofedits", "КІЛЬКІСТЬ_РЕДАГУВАНЬ", "КОЛИЧЕСТВО_ПРАВОК", "NUMBEROFEDITS", "Array");
		addI18nAlias("numberofviews", "КІЛЬКІСТЬ_ПЕРЕГЛЯДІВ", "КОЛИЧЕСТВО_ПРОСМОТРОВ", "NUMBEROFVIEWS", "Array");
		addI18nAlias("pagename", "НАЗВА_СТОРІНКИ", "НАЗВАНИЕ_СТРАНИЦЫ", "PAGENAME", "Array");
		addI18nAlias("pagenamee", "НАЗВА_СТОРІНКИ_2", "НАЗВАНИЕ_СТРАНИЦЫ_2", "PAGENAMEE", "Array");
		addI18nAlias("namespace", "ПРОСТІР_НАЗВ", "ПРОСТРАНСТВО_ИМЁН", "NAMESPACE", "Array");
		addI18nAlias("namespacee", "ПРОСТІР_НАЗВ_2", "ПРОСТРАНСТВО_ИМЁН_2", "NAMESPACEE", "Array");
		addI18nAlias("talkspace", "ПРОСТІР_ОБГОВОРЕННЯ", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ", "TALKSPACE", "Array");
		addI18nAlias("talkspacee", "ПРОСТІР_ОБГОВОРЕННЯ_2", "ПРОСТРАНСТВО_ОБСУЖДЕНИЙ_2", "TALKSPACEE", "Array");
		addI18nAlias("subjectspace", "ПРОСТІР_СТАТЕЙ", "ПРОСТРАНСТВО_СТАТЕЙ", "SUBJECTSPACE", "ARTICLESPACE", "Array");
		addI18nAlias("subjectspacee", "ПРОСТІР_СТАТЕЙ_2", "ПРОСТРАНСТВО_СТАТЕЙ_2", "SUBJECTSPACEE", "ARTICLESPACEE", "Array");
		addI18nAlias("fullpagename", "ПОВНА_НАЗВА_СТОРІНКИ", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ", "FULLPAGENAME", "Array");
		addI18nAlias("fullpagenamee", "ПОВНА_НАЗВА_СТОРІНКИ_2", "ПОЛНОЕ_НАЗВАНИЕ_СТРАНИЦЫ_2", "FULLPAGENAMEE", "Array");
		addI18nAlias("subpagename", "НАЗВА_ПІДСТОРІНКИ", "НАЗВАНИЕ_ПОДСТРАНИЦЫ", "SUBPAGENAME", "Array");
		addI18nAlias("subpagenamee", "НАЗВА_ПІДСТОРІНКИ_2", "НАЗВАНИЕ_ПОДСТРАНИЦЫ_2", "SUBPAGENAMEE", "Array");
		addI18nAlias("basepagename", "ОСНОВА_НАЗВИ_ПІДСТОРІНКИ", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ", "BASEPAGENAME", "Array");
		addI18nAlias("basepagenamee", "ОСНОВА_НАЗВИ_ПІДСТОРІНКИ_2", "ОСНОВА_НАЗВАНИЯ_СТРАНИЦЫ_2", "BASEPAGENAMEE", "Array");
		addI18nAlias("talkpagename", "НАЗВА_СТОРІНКИ_ОБГОВОРЕННЯ", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ", "TALKPAGENAME", "Array");
		addI18nAlias("talkpagenamee", "НАЗВА_СТОРІНКИ_ОБГОВОРЕННЯ_2", "НАЗВАНИЕ_СТРАНИЦЫ_ОБСУЖДЕНИЯ_2", "TALKPAGENAMEE", "Array");
		addI18nAlias("subjectpagename", "НАЗВА_СТАТТІ", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ", "SUBJECTPAGENAME", "ARTICLEPAGENAME", "Array");
		addI18nAlias("subjectpagenamee", "НАЗВА_СТАТТІ_2", "НАЗВАНИЕ_СТРАНИЦЫ_СТАТЬИ_2", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE", "Array");
		addI18nCIAlias("msg", "ПОВІД:", "ПОВІДОМЛЕННЯ:", "СООБЩЕНИЕ:", "СООБЩ:", "MSG:", "Array");
		addI18nCIAlias("subst", "ПІДСТ:", "ПІДСТАНОВКА:", "ПОДСТАНОВКА:", "ПОДСТ:", "SUBST:", "Array");
		addI18nCIAlias("safesubst", "БЕЗПЕЧНА_ПІДСТАНОВКА:", "ЗАЩПОДСТ:", "SAFESUBST:", "Array");
		addI18nCIAlias("msgnw", "ПОВІД_БЕЗ_ВІКІ:", "СООБЩ_БЕЗ_ВИКИ:", "MSGNW:", "Array");
		addI18nAlias("img_thumbnail", "міні", "мініатюра", "мини", "миниатюра", "thumbnail", "thumb", "Array");
		addI18nAlias("img_manualthumb", "міні=$1", "мініатюра=$1", "мини=$1", "миниатюра=$1", "thumbnail=$1", "thumb=$1", "Array");
		addI18nAlias("img_right", "праворуч", "справа", "right", "Array");
		addI18nAlias("img_left", "ліворуч", "слева", "left", "Array");
		addI18nAlias("img_none", "без", "none", "Array");
		addI18nAlias("img_width", "$1пкс", "$1px", "Array");
		addI18nAlias("img_center", "центр", "center", "centre", "Array");
		addI18nAlias("img_framed", "обрамити", "рамка", "обрамить", "framed", "enframed", "frame", "Array");
		addI18nAlias("img_frameless", "безрамки", "frameless", "Array");
		addI18nAlias("img_page", "сторінка=$1", "сторінка_$1", "страница=$1", "страница_$1", "страница $1", "page=$1", "page $1", "Array");
		addI18nAlias("img_upright", "зверхуправоруч", "зверхуправоруч=$1", "зверхуправоруч_$1", "сверхусправа", "сверхусправа=$1", "сверхусправа_$1", "сверхусправа $1", "upright", "upright=$1", "upright $1", "Array");
		addI18nAlias("img_border", "межа", "граница", "border", "Array");
		addI18nAlias("img_baseline", "основа", "основание", "baseline", "Array");
		addI18nAlias("img_sub", "під", "под", "sub", "Array");
		addI18nAlias("img_super", "над", "super", "sup", "Array");
		addI18nAlias("img_top", "зверху", "сверху", "top", "Array");
		addI18nAlias("img_text_top", "текст-зверху", "текст-сверху", "text-top", "Array");
		addI18nAlias("img_middle", "посередині", "посередине", "middle", "Array");
		addI18nAlias("img_bottom", "знизу", "снизу", "bottom", "Array");
		addI18nAlias("img_text_bottom", "текст-знизу", "текст-снизу", "text-bottom", "Array");
		addI18nAlias("img_link", "посилання=$1", "ссылка=$1", "link=$1", "Array");
		addI18nAlias("img_alt", "альт=$1", "alt=$1", "Array");
		addI18nCIAlias("int", "ВНУТР:", "INT:", "Array");
		addI18nAlias("sitename", "НАЗВА_САЙТУ", "НАЗВАНИЕ_САЙТА", "SITENAME", "Array");
		addI18nCIAlias("ns", "ПН:", "ПИ:", "NS:", "Array");
		addI18nCIAlias("nse", "ПН_2:", "ПИК:", "NSE:", "Array");
		addI18nCIAlias("localurl", "ЛОКАЛЬНА_АДРЕСА:", "ЛОКАЛЬНЫЙ_АДРЕС:", "LOCALURL:", "Array");
		addI18nCIAlias("localurle", "ЛОКАЛЬНА_АДРЕСА_2:", "ЛОКАЛЬНЫЙ_АДРЕС_2:", "LOCALURLE:", "Array");
		addI18nCIAlias("server", "СЕРВЕР", "SERVER", "Array");
		addI18nCIAlias("servername", "НАЗВА_СЕРВЕРА", "НАЗВАНИЕ_СЕРВЕРА", "SERVERNAME", "Array");
		addI18nCIAlias("scriptpath", "ШЛЯХ_ДО_СКРИПТУ", "ПУТЬ_К_СКРИПТУ", "SCRIPTPATH", "Array");
		addI18nCIAlias("stylepath", "ШЛЯХ_ДО_СТИЛЮ", "ПУТЬ_К_СТИЛЮ", "STYLEPATH", "Array");
		addI18nCIAlias("grammar", "ВІДМІНОК:", "ПАДЕЖ:", "GRAMMAR:", "Array");
		addI18nCIAlias("gender", "СТАТЬ:", "ПОЛ:", "GENDER:", "Array");
		addI18nCIAlias("notitleconvert", "__БЕЗ_ПЕРЕТВОРЕННЯ_ЗАГОЛОВКУ__", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ЗАГОЛОВКА__", "__NOTITLECONVERT__", "__NOTC__", "Array");
		addI18nCIAlias("nocontentconvert", "__БЕЗ_ПЕРЕТВОРЕННЯ_ТЕКСТУ__", "__БЕЗ_ПРЕОБРАЗОВАНИЯ_ТЕКСТА__", "__NOCONTENTCONVERT__", "__NOCC__", "Array");
		addI18nAlias("currentweek", "ПОТОЧНИЙ_ТИЖДЕНЬ", "ТЕКУЩАЯ_НЕДЕЛЯ", "CURRENTWEEK", "Array");
		addI18nAlias("currentdow", "ПОТОЧНИЙ_ДЕНЬ_ТИЖНЯ", "ТЕКУЩИЙ_ДЕНЬ_НЕДЕЛИ", "CURRENTDOW", "Array");
		addI18nAlias("localweek", "ЛОКАЛЬНИЙ_ТИЖДЕНЬ", "МЕСТНАЯ_НЕДЕЛЯ", "LOCALWEEK", "Array");
		addI18nAlias("localdow", "ЛОКАЛЬНИЙ_ДЕНЬ_ТИЖНЯ", "МЕСТНЫЙ_ДЕНЬ_НЕДЕЛИ", "LOCALDOW", "Array");
		addI18nAlias("revisionid", "ІД_ВЕРСІЇ", "ИД_ВЕРСИИ", "REVISIONID", "Array");
		addI18nAlias("revisionday", "ДЕНЬ_ВЕРСІЇ", "ДЕНЬ_ВЕРСИИ", "REVISIONDAY", "Array");
		addI18nAlias("revisionday2", "ДЕНЬ_ВЕРСІЇ_2", "ДЕНЬ_ВЕРСИИ_2", "REVISIONDAY2", "Array");
		addI18nAlias("revisionmonth", "МІСЯЦЬ_ВЕРСІЇ", "МЕСЯЦ_ВЕРСИИ", "REVISIONMONTH", "Array");
		addI18nAlias("revisionmonth1", "МІСЯЦЬ_ВЕРСІЇ_1", "МЕСЯЦ_ВЕРСИИ_1", "REVISIONMONTH1", "Array");
		addI18nAlias("revisionyear", "РІК_ВЕРСІЇ", "ГОД_ВЕРСИИ", "REVISIONYEAR", "Array");
		addI18nAlias("revisiontimestamp", "МІТКА_ЧАСУ_ВЕРСІЇ", "ОТМЕТКА_ВРЕМЕНИ_ВЕРСИИ", "REVISIONTIMESTAMP", "Array");
		addI18nAlias("revisionuser", "ВЕРСІЯ_КОРИСТУВАЧА", "ВЕРСИЯ_УЧАСТНИКА", "REVISIONUSER", "Array");
		addI18nCIAlias("plural", "МНОЖИНА:", "МНОЖЕСТВЕННОЕ_ЧИСЛО:", "PLURAL:", "Array");
		addI18nCIAlias("fullurl", "ПОВНА_АДРЕСА:", "ПОЛНЫЙ_АДРЕС:", "FULLURL:", "Array");
		addI18nCIAlias("fullurle", "ПОВНА_АДРЕСА_2:", "ПОЛНЫЙ_АДРЕС_2:", "FULLURLE:", "Array");
		addI18nCIAlias("lcfirst", "НР_ПЕРША:", "ПЕРША_БУКВА_МАЛА:", "ПЕРВАЯ_БУКВА_МАЛЕНЬКАЯ:", "LCFIRST:", "Array");
		addI18nCIAlias("ucfirst", "ВР_ПЕРША:", "ПЕРША_БУКВА_ВЕЛИКА:", "ПЕРВАЯ_БУКВА_БОЛЬШАЯ:", "UCFIRST:", "Array");
		addI18nCIAlias("lc", "НР:", "НИЖНІЙ_РЕГІСТР:", "МАЛИМИ_БУКВАМИ:", "МАЛЕНЬКИМИ_БУКВАМИ:", "LC:", "Array");
		addI18nCIAlias("uc", "ВР:", "ВЕРХНІЙ_РЕГІСТР:", "ВЕЛИКИМИ_БУКВАМИ:", "БОЛЬШИМИ_БУКВАМИ:", "UC:", "Array");
		addI18nCIAlias("raw", "НЕОБРОБ:", "НЕОБРАБ:", "RAW:", "Array");
		addI18nAlias("displaytitle", "ПОКАЗАТИ_ЗАГОЛОВОК", "ПОКАЗАТЬ_ЗАГОЛОВОК", "DISPLAYTITLE", "Array");
		addI18nAlias("rawsuffix", "Н", "R", "Array");
		addI18nAlias("newsectionlink", "__ПОСИЛАННЯ_НА_НОВИЙ_РОЗДІЛ__", "__ССЫЛКА_НА_НОВЫЙ_РАЗДЕЛ__", "__NEWSECTIONLINK__", "Array");
		addI18nAlias("nonewsectionlink", "__БЕЗ_ПОСИЛАННЯ_НА_НОВИЙ_РОЗДІЛ__", "__БЕЗ_ССЫЛКИ_НА_НОВЫЙ_РАЗДЕЛ__", "__NONEWSECTIONLINK__", "Array");
		addI18nAlias("currentversion", "ПОТОЧНА_ВЕРСІЯ", "ТЕКУЩАЯ_ВЕРСИЯ", "CURRENTVERSION", "Array");
		addI18nCIAlias("urlencode", "ЗАКОДОВАНА_АДРЕСА:", "ЗАКОДИРОВАННЫЙ_АДРЕС:", "URLENCODE:", "Array");
		addI18nCIAlias("anchorencode", "КОДУВАТИ_МІТКУ", "КОДИРОВАТЬ_МЕТКУ", "ANCHORENCODE", "Array");
		addI18nAlias("currenttimestamp", "МІТКА_ПОТОЧНОГО_ЧАСУ", "ОТМЕТКА_ТЕКУЩЕГО_ВРЕМЕНИ", "CURRENTTIMESTAMP", "Array");
		addI18nAlias("localtimestamp", "МІТКА_ЛОКАЛЬНОГО_ЧАСУ", "ОТМЕТКА_МЕСТНОГО_ВРЕМЕНИ", "LOCALTIMESTAMP", "Array");
		addI18nAlias("directionmark", "НАПРЯМОК_ПИСЬМА", "НАПРАВЛЕНИЕ_ПИСЬМА", "DIRECTIONMARK", "DIRMARK", "Array");
		addI18nCIAlias("language", "#МОВА:", "#ЯЗЫК:", "#LANGUAGE:", "Array");
		addI18nAlias("contentlanguage", "МОВА_ВМІСТУ", "ЯЗЫК_СОДЕРЖАНИЯ", "CONTENTLANGUAGE", "CONTENTLANG", "Array");
		addI18nAlias("pagesinnamespace", "СТОРІНОК_У_ПРОСТОРІ_НАЗВ:", "СТРАНИЦ_В_ПРОСТРАНСТВЕ_ИМЁН:", "PAGESINNAMESPACE:", "PAGESINNS:", "Array");
		addI18nAlias("numberofadmins", "КІЛЬКІСТЬ_АДМІНІСТРАТОРІВ", "КОЛИЧЕСТВО_АДМИНИСТРАТОРОВ", "NUMBEROFADMINS", "Array");
		addI18nCIAlias("formatnum", "ФОРМАТУВАТИ_ЧИСЛО", "ФОРМАТИРОВАТЬ_ЧИСЛО", "FORMATNUM", "Array");
		addI18nCIAlias("padleft", "ЗАПОВНИТИ_ЛІВОРУЧ", "ЗАПОЛНИТЬ_СЛЕВА", "PADLEFT", "Array");
		addI18nCIAlias("padright", "ЗАПОВНИТИ_ПРАВОРУЧ", "ЗАПОЛНИТЬ_СПРАВА", "PADRIGHT", "Array");
		addI18nCIAlias("special", "спеціальна", "служебная", "special", "Array");
		addI18nAlias("defaultsort", "СТАНДАРТНЕ_СОРТУВАННЯ:", "СОРТУВАННЯ:", "СОРТИРОВКА_ПО_УМОЛЧАНИЮ", "КЛЮЧ_СОРТИРОВКИ", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:", "Array");
		addI18nCIAlias("filepath", "ШЛЯХ_ДО_ФАЙЛУ:", "ПУТЬ_К_ФАЙЛУ:", "FILEPATH:", "Array");
		addI18nCIAlias("tag", "тег", "мітка", "метка", "тэг", "tag", "Array");
		addI18nAlias("hiddencat", "__ПРИХОВ_КАТ__", "__СКРЫТАЯ_КАТЕГОРИЯ__", "__HIDDENCAT__", "Array");
		addI18nAlias("pagesincategory", "СТОР_В_КАТ", "СТОР_У_КАТ", "СТРАНИЦ_В_КАТЕГОРИИ", "PAGESINCATEGORY", "PAGESINCAT", "Array");
		addI18nAlias("pagesize", "РОЗМІР", "РОЗМІР_СТОРІНКИ", "РАЗМЕР_СТРАНИЦЫ", "PAGESIZE", "Array");
		addI18nAlias("index", "__ІНДЕКС__", "__ИНДЕКС__", "__INDEX__", "Array");
		addI18nAlias("noindex", "__БЕЗ_ІНДЕКСУ__", "__БЕЗ_ИНДЕКСА__", "__NOINDEX__", "Array");
		addI18nAlias("numberingroup", "КІЛЬКІСТЬ_У_ГРУПІ", "ЧИСЛО_В_ГРУППЕ", "NUMBERINGROUP", "NUMINGROUP", "Array");
		addI18nAlias("staticredirect", "__СТАТИЧНЕ_ПЕРЕНАПРАВЛЕННЯ__", "__СТАТИЧЕСКОЕ_ПЕРЕНАПРАВЛЕНИЕ__", "__STATICREDIRECT__", "Array");
		addI18nAlias("protectionlevel", "РІВЕНЬ_ЗАХИСТУ", "УРОВЕНЬ_ЗАЩИТЫ", "PROTECTIONLEVEL", "Array");
		addI18nCIAlias("formatdate", "форматдати", "форматдаты", "formatdate", "dateformat", "Array");
		addI18nCIAlias("url_path", "ШЛЯХ", "ПУТЬ", "PATH", "Array");
		addI18nCIAlias("url_wiki", "ВІКІ", "ВИКИ", "WIKI", "Array");
		addI18nCIAlias("url_query", "ЗАПИТ", "ЗАПРОС", "QUERY", "Array");
		addI18nAlias("namespacenumber", "НОМЕР_ПРОСТРАНСТВА_ИМЁН", "NAMESPACENUMBER");
		addI18nCIAlias("articlepath", "ПУТЬ_К_СТАТЬЕ", "ARTICLEPATH");
		addI18nCIAlias("pageid", "ИДЕНТИФИКАТОР_СТРАНИЦЫ", "PAGEID");
		addI18nCIAlias("pagesincategory_all", "все", "all");
		addI18nCIAlias("pagesincategory_pages", "страницы", "pages");
		addI18nCIAlias("pagesincategory_subcats", "подкатегории", "subcats");
		addI18nCIAlias("pagesincategory_files", "файлы", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://rue.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "rue";
	}
}
