/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class SaConfig extends TemplateConfig {
	public SaConfig() {
		addNamespaceAlias(-2, "माध्यमम्", "माध्यम", "मीडिया");
		addNamespaceAlias(-1, "विशेषम्", "विशेष", "विशेष");
		addNamespaceAlias(1, "सम्भाषणम्", "संभाषणं", "वार्ता");
		addNamespaceAlias(2, "योजकः", "सदस्य");
		addNamespaceAlias(3, "योजकसम्भाषणम्", "योजकसंभाषणं", "सदस्य_वार्ता");
		addNamespaceAlias(5, "Wikipediaसम्भाषणम्", "Wikipediaसंभाषणं", "Wikipedia_वार्ता");
		addNamespaceAlias(6, "चित्रम्", "चित्रं", "चित्र");
		addNamespaceAlias(7, "चित्रसम्भाषणम्", "चित्रसंभाषणं", "चित्र_वार्ता");
		addNamespaceAlias(8, "मिडीयाविकी", "मीडियाविकि");
		addNamespaceAlias(9, "मिडियाविकीसम्भाषणम्", "मिडियाविकीसंभाषणं", "मीडियाविकि_वार्ता");
		addNamespaceAlias(10, "फलकम्", "बिंबधर", "साँचा");
		addNamespaceAlias(11, "फलकस्य_सम्भाषणम्", "बिंबधर संभाषणं", "साँचा_वार्ता");
		addNamespaceAlias(12, "सहाय्यम्", "सहाय्य", "उपकारः", "सहायता");
		addNamespaceAlias(13, "सहाय्यस्य_सम्भाषणम्", "सहाय्यसंभाषणं", "उपकारसंभाषणं", "सहायता_वार्ता");
		addNamespaceAlias(14, "वर्गः", "श्रेणी");
		addNamespaceAlias(15, "वर्गसम्भाषणम्", "वर्गसंभाषणं", "श्रेणी_वार्ता");

		addI18nCIAlias("redirect", "#पुनर्निदेशन", "#अनुप्रेषित", "#REDIRECT", "Array");
		addI18nCIAlias("notoc", "__नैवअनुक्रमणी__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__नैवसंक्रमणका__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__अनुक्रमणीसचते__", "__FORCETOC__");
		addI18nCIAlias("toc", "__अनुक्रमणी__", "__TOC__");
		addI18nCIAlias("noeditsection", "__नैवसम्पादनविभाग__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "अद्यमासे", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonthname", "अद्यमासेनाम", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "अद्यमासेनामसाधारण", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "अद्यमासेसंक्षीप्त", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "अद्यदिवसे", "CURRENTDAY");
		addI18nAlias("currentday2", "अद्यदिवसे२", "CURRENTDAY2");
		addI18nAlias("currentdayname", "अद्यदिवसेनाम", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "अद्यवर्ष", "CURRENTYEAR");
		addI18nAlias("currenttime", "सद्यसमय", "CURRENTTIME");
		addI18nAlias("currenthour", "सद्यघण्टा", "CURRENTHOUR");
		addI18nAlias("localmonth", "स्थानिकमासे", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonthname", "स्थानिकमासेनाम", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "स्थानिकमासेनामसाधारण", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "स्थानिकमासेसंक्षीप्त", "LOCALMONTHABBREV");
		addI18nAlias("localday", "स्थानिकदिवसे", "LOCALDAY");
		addI18nAlias("localday2", "स्थानिकदिवसे२", "LOCALDAY2");
		addI18nAlias("localdayname", "स्थानिकदिवसेनाम", "LOCALDAYNAME");
		addI18nAlias("localyear", "स्थानिकवर्षे", "LOCALYEAR");
		addI18nAlias("localtime", "स्थानिकसमये", "LOCALTIME");
		addI18nAlias("localhour", "स्थानिकघण्टा", "LOCALHOUR");
		addI18nAlias("numberofpages", "पृष्ठानाम्‌सङ्ख्या", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "लेखस्य‌सङ्ख्या", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "संचिकानाम्‌‌सङ्ख्या", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "योजकस्यसङ्ख्या", "NUMBEROFUSERS");
		addI18nAlias("numberofedits", "सम्पादनसङ्ख्या", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "दृष्टिसङ्ख्या", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "पृष्ठनाम", "PAGENAME");
		addI18nAlias("namespace", "नामविश्व", "NAMESPACE");
		addI18nAlias("talkspace", "व्यासपिठ", "TALKSPACE");
		addI18nAlias("subjectspace", "विषयविश्व", "लेखविश्व", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("fullpagename", "पूर्णपृष्ठनाम", "FULLPAGENAME");
		addI18nAlias("subpagename", "उपपृष्ठनाम", "SUBPAGENAME");
		addI18nAlias("basepagename", "आधारपृष्ठनाम", "BASEPAGENAME");
		addI18nAlias("talkpagename", "संवादपृष्ठनाम", "TALKPAGENAME");
		addI18nAlias("subjectpagename", "विषयपृष्ठनाम", "लेखपृष्ठनाम", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nCIAlias("msg", "सन्देश:", "MSG:");
		addI18nCIAlias("msgnw", "नूतनसन्देश:", "MSGNW:");
		addI18nAlias("img_thumbnail", "लघुत्तम", "सङ्कुचितचित्र", "अङ्गुष्ठ", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "सङ्कुचितचित्र=$1", "अङ्गुष्ठ=$1", "लघुत्तमचित्र=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "दक्षिणत", "right");
		addI18nAlias("img_left", "वामतः", "left");
		addI18nAlias("img_none", "नैव", "none");
		addI18nAlias("img_width", "$1पिट", "$1px");
		addI18nAlias("img_center", "मध्य", "center", "centre");
		addI18nAlias("img_framed", "आबन्ध", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "निराबन्ध", "frameless");
		addI18nAlias("img_page", "पृष्ठ=$1", "पृष्ठ $1", "page=$1", "page $1");
		addI18nAlias("img_upright", "उन्नत", "उन्नत=$1", "उन्नत $1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "सीमा", "border");
		addI18nAlias("img_baseline", "आधाररेखा", "baseline");
		addI18nAlias("img_sub", "विषये", "sub");
		addI18nAlias("img_super", "अति", "तीव्र", "super", "sup");
		addI18nAlias("img_top", "अग्र", "top");
		addI18nAlias("img_text_top", "पाठ्य-अग्र", "text-top");
		addI18nAlias("img_middle", "मध्ये", "middle");
		addI18nAlias("img_bottom", "अधस", "bottom");
		addI18nAlias("img_text_bottom", "पाठ्य-अधस", "text-bottom");
		addI18nAlias("img_link", "सम्बद्धं=$1", "link=$1");
		addI18nAlias("img_alt", "विकल्प=$1", "alt=$1");
		addI18nAlias("sitename", "स्थलनाम", "SITENAME");
		addI18nCIAlias("grammar", "व्याकरण:", "GRAMMAR:");
		addI18nCIAlias("notitleconvert", "__नैवशिर्षकपरिवर्त__", "__नैशिप__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__नैवलेखपरिवर्त__", "__नैलेप__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "अद्यसप्ताह", "CURRENTWEEK");
		addI18nAlias("localweek", "स्थानिकसप्ताह", "LOCALWEEK");
		addI18nAlias("revisionid", "आवृत्तीक्रमांक", "REVISIONID");
		addI18nAlias("revisionday", "आवृत्तीदिवसे", "REVISIONDAY");
		addI18nAlias("revisionday2", "आवृत्तीदिवसे२", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "आवृत्तीमासे", "REVISIONMONTH");
		addI18nAlias("revisionyear", "आवृत्तीवर्षे", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "आवृत्तीसमयमुद्रा", "REVISIONTIMESTAMP");
		addI18nCIAlias("plural", "अनेकवचन:", "PLURAL:");
		addI18nAlias("displaytitle", "प्रदर्शनशीर्षक", "उपाधिदर्शन", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "__नूतनविभागसम्बद्धं__", "__NEWSECTIONLINK__");
		addI18nAlias("currentversion", "अद्यआवृत्ती", "CURRENTVERSION");
		addI18nAlias("currenttimestamp", "सद्यसमयमुद्रा", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "स्थानिकसमयमुद्रा", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "दिशाचिह्न", "दिशे", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#भाषा:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "विषयभाषा", "आधेयभाषा", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "नामविश्वातपृष्ठ", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "प्रचालकसंख्या", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "रचनासंख्या", "FORMATNUM");
		addI18nCIAlias("special", "विशेष", "special");
		addI18nCIAlias("filepath", "संचिकापथ", "FILEPATH:");
		addI18nCIAlias("tag", "वीजक", "tag");
		addI18nAlias("hiddencat", "__लुप्तवर्ग__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "वर्गेपृष्ठ", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "पृष्ठाकार", "PAGESIZE");
		addI18nAlias("index", "__अनुक्रमणिका__", "__INDEX__");
		addI18nAlias("noindex", "__नैवअनुक्रमणिका__", "__NOINDEX__");
		addI18nAlias("numberingroup", "गणानामसंख्या", "गणसंख्या", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__अनित्यपुनर्निदेशन__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "रक्षास्तर", "PROTECTIONLEVEL");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://sa.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "sa";
	}
}
