/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class ScConfig extends TemplateConfig {
	public ScConfig() {
		addNamespaceAlias(-1, "Ispetziale", "Speciale");
		addNamespaceAlias(1, "Cuntierra", "Contièndha");
		addNamespaceAlias(2, "Usuàriu", "Utente");
		addNamespaceAlias(3, "Cuntierra_usuàriu", "Utente_discussioni");
		addNamespaceAlias(5, "Cuntierra_Wikipedia", "Wikipedia_discussioni");
		addNamespaceAlias(6, "File", "Immàgini");
		addNamespaceAlias(7, "Cuntierra_file", "Immàgini_contièndha");
		addNamespaceAlias(9, "Cuntierra_MediaWiki");
		addNamespaceAlias(11, "Cuntierra_template");
		addNamespaceAlias(12, "Agiudu");
		addNamespaceAlias(13, "Cuntierra_agiudu");
		addNamespaceAlias(14, "Categoria");
		addNamespaceAlias(15, "Cuntierra_categoria");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://sc.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "sc";
	}
}
