/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class SrConfig extends TemplateConfig {
	public SrConfig() {
		addNamespaceAlias(-2, "Медиј", "Medija", "Медија");
		addNamespaceAlias(-1, "Посебно", "Posebno");
		addNamespaceAlias(1, "Разговор", "Razgovor");
		addNamespaceAlias(2, "Корисник", "Korisnik");
		addNamespaceAlias(3, "Разговор_са_корисником", "Razgovor_sa_korisnikom");
		addNamespaceAlias(5, "Разговор_о_Wikipedia", "Razgovor_o_Wikipedia");
		addNamespaceAlias(6, "Датотека", "Slika", "Слика");
		addNamespaceAlias(7, "Разговор_о_датотеци", "Razgovor_o_slici", "Разговор_о_слици");
		addNamespaceAlias(8, "Медијавики", "MedijaViki", "МедијаВики");
		addNamespaceAlias(9, "Разговор_о_Медијавикију", "Razgovor_o_MedijaVikiju", "Разговор_о_МедијаВикију");
		addNamespaceAlias(10, "Шаблон", "Šablon");
		addNamespaceAlias(11, "Разговор_о_шаблону", "Razgovor_o_šablonu");
		addNamespaceAlias(12, "Помоћ", "Pomoć");
		addNamespaceAlias(13, "Разговор_о_помоћи", "Razgovor_o_pomoći");
		addNamespaceAlias(14, "Категорија", "Kategorija");
		addNamespaceAlias(15, "Разговор_о_категорији", "Razgovor_o_kategoriji");

		addI18nCIAlias("redirect", "#Преусмери", "#преусмери", "#ПРЕУСМЕРИ", "#Преусмјери", "#преусмјери", "#ПРЕУСМЈЕРИ", "#redirect", "#REDIRECT");
		addI18nCIAlias("notoc", "__БЕЗСАДРЖАЈА__", "__БЕЗ_САДРЖАЈА__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__БЕЗГАЛЕРИЈЕ__", "__БЕЗ_ГАЛЕРИЈЕ__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__ФОРСИРАНИСАДРЖАЈ__", "__ФОРСИРАНИ_САДРЖАЈ__", "__ПРИМОРАНИСАДРЖАЈ__", "__ПРИМОРАНИ_САДРЖАЈ__", "__FORCETOC__");
		addI18nCIAlias("toc", "__САДРЖАЈ__", "__TOC__");
		addI18nCIAlias("noeditsection", "__БЕЗИЗМЕНА__", "__БЕЗ_ИЗМЕНА__", "__БЕЗИЗМЈЕНА__", "__БЕЗ_ИЗМЈЕНА__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "ТРЕНУТНИМЕСЕЦ", "ТРЕНУТНИ_МЕСЕЦ", "ТЕКУЋИМЕСЕЦ", "ТЕКУЋИ_МЕСЕЦ", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "ТРЕНУТНИМЕСЕЦ1", "ТРЕНУТНИ_МЕСЕЦ1", "ТЕКУЋИМЕСЕЦ1", "ТЕКУЋИ_МЕСЕЦ1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "ТРЕНУТНИМЕСЕЦИМЕ", "ИМЕТЕКУЋЕГМЕСЕЦА", "ИМЕ_ТЕКУЋЕГ_МЕСЕЦА", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "ТРЕНУТНИМЕСЕЦГЕН", "ТЕКУЋИМЕСЕЦГЕН", "ТЕКУЋИ_МЕСЕЦ_ГЕН", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "ТРЕНУТНИМЕСЕЦСКР", "ТЕКУЋИМЕСЕЦСКР", "ТЕКУЋИ_МЕСЕЦ_СКР", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "ТРЕНУТНИДАН", "ТЕКУЋИДАН", "ТЕКУЋИ_ДАН", "CURRENTDAY");
		addI18nAlias("currentday2", "ТЕКУЋИДАН2", "ТЕКУЋИ_ДАН_2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "ТРЕНУТНИДАНИМЕ", "ИМЕТЕКУЋЕГДАНА", "ИМЕ_ТЕКУЋЕГ_ДАНА", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "ТРЕНУТНАГОДИНА", "ТЕКУЋАГОДИНА", "ТЕКУЋА_ГОДИНА", "CURRENTYEAR");
		addI18nAlias("currenttime", "ТРЕНУТНОВРЕМЕ", "ТЕКУЋЕВРЕМЕ", "ТЕКУЋЕ_ВРЕМЕ", "CURRENTTIME");
		addI18nAlias("currenthour", "ТЕКУЋИСАТ", "ТЕКУЋИ_САТ", "CURRENTHOUR");
		addI18nAlias("localmonth", "ЛОКАЛНИМЕСЕЦ", "ЛОКАЛНИ_МЕСЕЦ", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "ЛОКАЛНИМЕСЕЦ2", "ЛОКАЛНИ_МЕСЕЦ2", "LOCALMONTH1");
		addI18nAlias("localmonthname", "ИМЕЛОКАЛНОГМЕСЕЦА", "ИМЕ_ЛОКАЛНОГ_МЕСЕЦА", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "ЛОКАЛНИМЕСЕЦГЕН", "ЛОКАЛНИ_МЕСЕЦ_ГЕН", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "ЛОКАЛНИМЕСЕЦСКР", "ЛОКАЛНИ_МЕСЕЦ_СКР", "LOCALMONTHABBREV");
		addI18nAlias("localday", "ЛОКАЛНИДАН", "ЛОКАЛНИ_ДАН", "LOCALDAY");
		addI18nAlias("localday2", "ЛОКАЛНИДАН2", "ЛОКАЛНИ_ДАН2", "LOCALDAY2");
		addI18nAlias("localdayname", "ИМЕЛОКАЛНОГДАНА", "ИМЕ_ЛОКАЛНОГ_ДАНА", "LOCALDAYNAME");
		addI18nAlias("localyear", "ЛОКАЛНАГОДИНА", "ЛОКАЛНА_ГОДИНА", "LOCALYEAR");
		addI18nAlias("localtime", "ЛОКАЛНОВРЕМЕ", "ЛОКАЛНО_ВРЕМЕ", "LOCALTIME");
		addI18nAlias("localhour", "ЛОКАЛНИСАТ", "ЛОКАЛНИ_САТ", "LOCALHOUR");
		addI18nAlias("numberofpages", "БРОЈСТРАНИЦА", "БРОЈ_СТРАНИЦА", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "БРОЈЧЛАНАКА", "БРОЈ_ЧЛАНАКА", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "БРОЈДАТОТЕКА", "БРОЈ_ДАТОТЕКА", "БРОЈФАЈЛОВА", "БРОЈ_ФАЈЛОВА", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "БРОЈКОРИСНИКА", "БРОЈ_КОРИСНИКА", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "БРОЈАКТИВНИХКОРИСНИКА", "БРОЈ_АКТИВНИХ_КОРИСНИКА", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "БРОЈИЗМЕНА", "БРОЈ_ИЗМЕНА", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "БРОЈПРЕГЛЕДА", "БРОЈ_ПРЕГЛЕДА", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "ИМЕСТРАНИЦЕ", "ИМЕ_СТРАНИЦЕ", "СТРАНИЦА", "PAGENAME");
		addI18nAlias("pagenamee", "ИМЕНАСТРАНИЦА", "ИМЕНА_СТРАНИЦА", "СТРАНИЦЕ", "PAGENAMEE");
		addI18nAlias("namespace", "ИМЕНСКИПРОСТОР", "ИМЕНСКИ_ПРОСТОР", "NAMESPACE");
		addI18nAlias("namespacee", "ИМЕНСКИПРОСТОРИ", "ИМЕНСКИ_ПРОСТОРИ", "NAMESPACEE");
		addI18nAlias("talkspace", "РАЗГОВОР", "TALKSPACE");
		addI18nAlias("talkspacee", "РАЗГОВОРИ", "TALKSPACEE");
		addI18nAlias("subjectspace", "ИМЕНСКИПРОСТОРЧЛАНКА", "ИМЕНСКИ_ПРОСТОР_ЧЛАНКА", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "ИМЕНСКИПРОСТОРЧЛАНАКА", "ИМЕНСКИ_ПРОСТОР_ЧЛАНАКА", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "ПУНОИМЕСТРАНИЦЕ", "ПУНОИМЕСТРАНЕ", "ПУНО_ИМЕ_СТРАНИЦЕ", "ПУНО_ИМЕ_СТРАНЕ", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "ПУНАИМЕНАСТРАНИЦА", "ПУНАИМЕНАСТРАНА", "ПУНА_ИМЕНА_СТРАНИЦА", "ПУНА_ИМЕНА_СТРАНА", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "ИМЕПОДСТРАНИЦЕ", "ИМЕПОДСТРАНЕ", "ИМЕ_ПОДСТРАНИЦЕ", "ИМЕ_ПОДСТРАНЕ", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "ИМЕНАПОДСТРАНИЦА", "ИМЕНАПОДСТРАНА", "ИМЕНА_ПОДСТРАНИЦА", "ИМЕНА_ПОДСТРАНА", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "ИМЕОСНОВЕ", "ИМЕ_ОСНОВЕ", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "ИМЕНАОСНОВА", "ИМЕНА_ОСНОВА", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "ИМЕРАЗГОВОРА", "ИМЕ_РАЗГОВОРА", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "ИМЕНАРАЗГОВОРА", "ИМЕНА_РАЗГОВОРА", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "ИМЕЧЛАНКА", "ИМЕ_ЧЛАНКА", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "ИМЕНАЧЛАНАКА", "ИМЕНА_ЧЛАНАКА", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "ПОР:", "MSG:");
		addI18nCIAlias("subst", "ЗАМЕНИ:", "ЗАМЕНА:", "SUBST:");
		addI18nCIAlias("safesubst", "БЕЗБЕДНАЗАМЕНА", "БЕЗБЕДНА_ЗАМЕНА", "SAFESUBST:");
		addI18nCIAlias("msgnw", "НВПОР:", "MSGNW:");
		addI18nAlias("img_thumbnail", "мини", "умањено", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "мини=$1", "умањено=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "десно", "д", "right");
		addI18nAlias("img_left", "лево", "л", "left");
		addI18nAlias("img_none", "без", "н", "none");
		addI18nAlias("img_width", "$1пискел", "$1п", "$1px");
		addI18nAlias("img_center", "центар", "ц", "center", "centre");
		addI18nAlias("img_framed", "оквир", "рам", "framed", "enframed", "frame");
		addI18nAlias("img_frameless", "безоквира", "без_оквира", "безрама", "без_рама", "frameless");
		addI18nAlias("img_page", "страница=$1", "страна=$1", "страница_$1", "страна_$1", "page=$1", "page $1");
		addI18nAlias("img_upright", "усправно", "усправно=$1", "усправно_$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "ивица", "border");
		addI18nAlias("img_baseline", "основа", "baseline");
		addI18nAlias("img_sub", "под", "sub");
		addI18nAlias("img_super", "супер", "super", "sup");
		addI18nAlias("img_top", "врх", "top");
		addI18nAlias("img_text_top", "врхтекста", "врх_текста", "text-top");
		addI18nAlias("img_middle", "средина", "middle");
		addI18nAlias("img_bottom", "дно", "bottom");
		addI18nAlias("img_text_bottom", "срединатекста", "средина_текста", "text-bottom");
		addI18nAlias("img_link", "веза=$1", "link=$1");
		addI18nAlias("img_alt", "алт=$1", "alt=$1");
		addI18nCIAlias("int", "ИНТ:", "INT:");
		addI18nAlias("sitename", "ИМЕСАЈТА", "SITENAME");
		addI18nCIAlias("ns", "ИП:", "NS:");
		addI18nCIAlias("localurl", "ЛОКАЛНААДРЕСА:", "ЛОКАЛНА_АДРЕСА:", "LOCALURL:");
		addI18nCIAlias("localurle", "ЛОКАЛНЕАДРЕСЕ:", "ЛОКАЛНЕ_АДРЕСЕ:", "LOCALURLE:");
		addI18nCIAlias("articlepath", "ПУТАЊАЧЛАНКА", "ПУТАЊА_ЧЛАНКА", "ARTICLEPATH");
		addI18nCIAlias("server", "СЕРВЕР", "SERVER");
		addI18nCIAlias("servername", "ИМЕСЕРВЕРА", "ИМЕ_СЕРВЕРА", "SERVERNAME");
		addI18nCIAlias("scriptpath", "СКРИПТА", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "ПУТАЊАСТИЛА", "ПУТАЊА_СТИЛА", "STYLEPATH");
		addI18nCIAlias("grammar", "ГРАМАТИКА:", "GRAMMAR:");
		addI18nCIAlias("gender", "РОД:", "ЛИЦЕ:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__БЕЗКН__", "__BEZKN__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__БЕЗЦЦ__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "ТРЕНУТНАНЕДЕЉА", "ТРЕНУТНА_НЕДЕЉА", "ТЕКУЋАНЕДЕЉА", "ТЕКУЋА_НЕДЕЉА", "CURRENTWEEK");
		addI18nAlias("currentdow", "ТРЕНУТНИДОВ", "ТЕКУЋИДУН", "CURRENTDOW");
		addI18nAlias("localweek", "ЛОКАЛНАНЕДЕЉА", "ЛОКАЛНА_НЕДЕЉА", "LOCALWEEK");
		addI18nAlias("localdow", "ЛОКАЛНИДУН", "LOCALDOW");
		addI18nAlias("revisionid", "ИДРЕВИЗИЈЕ", "ИД_РЕВИЗИЈЕ", "REVISIONID");
		addI18nAlias("revisionday", "ДАНИЗМЕНЕ", "ДАН_ИЗМЕНЕ", "REVISIONDAY");
		addI18nAlias("revisionday2", "ДАНИЗМЕНЕ2", "ДАН_ИЗМЕНЕ2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "МЕСЕЦИЗМЕНЕ", "МЕСЕЦ_ИЗМЕНЕ", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "МЕСЕЦИЗМЕНЕ1", "МЕСЕЦ_ИЗМЕНЕ1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "ГОДИНАИЗМЕНЕ", "ГОДИНА_ИЗМЕНЕ", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "ВРЕМЕИЗМЕНЕ", "ВРЕМЕ_ИЗМЕНЕ", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "КОРИСНИКИЗМЕНЕ", "КОРИСНИК_ИЗМЕНЕ", "REVISIONUSER");
		addI18nCIAlias("plural", "МНОЖИНА:", "PLURAL:");
		addI18nCIAlias("fullurl", "ПУНУРЛ:", "ЦЕЛААДРЕСА", "ЦЕЛА_АДРЕСА", "FULLURL:");
		addI18nCIAlias("fullurle", "ПУНУРЛЕ:", "ЦЕЛЕАДРЕСЕ", "ЦЕЛЕ_АДРЕСЕ", "FULLURLE:");
		addI18nCIAlias("lcfirst", "ЛЦПРВИ:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "УЦПРВИ:", "UCFIRST:");
		addI18nCIAlias("lc", "ЛЦ:", "LC:");
		addI18nCIAlias("uc", "УЦ:", "UC:");
		addI18nCIAlias("raw", "ЧИСТ:", "RAW:");
		addI18nAlias("displaytitle", "НАЗИВПРИКАЗА", "НАЗИВ_ПРИКАЗА", "DISPLAYTITLE");
		addI18nAlias("rawsuffix", "Р", "R");
		addI18nAlias("newsectionlink", "__НОВАВЕЗАОДЕЉКА__", "__НОВА_ВЕЗА_ОДЕЉКА__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__БЕЗНОВЕВЕЗЕОДЕЉКА__", "__БЕЗ_НОВЕ_ВЕЗЕ_ОДЕЉКА__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "ТЕКУЋЕИЗДАЊЕ", "ТЕКУЋЕ_ИЗДАЊЕ", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "КОДИРАЊЕАДРЕСЕ", "КОДИРАЊЕ_АДРЕСЕ", "URLENCODE:");
		addI18nCIAlias("anchorencode", "КОДИРАЊЕВЕЗЕ", "КОДИРАЊЕ_ВЕЗЕ", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "ТЕКУЋИОТИСАКВРЕМЕНА", "ТЕКУЋИ_ОТИСАК_ВРЕМЕНА", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "ОТИСАКВРЕМЕНА", "ОТИСАК_ВРЕМЕНА", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "СМЕРОЗНАКЕ", "СМЕР	_ОЗНАКЕ", "DIRECTIONMARK", "DIRMARK");
		addI18nAlias("contentlanguage", "ЈЕЗИКСАДРЖАЈА", "ЈЕЗИК_САДРЖАЈА", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "СТРАНИЦАУИМЕНСКОМПРОСТОРУ", "СТРАНАУИМЕНСКОМПРОСТОРУ", "СТРАНИЦА_У_ИМЕНСКОМ_ПРОСТОРУ", "СТРАНА_У_ИМЕНСКОМ_ПРОСТОРУ", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "БРОЈАДМИНА", "БРОЈ_АДМИНА", "NUMBEROFADMINS");
		addI18nCIAlias("padleft", "ПОРАВНАЈЛЕВО", "ПОРАВНАЈ_ЛЕВО", "PADLEFT");
		addI18nCIAlias("padright", "ПОРАВНАЈДЕСНО", "ПОРАВНАЈ_ДЕСНО", "PADRIGHT");
		addI18nCIAlias("special", "посебно", "special");
		addI18nCIAlias("filepath", "ПУТАЊАДАТОТЕКЕ", "ПУТАЊА_ДАТОТЕКЕ", "FILEPATH:");
		addI18nCIAlias("tag", "ознака", "tag");
		addI18nAlias("hiddencat", "__САКРИВЕНАКАТ__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "СТРАНИЦАУКАТЕГОРИЈИ", "СТРАНАУКАТЕГОРИЈИ", "СТРАНИЦА_У_КАТЕГОРИЈИ", "СТРАНА_У_КАТЕГОРИЈИ", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "ВЕЛИЧИНАСТРАНИЦЕ", "ВЕЛИЧИНАСТРАНЕ", "ВЕЛИЧИНА_СТРАНИЦЕ", "ВЕЛИЧИНА_СТРАНЕ", "PAGESIZE");
		addI18nAlias("index", "__ИНДЕКС__", "__INDEX__");
		addI18nAlias("noindex", "__БЕЗИНДЕКСА__", "__БЕЗ_ИНДЕКСА__", "__NOINDEX__");
		addI18nAlias("numberingroup", "БРОЈУГРУПИ", "БРОЈ_У_ГРУПИ", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__СТАТИЧКОПРЕУСМЕРЕЊЕ__", "СТАТИЧКО_ПРЕУСМЕРЕЊЕ", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "НИВОЗАШТИТЕ", "НИВО_ЗАШТИТЕ", "PROTECTIONLEVEL");
		addI18nCIAlias("formatdate", "форматдатума", "формат_датума", "formatdate", "dateformat");
		addI18nCIAlias("url_path", "ПУТАЊА", "PATH");
		addI18nCIAlias("url_wiki", "ВИКИ", "WIKI");
		addI18nCIAlias("url_query", "РЕДОСЛЕД", "QUERY");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://sr.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "sr";
	}
}
