/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class TaConfig extends TemplateConfig {
	public TaConfig() {
		addNamespaceAlias(-2, "ஊடகம்");
		addNamespaceAlias(-1, "சிறப்பு");
		addNamespaceAlias(1, "பேச்சு");
		addNamespaceAlias(2, "பயனர்");
		addNamespaceAlias(3, "பயனர்_பேச்சு");
		addNamespaceAlias(5, "Wikipedia_பேச்சு", "விக்கிபீடியா_பேச்சு");
		addNamespaceAlias(6, "படிமம்");
		addNamespaceAlias(7, "படிமப்_பேச்சு", "உருவப்_பேச்சு");
		addNamespaceAlias(8, "மீடியாவிக்கி");
		addNamespaceAlias(9, "மீடியாவிக்கி_பேச்சு");
		addNamespaceAlias(10, "வார்ப்புரு");
		addNamespaceAlias(11, "வார்ப்புரு_பேச்சு");
		addNamespaceAlias(12, "உதவி");
		addNamespaceAlias(13, "உதவி_பேச்சு");
		addNamespaceAlias(14, "பகுப்பு");
		addNamespaceAlias(15, "பகுப்பு_பேச்சு");
		addNamespaceAlias(4, "விக்கிபீடியா");

		addI18nCIAlias("redirect", "#வழிமாற்று", "#REDIRECT");
		addI18nAlias("img_right", "வலது", "right");
		addI18nAlias("img_left", "இடது", "left");
		addI18nAlias("img_none", "ஒன்றுமில்லை", "none");
		addI18nAlias("img_center", "மையம்", "center", "centre");
		addI18nAlias("img_top", "மேல்", "top");
		addI18nAlias("img_middle", "மத்தியில்", "middle");
		addI18nAlias("img_bottom", "கீழ்", "bottom");
		addI18nCIAlias("plural", "பன்மை", "PLURAL:");
		addI18nCIAlias("special", "சிறப்பு", "special");
		addI18nAlias("pagesize", "பக்க_அளவு", "PAGESIZE");
		addI18nCIAlias("url_path", "வழி", "PATH");
		addI18nCIAlias("url_wiki", "விக்கி", "WIKI");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ta.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ta";
	}
}
