/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class TlConfig extends TemplateConfig {
	public TlConfig() {
		addNamespaceAlias(-2, "Midya");
		addNamespaceAlias(-1, "Natatangi");
		addNamespaceAlias(1, "Usapan");
		addNamespaceAlias(2, "Tagagamit");
		addNamespaceAlias(3, "Usapang_tagagamit");
		addNamespaceAlias(5, "Usapang_Wikipedia");
		addNamespaceAlias(6, "Talaksan");
		addNamespaceAlias(7, "Usapang_talaksan");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Usapang_MediaWiki");
		addNamespaceAlias(10, "Padron", "Suleras");
		addNamespaceAlias(11, "Usapang_padron", "Usapang_suleras");
		addNamespaceAlias(12, "Tulong");
		addNamespaceAlias(13, "Usapang_tulong");
		addNamespaceAlias(14, "Kategorya", "Kaurian");
		addNamespaceAlias(15, "Usapang_kategorya", "Usapang_kaurian");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://tl.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "tl";
	}
}
