/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class TlyConfig extends TemplateConfig {
	public TlyConfig() {
		addNamespaceAlias(-2, "Medja");
		addNamespaceAlias(-1, "Xususi");
		addNamespaceAlias(1, "Nopegət");
		addNamespaceAlias(2, "Okoədə");
		addNamespaceAlias(3, "Okoədəj_nopegət");
		addNamespaceAlias(5, "Wikipedia_Nopegət", "Wikipedia_Nopegətəti");
		addNamespaceAlias(6, "Fajl");
		addNamespaceAlias(7, "Fajl_nopegət", "Fajli_nopegət");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "MediaWiki_nopegət");
		addNamespaceAlias(10, "Numunə");
		addNamespaceAlias(11, "Numunə_nopegət");
		addNamespaceAlias(12, "Koməg");
		addNamespaceAlias(13, "Koməg_nopegət", "Koməgi_nopegət");
		addNamespaceAlias(14, "Tispir");
		addNamespaceAlias(15, "Tispir_nopegət", "Tispiron_nopegət");

		addI18nCIAlias("redirect", "#ТОЖӘДӘН_ИСТИҒОМӘТ_ДОЈ", "#REDIRECT");
		addI18nCIAlias("notoc", "__БЕМЫНДӘРИҸОТ__", "__NOTOC__");
		addI18nCIAlias("forcetoc", "__МӘҸБУРИЈӘ_МЫНДӘРИҸОТ__", "__FORCETOC__");
		addI18nCIAlias("toc", "__МЫНДӘРИҸОТ__", "__TOC__");
		addI18nAlias("currentmonth", "ЕСӘТНӘ_МАНГ", "ЕСӘТНӘ_МАНГ_2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "ЕСӘТНӘ_МАНГ_1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "ЕСӘТНӘ_МАНГИ_НОМ", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "ЕСӘТНӘ_МАНГИ_НОМ_ҸИНС", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentday", "ЕСӘТНӘ_РУЖ", "CURRENTDAY");
		addI18nAlias("currentday2", "ЕСӘТНӘ_РУЖ_2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "ЕСӘТНӘ_РУЖИ_НОМ", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "ЕСӘТНӘ_СОР", "CURRENTYEAR");
		addI18nAlias("currenttime", "ЕСӘТНӘ_ВАХТ", "CURRENTTIME");
		addI18nAlias("currenthour", "ЕСӘТНӘ_СААТ", "CURRENTHOUR");
		addI18nAlias("localmonth", "БУМИНӘ_МАНГ", "БУМИНӘ_МАНГ_2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "БУМИНӘ_МАНГ_1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "БУМИНӘ_МАНГИ_НОМ", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "БУМИНӘ_МАНГИ_НОМ_ҸИНС", "LOCALMONTHNAMEGEN");
		addI18nAlias("localday", "БУМИНӘ_РУЖ", "LOCALDAY");
		addI18nAlias("localday2", "БУМИНӘ_РУЖ_2", "LOCALDAY2");
		addI18nAlias("localdayname", "БУМИНӘ_РУЖИ_НОМ", "LOCALDAYNAME");
		addI18nAlias("localyear", "БУМИНӘ_СОР", "LOCALYEAR");
		addI18nAlias("localtime", "БУМИНӘ_ВАХТ", "LOCALTIME");
		addI18nAlias("localhour", "БУМИНӘ_СААТ", "LOCALHOUR");
		addI18nAlias("numberofpages", "СӘҺИФОН_ҒӘДӘР", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "МӘҒОЛОН_ҒӘДӘР", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "ФАЈЛОН_ҒӘДӘР", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "ИШТИРОКӘКОН_ҒӘДӘР", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "ТИЛИКӘ_ИШТИРОКӘКОН_ҒӘДӘР", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "ДӘГИШОН_ҒӘДӘР", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "ДИЈӘ_КАРДЕ_ҒӘДӘР", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "СӘҺИФӘ_НОМ", "PAGENAME");
		addI18nAlias("pagenamee", "СӘҺИФӘ_НОМ_2", "PAGENAMEE");
		addI18nAlias("namespace", "НОМОН_МӘКОН", "NAMESPACE");
		addI18nAlias("namespacee", "НОМОН_МӘКОН_2", "NAMESPACEE");
		addI18nAlias("namespacenumber", "НОМОН_МӘКОН_ҒӘДӘР", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "МЫЗОКИРОН_МӘКОН", "TALKSPACE");
		addI18nAlias("talkspacee", "МЫЗОКИРОН_МӘКОН_2", "TALKSPACEE");
		addI18nAlias("subjectspace", "МӘҒОЛОН_МӘКОН", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("subjectspacee", "МӘҒОЛОН_МӘКОН_2", "SUBJECTSPACEE", "ARTICLESPACEE");
		addI18nAlias("fullpagename", "СӘҺИФӘ_ПУРӘ_НОМ", "FULLPAGENAME");
		addI18nAlias("fullpagenamee", "СӘҺИФӘ_ПУРӘ_НОМ_2", "FULLPAGENAMEE");
		addI18nAlias("subpagename", "ЖИНТОНӘДӘ_СӘҺИФӘ_НОМ", "SUBPAGENAME");
		addI18nAlias("subpagenamee", "ЖИНТОНӘДӘ_СӘҺИФӘ_НОМ_2", "SUBPAGENAMEE");
		addI18nAlias("basepagename", "СӘҺИФӘ_НОМИ_ӘСОС", "BASEPAGENAME");
		addI18nAlias("basepagenamee", "СӘҺИФӘ_НОМИ_ӘСОС_2", "BASEPAGENAMEE");
		addI18nAlias("talkpagename", "МЫЗОКИРӘ_СӘҺИФӘ_НОМ", "TALKPAGENAME");
		addI18nAlias("talkpagenamee", "МЫЗОКИРӘ_СӘҺИФӘ_НОМ_2", "TALKPAGENAMEE");
		addI18nAlias("subjectpagename", "МӘҒОЛӘ_СӘҺИФӘ_НОМ", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nAlias("subjectpagenamee", "МӘҒОЛӘ_СӘҺИФӘ_НОМ_2", "SUBJECTPAGENAMEE", "ARTICLEPAGENAMEE");
		addI18nCIAlias("msg", "ХӘБӘ:", "MSG:");
		addI18nCIAlias("subst", "ӘВӘЗ_КАРДЕ:", "SUBST:");
		addI18nCIAlias("msgnw", "БЕВИКИ_ХӘБӘ:", "MSGNW:");
		addI18nAlias("img_thumbnail", "миниатјур", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "миниатјур=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "росто", "right");
		addI18nAlias("img_left", "чәпо", "left");
		addI18nAlias("img_none", "бе", "none");
		addI18nAlias("img_width", "$1пкс", "$1px");
		addI18nAlias("img_center", "мәрәнго", "center", "centre");
		addI18nAlias("img_page", "сәһифә=$1", "сәһифә_$1", "page=$1", "page $1");
		addI18nAlias("sitename", "САЈТИ_НОМ", "SITENAME");
		addI18nCIAlias("localurl", "БУМИНӘ_УНВОН:", "LOCALURL:");
		addI18nCIAlias("localurle", "БУМИНӘ_УНВОН_2:", "LOCALURLE:");
		addI18nAlias("currentweek", "ЕСӘТНӘ_ҺАФТӘ", "CURRENTWEEK");
		addI18nAlias("currentdow", "ЕСӘТНӘ_ҺАФТӘ_РУЖ", "CURRENTDOW");
		addI18nAlias("localweek", "БУМИНӘ_ҺАФТӘ", "LOCALWEEK");
		addI18nAlias("localdow", "БУМИНӘ_ҺАФТӘ_РУЖ", "LOCALDOW");
		addI18nAlias("revisionid", "РӘВОЈӘТИ_ID", "REVISIONID");
		addI18nAlias("revisionday", "РӘВОЈӘТИ_РУЖ", "REVISIONDAY");
		addI18nAlias("revisionday2", "РӘВОЈӘТИ_РУЖ_2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "РӘВОЈӘТИ_МАНГ", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "РӘВОЈӘТИ_МАНГ_2", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "РӘВОЈӘТИ_СОР", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "РӘВОЈӘТИ_ВАХТИ_ҒЕЈД", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "ИШТИРОКӘКӘ_РӘВОЈӘТ", "REVISIONUSER");
		addI18nCIAlias("fullurl", "ПУРӘ_УНВОН:", "FULLURL:");
		addI18nCIAlias("fullurle", "ПУРӘ_УНВОН_2:", "FULLURLE:");
		addI18nAlias("currentversion", "ЕСӘТНӘ_РӘВОЈӘТ", "CURRENTVERSION");
		addI18nAlias("currenttimestamp", "ЕСӘТНӘ_ВАХТИ_ҒЕЈД", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "БУМИНӘ_ВАХТИ_ҒЕЈД", "LOCALTIMESTAMP");
		addI18nAlias("directionmark", "НОМӘ_ИСТИҒОМӘТ", "DIRECTIONMARK", "DIRMARK");
		addI18nCIAlias("language", "#ЗЫВОН:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "МЫҒДОРИ_ЗЫВОН", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "СӘҺИФОН_БӘ_НОМОН_МӘКОНӘДӘ:", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("pagesize", "СӘҺИФӘ_ПАМЈӘ", "PAGESIZE");
		addI18nCIAlias("url_wiki", "ВИКИ", "WIKI");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://tly.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "tly";
	}
}
