/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class UrConfig extends TemplateConfig {
	public UrConfig() {
		addNamespaceAlias(-2, "وسیط", "زریعہ");
		addNamespaceAlias(-1, "خاص");
		addNamespaceAlias(0, "");
		addNamespaceAlias(1, "تبادلۂ_خیال");
		addNamespaceAlias(2, "صارف");
		addNamespaceAlias(3, "تبادلۂ_خیال_صارف");
		addNamespaceAlias(5, "تبادلۂ_خیال_Wikipedia");
		addNamespaceAlias(6, "ملف", "تصویر");
		addNamespaceAlias(7, "تبادلۂ_خیال_ملف", "تبادلۂ_خیال_تصویر");
		addNamespaceAlias(8, "میڈیاویکی", "میڈیاوکی");
		addNamespaceAlias(9, "تبادلۂ_خیال_میڈیاویکی", "تبادلۂ_خیال_میڈیاوکی");
		addNamespaceAlias(10, "سانچہ");
		addNamespaceAlias(11, "تبادلۂ_خیال_سانچہ");
		addNamespaceAlias(12, "معاونت");
		addNamespaceAlias(13, "تبادلۂ_خیال_معاونت");
		addNamespaceAlias(14, "زمرہ");
		addNamespaceAlias(15, "تبادلۂ_خیال_زمرہ");

		addI18nCIAlias("redirect", "#رجوع_مکرر", "#REDIRECT");
		addI18nCIAlias("notoc", "_فہرست_نہیں_", "__NOTOC__");
		addI18nCIAlias("toc", "__فہرست__", "__TOC__");
		addI18nCIAlias("noeditsection", "__ناتحریرقسم__", "__NOEDITSECTION__");
		addI18nAlias("pagename", "نام_صفحہ", "PAGENAME");
		addI18nAlias("namespace", "نام_فضا", "NAMESPACE");
		addI18nCIAlias("msg", "پیغام:", "MSG:");
		addI18nCIAlias("subst", "جا:", "نقل:", "SUBST:");
		addI18nCIAlias("safesubst", "محفوظ_جا:", "محفوظ_نقل:", "SAFESUBST:");
		addI18nAlias("img_thumbnail", "تصغیر", "thumbnail", "thumb");
		addI18nAlias("img_right", "دائیں", "right");
		addI18nAlias("img_left", "بائیں", "left");
		addI18nAlias("img_center", "درمیان", "center", "centre");
		addI18nAlias("sitename", "نام_موقع", "SITENAME");
		addI18nCIAlias("grammar", "قواعد:", "GRAMMAR:");
		addI18nCIAlias("gender", "جنس:", "GENDER:");
		addI18nCIAlias("special", "خاص", "special");
		addI18nCIAlias("speciale", "خاص_عنوان", "speciale");
		addI18nAlias("index", "__اشاریہ__", "__INDEX__");
		addI18nAlias("noindex", "__نااشاریہ__", "__NOINDEX__");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://ur.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "ur";
	}
}
