/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class UzConfig extends TemplateConfig {
	public UzConfig() {
		addNamespaceAlias(-2, "Media", "Mediya");
		addNamespaceAlias(-1, "Maxsus");
		addNamespaceAlias(1, "Munozara");
		addNamespaceAlias(2, "Foydalanuvchi");
		addNamespaceAlias(3, "Foydalanuvchi_munozarasi");
		addNamespaceAlias(5, "Wikipedia_munozarasi");
		addNamespaceAlias(6, "Fayl", "Tasvir");
		addNamespaceAlias(7, "Fayl_munozarasi", "Tasvir_munozarasi");
		addNamespaceAlias(8, "MediaWiki", "MediyaViki");
		addNamespaceAlias(9, "MediaWiki_munozarasi", "MediyaViki_munozarasi");
		addNamespaceAlias(10, "Andoza", "Shablon");
		addNamespaceAlias(11, "Andoza_munozarasi", "Shablon_munozarasi");
		addNamespaceAlias(12, "Yordam");
		addNamespaceAlias(13, "Yordam_munozarasi");
		addNamespaceAlias(14, "Turkum", "Kategoriya");
		addNamespaceAlias(15, "Turkum_munozarasi", "Kategoriya_munozarasi");

		addI18nCIAlias("redirect", "#YOʻNALTIRISH", "#YONALTIRISH", "#REDIRECT");
		addI18nCIAlias("notoc", "__ICHIDAGILARYOQ__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__GALEREYAYOQ__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__ICHIDAGILARMAJBURIY__", "__FORCETOC__");
		addI18nCIAlias("toc", "__ICHIDAGILARI__", "__ICHIDAGILAR__", "__TOC__");
		addI18nCIAlias("noeditsection", "__TAHRIRYOQ__", "__TARTIBLASHYOQ__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "JORIYOY", "JORIYOY2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "JORIYOY1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "JORIYOYNOMI", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "JORIYOYNOMIQARATQICH", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "JORIYOYQISQARTMASI", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "JORIYKUN", "CURRENTDAY");
		addI18nAlias("currentday2", "JORIYKUN2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "JORIYKUNNOMI", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "JORIYYIL", "CURRENTYEAR");
		addI18nAlias("currenttime", "JORIYVAQT", "CURRENTTIME");
		addI18nAlias("currenthour", "JORIYSOAT", "CURRENTHOUR");
		addI18nAlias("localmonth", "MAHALLIYOY", "MAHALLIYOY2", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "MAHALLIYOY1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "MAHALLIYOYNOMI", "LOCALMONTHNAME");
		addI18nAlias("localmonthnamegen", "MAHALLIYOYQARATQICH", "LOCALMONTHNAMEGEN");
		addI18nAlias("localmonthabbrev", "MAHALLIYOYQISQARTMASI", "LOCALMONTHABBREV");
		addI18nAlias("localday", "MAHALLIYKUN", "LOCALDAY");
		addI18nAlias("localday2", "MAHALLIYKUN2", "LOCALDAY2");
		addI18nAlias("localdayname", "MAHALLIYKUNNOMI", "LOCALDAYNAME");
		addI18nAlias("localyear", "MAHALLIYYIL", "LOCALYEAR");
		addI18nAlias("localtime", "MAHALLIYVAQT", "LOCALTIME");
		addI18nAlias("localhour", "MAHALLIYSOAT", "LOCALHOUR");
		addI18nAlias("numberofpages", "SAHIFASONI", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "MAQOLASONI", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "FAYLSONI", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "FOYDALANUVCHISONI", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "FAOLFOYDALANUVCHISONI", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "OZGARISHSONI", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "KORISHSONI", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "SAHIFANOMI", "PAGENAME");
		addI18nAlias("namespace", "NOMFAZO", "NAMESPACE");
		addI18nCIAlias("gender", "JINS", "GENDER:");
		addI18nAlias("currentweek", "JORIYHAFTA", "CURRENTWEEK");
		addI18nCIAlias("language", "#TIL:", "#LANGUAGE:");
		addI18nAlias("numberofadmins", "ADMINISTRATORSONI", "NUMBEROFADMINS");
		addI18nCIAlias("special", "maxsus", "special");
		addI18nCIAlias("tag", "yorliq", "tag");
		addI18nAlias("hiddencat", "__YASHIRINTURKUM__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "TURKUMDAGISAHIFALAR", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "SAHIFAHAJMI", "PAGESIZE");
		addI18nAlias("index", "__INDEKS__", "__INDEX__");
		addI18nAlias("noindex", "__INDEKSYOQ__", "__NOINDEX__");
		addI18nCIAlias("url_wiki", "VIKI", "WIKI");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://uz.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "uz";
	}
}
