/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class ViConfig extends TemplateConfig {
	public ViConfig() {
		addNamespaceAlias(-2, "Phương_tiện");
		addNamespaceAlias(-1, "Đặc_biệt");
		addNamespaceAlias(1, "Thảo_luận");
		addNamespaceAlias(2, "Thành_viên");
		addNamespaceAlias(3, "Thảo_luận_Thành_viên");
		addNamespaceAlias(5, "Thảo_luận_Wikipedia");
		addNamespaceAlias(6, "Tập_tin", "Hình");
		addNamespaceAlias(7, "Thảo_luận_Tập_tin", "Thảo_luận_Hình");
		addNamespaceAlias(8, "MediaWiki");
		addNamespaceAlias(9, "Thảo_luận_MediaWiki");
		addNamespaceAlias(10, "Bản_mẫu", "Tiêu_bản");
		addNamespaceAlias(11, "Thảo_luận_Bản_mẫu", "Thảo_luận_Tiêu_bản");
		addNamespaceAlias(12, "Trợ_giúp");
		addNamespaceAlias(13, "Thảo_luận_Trợ_giúp");
		addNamespaceAlias(14, "Thể_loại");
		addNamespaceAlias(15, "Thảo_luận_Thể_loại");

		addI18nCIAlias("redirect", "#đổi", "#REDIRECT");
		addI18nCIAlias("notoc", "__KHÔNG_MỤC_LỤC__", "__KHÔNGMỤCLỤC__", "__NOTOC__");
		addI18nCIAlias("nogallery", "__KHÔNG_ALBUM__", "__KHÔNGALBUM__", "__NOGALLERY__");
		addI18nCIAlias("forcetoc", "__LUÔN_MỤC_LỤC__", "__LUÔNMỤCLỤC__", "__FORCETOC__");
		addI18nCIAlias("toc", "__MỤC_LỤC__", "__MỤCLỤC__", "__TOC__");
		addI18nCIAlias("noeditsection", "__KHÔNG_NÚT_SỬA_MỤC__", "__KHÔNGNÚTSỬAMỤC__", "__NOEDITSECTION__");
		addI18nAlias("currentmonth", "THÁNG_NÀY", "THÁNGNÀY", "THÁNG_NÀY_2", "THÁNGNÀY2", "CURRENTMONTH", "CURRENTMONTH2");
		addI18nAlias("currentmonth1", "THÁNG_NÀY_1", "THÁNGNÀY1", "CURRENTMONTH1");
		addI18nAlias("currentmonthname", "TÊN_THÁNG_NÀY", "TÊNTHÁNGNÀY", "CURRENTMONTHNAME");
		addI18nAlias("currentmonthnamegen", "TÊN_DÀI_THÁNG_NÀY", "TÊNDÀITHÁNGNÀY", "CURRENTMONTHNAMEGEN");
		addI18nAlias("currentmonthabbrev", "TÊN_NGẮN_THÁNG_NÀY", "TÊNNGẮNTHÁNGNÀY", "CURRENTMONTHABBREV");
		addI18nAlias("currentday", "NGÀY_NÀY", "NGÀYNÀY", "CURRENTDAY");
		addI18nAlias("currentday2", "NGÀY_NÀY_2", "NGÀYNÀY2", "CURRENTDAY2");
		addI18nAlias("currentdayname", "TÊN_NGÀY_NÀY", "TÊNNGÀYNÀY", "CURRENTDAYNAME");
		addI18nAlias("currentyear", "NĂM_NÀY", "NĂMNÀY", "CURRENTYEAR");
		addI18nAlias("currenttime", "GIỜ_NÀY", "GIỜNÀY", "CURRENTTIME");
		addI18nAlias("currenthour", "GIỜ_HIỆN_TẠI", "GIỜHIỆNTẠI", "CURRENTHOUR");
		addI18nAlias("localmonth", "THÁNG_ĐỊA_PHƯƠNG", "THÁNGĐỊAPHƯƠNG", "LOCALMONTH", "LOCALMONTH2");
		addI18nAlias("localmonth1", "THÁNG_ĐỊA_PHƯƠNG_1", "THÁNGĐỊAPHƯƠNG1", "LOCALMONTH1");
		addI18nAlias("localmonthname", "TÊN_THÁNG_ĐỊA_PHƯƠNG", "TÊNTHÁNGĐỊAPHƯƠNG", "LOCALMONTHNAME");
		addI18nAlias("localmonthabbrev", "THÁNG_ĐỊA_PHƯƠNG_TẮT", "THÁNGĐỊAPHƯƠNGTẮT", "LOCALMONTHABBREV");
		addI18nAlias("localday", "NGÀY_ĐỊA_PHƯƠNG", "NGÀYĐỊAPHƯƠNG", "LOCALDAY");
		addI18nAlias("localday2", "NGÀY_ĐỊA_PHƯƠNG_2", "NGÀYĐỊAPHƯƠNG2", "LOCALDAY2");
		addI18nAlias("localdayname", "TÊN_NGÀY_ĐỊA_PHƯƠNG", "TÊNNGÀYĐỊAPHƯƠNG", "LOCALDAYNAME");
		addI18nAlias("localyear", "NĂM_ĐỊA_PHƯƠNG", "NĂMĐỊAPHƯƠNG", "LOCALYEAR");
		addI18nAlias("localtime", "THỜI_GIAN_ĐỊA_PHƯƠNG", "THỜIGIANĐỊAPHƯƠNG", "LOCALTIME");
		addI18nAlias("localhour", "GIỜ_ĐỊA_PHƯƠNG", "GIỜĐỊAPHƯƠNG", "LOCALHOUR");
		addI18nAlias("numberofpages", "SỐ_TRANG", "SỐTRANG", "NUMBEROFPAGES");
		addI18nAlias("numberofarticles", "SỐ_BÀI", "SỐBÀI", "NUMBEROFARTICLES");
		addI18nAlias("numberoffiles", "SỐ_TẬP_TIN", "SỐTẬPTIN", "NUMBEROFFILES");
		addI18nAlias("numberofusers", "SỐ_THÀNH_VIÊN", "SỐTHÀNHVIÊN", "NUMBEROFUSERS");
		addI18nAlias("numberofactiveusers", "SỐ_THÀNH_VIÊN_TÍCH_CỰC", "SỐTHÀNHVIÊNTÍCHCỰC", "NUMBEROFACTIVEUSERS");
		addI18nAlias("numberofedits", "SỐ_SỬA_ĐỔI", "SỐSỬAĐỔI", "NUMBEROFEDITS");
		addI18nAlias("numberofviews", "SỐ_LẦN_XEM", "SỐLẦNXEM", "NUMBEROFVIEWS");
		addI18nAlias("pagename", "TÊN_TRANG", "TÊNTRANG", "PAGENAME");
		addI18nAlias("pagenamee", "TÊN_TRANG_2", "TÊNTRANG2", "PAGENAMEE");
		addI18nAlias("namespace", "KHÔNG_GIAN_TÊN", "KHÔNGGIANTÊN", "NAMESPACE");
		addI18nAlias("namespacenumber", "SỐ_KHÔNG_GIAN_TÊN", "SỐKHÔNGGIANTÊN", "NAMESPACENUMBER");
		addI18nAlias("talkspace", "KGT_THẢO_LUẬN", "KGTTHẢOLUẬN", "TALKSPACE");
		addI18nAlias("subjectspace", "KGT_NỘI_DUNG", "KGTNỘIDUNG", "SUBJECTSPACE", "ARTICLESPACE");
		addI18nAlias("fullpagename", "TÊN_TRANG_ĐỦ", "TÊNTRANGĐỦ", "FULLPAGENAME");
		addI18nAlias("subpagename", "TÊN_TRANG_PHỤ", "TÊNTRANGPHỤ", "SUBPAGENAME");
		addI18nAlias("basepagename", "TÊN_TRANG_GỐC", "TÊNTRANGGỐC", "BASEPAGENAME");
		addI18nAlias("talkpagename", "TÊN_TRANG_THẢO_LUẬN", "TÊNTRANGTHẢOLUẬN", "TALKPAGENAME");
		addI18nAlias("subjectpagename", "TÊN_TRANG_NỘI_DUNG", "TÊNTRANGNỘIDUNG", "SUBJECTPAGENAME", "ARTICLEPAGENAME");
		addI18nCIAlias("msg", "NHẮN:", "MSG:");
		addI18nCIAlias("subst", "THẾ:", "SUBST:");
		addI18nCIAlias("msgnw", "NHẮN_MỚI:", "NHẮNMỚI:", "MSGNW:");
		addI18nAlias("img_thumbnail", "nhỏ", "thumbnail", "thumb");
		addI18nAlias("img_manualthumb", "nhỏ=$1", "thumbnail=$1", "thumb=$1");
		addI18nAlias("img_right", "phải", "right");
		addI18nAlias("img_left", "trái", "left");
		addI18nAlias("img_none", "không", "none");
		addI18nAlias("img_center", "giữa", "center", "centre");
		addI18nAlias("img_framed", "khung", "framed", "enframed", "frame");
		addI18nAlias("img_page", "trang=$1", "trang_$1", "page=$1", "page $1");
		addI18nAlias("img_upright", "đứng", "đứng=$1", "đứng_$1", "upright", "upright=$1", "upright $1");
		addI18nAlias("img_border", "viền", "border");
		addI18nAlias("img_baseline", "chân-chữ", "baseline");
		addI18nAlias("img_sub", "chỉ-số-dưới", "sub");
		addI18nAlias("img_super", "chỉ-số-trên", "super", "sup");
		addI18nAlias("img_top", "trên", "top");
		addI18nAlias("img_text_top", "trên-chữ", "text-top");
		addI18nAlias("img_bottom", "dưới", "bottom");
		addI18nAlias("img_text_bottom", "dưới-chữ", "text-bottom");
		addI18nAlias("img_link", "liên_kết=$1", "link=$1");
		addI18nAlias("img_class", "lớp=$1", "class=$1");
		addI18nCIAlias("int", "NỘI:", "INT:");
		addI18nAlias("sitename", "TÊN_MẠNG", "TÊNMẠNG", "SITENAME");
		addI18nCIAlias("ns", "KGT:", "NS:");
		addI18nCIAlias("localurl", "URL_ĐỊA_PHƯƠNG:", "URLĐỊAPHƯƠNG:", "LOCALURL:");
		addI18nCIAlias("articlepath", "ĐƯỜNG_DẪN_BÀI", "ĐƯỜNGDẪNBÀI", "LỐI_BÀI", "LỐIBÀI", "ARTICLEPATH");
		addI18nCIAlias("pageid", "ID_TRANG", "IDTRANG", "PAGEID");
		addI18nCIAlias("server", "MÁY_CHỦ", "MÁYCHỦ", "SERVER");
		addI18nCIAlias("servername", "TÊN_MÁY_CHỦ", "TÊNMÁYCHỦ", "SERVERNAME");
		addI18nCIAlias("scriptpath", "ĐƯỜNG_DẪN_KỊCH_BẢN", "ĐƯỜNGDẪNKỊCHBẢN", "ĐƯỜNG_DẪN_SCRIPT", "ĐƯỜNGDẪNSCRIPT", "SCRIPTPATH");
		addI18nCIAlias("stylepath", "ĐƯỜNG_DẪN_KIỂU", "ĐƯỜNGDẪNKIỂU", "STYLEPATH");
		addI18nCIAlias("grammar", "NGỮ_PHÁP:", "NGỮPHÁP:", "GRAMMAR:");
		addI18nCIAlias("gender", "GIỐNG:", "GENDER:");
		addI18nCIAlias("notitleconvert", "__KHÔNG_CHUYỂN_TÊN__", "__KHÔNGCHUYỂNTÊN__", "__NOTITLECONVERT__", "__NOTC__");
		addI18nCIAlias("nocontentconvert", "__KHÔNG_CHUYỂN_NỘI_DUNG__", "__KHÔNGCHUYỂNNỘIDUNG__", "__NOCONTENTCONVERT__", "__NOCC__");
		addI18nAlias("currentweek", "TUẦN_NÀY", "TUẦNNÀY", "CURRENTWEEK");
		addI18nAlias("localweek", "TUẦN_ĐỊA_PHƯƠNG", "TUẦNĐỊAPHƯƠNG", "LOCALWEEK");
		addI18nAlias("revisionid", "SỐ_BẢN", "SỐBẢN", "REVISIONID");
		addI18nAlias("revisionday", "NGÀY_BẢN", "NGÀYBẢN", "REVISIONDAY");
		addI18nAlias("revisionday2", "NGÀY_BẢN_2", "NGÀYBẢN2", "REVISIONDAY2");
		addI18nAlias("revisionmonth", "THÁNG_BẢN", "THÁNGBẢN", "REVISIONMONTH");
		addI18nAlias("revisionmonth1", "THÁNG_BẢN_1", "THÁNGBẢN1", "REVISIONMONTH1");
		addI18nAlias("revisionyear", "NĂM_BẢN", "NĂMBẢN", "REVISIONYEAR");
		addI18nAlias("revisiontimestamp", "MỐC_THỜI_GIAN_BẢN", "MỐCTHỜIGIANBẢN", "DẤU_THỜI_GIAN_BẢN", "DẤUTHỜIGIANBẢN", "REVISIONTIMESTAMP");
		addI18nAlias("revisionuser", "NGƯỜI_DÙNG_BẢN", "NGƯỜIDÙNGBẢN", "REVISIONUSER");
		addI18nCIAlias("plural", "SỐ_NHIỀU:", "SỐNHIỀU:", "PLURAL:");
		addI18nCIAlias("fullurl", "URL_ĐỦ:", "URLĐỦ:", "FULLURL:");
		addI18nCIAlias("canonicalurl", "URL_CHUẨN:", "URLCHUẨN:", "CANONICALURL:");
		addI18nCIAlias("lcfirst", "CHỮ_ĐẦU_HOA:", "CHỮĐẦUHOA:", "LCFIRST:");
		addI18nCIAlias("ucfirst", "CHỮ_ĐẦU_THƯỜNG:", "CHỮĐẦUTHƯỜNG:", "UCFIRST:");
		addI18nCIAlias("lc", "CHỮ_HOA:", "CHỮHOA:", "LC:");
		addI18nCIAlias("uc", "CHỮ_THƯỜNG:", "CHỮTHƯỜNG:", "UC:");
		addI18nAlias("displaytitle", "TÊN_HIỂN_THỊ", "TÊNHIỂNTHỊ", "DISPLAYTITLE");
		addI18nAlias("newsectionlink", "__LIÊN_KẾT_MỤC_MỚI__", "__LIÊNKẾTMỤCMỚI__", "__NEWSECTIONLINK__");
		addI18nAlias("nonewsectionlink", "__KHÔNG_LIÊN_KẾT_MỤC_MỚI__", "__KHÔNGLIÊNKẾTMỤCMỚI__", "__NONEWSECTIONLINK__");
		addI18nAlias("currentversion", "BẢN_NÀY", "BẢNNÀY", "CURRENTVERSION");
		addI18nCIAlias("urlencode", "MÃ_HÓA_URL:", "MÃHÓAURL:", "MÃ_HOÁ_URL:", "MÃHOÁURL:", "URLENCODE:");
		addI18nCIAlias("anchorencode", "MÃ_HÓA_NEO", "MÃHÓANEO", "MÃ_HOÁ_NEO", "MÃHOÁNEO", "ANCHORENCODE");
		addI18nAlias("currenttimestamp", "MỐC_THỜI_GIAN_NÀY", "MỐCTHỜIGIANNÀY", "DẤU_THỜI_GIAN_NÀY", "DẤUTHỜIGIANNÀY", "CURRENTTIMESTAMP");
		addI18nAlias("localtimestamp", "MỐC_THỜI_GIAN_ĐỊA_PHƯƠNG", "MỐCTHỜIGIANĐỊAPHƯƠNG", "DẤU_THỜI_GIAN_ĐỊA_PHƯƠNG", "DẤUTHỜIGIANĐỊAPHƯƠNG", "LOCALTIMESTAMP");
		addI18nCIAlias("language", "#NGÔN_NGỮ:", "#NGÔNNGỮ:", "#LANGUAGE:");
		addI18nAlias("contentlanguage", "NGÔN_NGỮ_NỘI_DUNG", "NGÔNNGỮNỘIDUNG", "CONTENTLANGUAGE", "CONTENTLANG");
		addI18nAlias("pagesinnamespace", "CỠ_KHÔNG_GIAN_TÊN:", "CỠKHÔNGGIANTÊN:", "CỠ_KGT:", "CỠKGT:", "PAGESINNAMESPACE:", "PAGESINNS:");
		addI18nAlias("numberofadmins", "SỐ_BẢO_QUẢN_VIÊN", "SỐBẢOQUẢNVIÊN", "SỐ_QUẢN_LÝ", "SỐQUẢNLÝ", "SỐ_QUẢN_LÍ", "SỐQUẢNLÍ", "NUMBEROFADMINS");
		addI18nCIAlias("formatnum", "PHÂN_CHIA_SỐ", "PHÂNCHIASỐ", "FORMATNUM");
		addI18nAlias("defaultsort", "XẾP_MẶC_ĐỊNH:", "XẾPMẶCĐỊNH:", "DEFAULTSORT:", "DEFAULTSORTKEY:", "DEFAULTCATEGORYSORT:");
		addI18nCIAlias("filepath", "ĐƯỜNG_DẪN_TẬP_TIN", "ĐƯỜNGDẪNTẬPTIN", "FILEPATH:");
		addI18nCIAlias("tag", "thẻ", "tag");
		addI18nAlias("hiddencat", "__THỂ_LOẠI_ẨN__", "__THỂLOẠIẨN__", "__HIDDENCAT__");
		addI18nAlias("pagesincategory", "CỠ_THỂ_LOẠI", "CỠTHỂLOẠI", "PAGESINCATEGORY", "PAGESINCAT");
		addI18nAlias("pagesize", "CỠ_TRANG", "CỠTRANG", "PAGESIZE");
		addI18nAlias("index", "__CHỈ_MỤC__", "__CHỈMỤC__", "__INDEX__");
		addI18nAlias("noindex", "__KHÔNG_CHỈ_MỤC__", "__KHÔNGCHỈMỤC__", "__NOINDEX__");
		addI18nAlias("numberingroup", "CỠ_NHÓM", "CỠNHÓM", "NUMBERINGROUP", "NUMINGROUP");
		addI18nAlias("staticredirect", "__ĐỔI_HƯỚNG_NHẤT_ĐỊNH__", "__ĐỔIHƯỚNGNHẤTĐỊNH__", "__STATICREDIRECT__");
		addI18nAlias("protectionlevel", "MỨC_KHÓA", "MỨCKHÓA", "MỨC_KHOÁ", "MỨCKHOÁ", "PROTECTIONLEVEL");
		addI18nCIAlias("url_path", "ĐƯỜNG_DẪN", "ĐƯỜNGDẪN", "PATH");
		addI18nCIAlias("url_query", "TRUY_VẤN", "TRUYVẤN", "QUERY");
		addI18nCIAlias("defaultsort_noerror", "không_lỗi", "noerror");
		addI18nCIAlias("defaultsort_noreplace", "không_thay_thế", "noreplace");
		addI18nCIAlias("pagesincategory_all", "tất_cả", "all");
		addI18nCIAlias("pagesincategory_pages", "trang", "pages");
		addI18nCIAlias("pagesincategory_subcats", "thể_loại_con", "subcats");
		addI18nCIAlias("pagesincategory_files", "tập_tin", "files");
	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://vi.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "vi";
	}
}
