/**
 * This file is part of Wikiforia.
 *
 * Wikiforia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Wikiforia is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Wikiforia. If not, see <http://www.gnu.org/licenses/>.
 */
 package se.lth.cs.nlp.wikipedia.lang;

//Autogenerated from Wikimedia sources at 2015-04-16T13:55:11+00:00

public class WarConfig extends TemplateConfig {
	public WarConfig() {
		addNamespaceAlias(-2, "Medya");
		addNamespaceAlias(-1, "Pinaurog");
		addNamespaceAlias(1, "Hiruhimangraw");
		addNamespaceAlias(2, "Gumaramit");
		addNamespaceAlias(3, "Hiruhimangaw_hiton_gumaramit");
		addNamespaceAlias(5, "Hiruhimangraw_hiton_Wikipedia");
		addNamespaceAlias(6, "Paypay", "Fayl");
		addNamespaceAlias(7, "Hiruhimangraw_hiton_paypay", "Hiruhimangraw_hiton_fayl");
		addNamespaceAlias(8, "MedyaWiki");
		addNamespaceAlias(9, "Hiruhimangraw_hiton_MedyaWiki", "Hiruhimangraw_hiton_MediaWiki");
		addNamespaceAlias(10, "Batakan");
		addNamespaceAlias(11, "Hiruhimangraw_hiton_batakan");
		addNamespaceAlias(12, "Bulig");
		addNamespaceAlias(13, "Hiruhimangaw_hiton_bulig");
		addNamespaceAlias(14, "Kaarangay");
		addNamespaceAlias(15, "Hiruhimangraw_hiton_kaarangay");

	}

	@Override
	protected String getSiteName() {
		return "Wikipedia";
	}

	@Override
	protected String getWikiUrl() {
		return "http://war.wikipedia.org/";
	}

	@Override
	public String getIso639() {
		return "war";
	}
}
